= Introduction

https://gsap.com/[GSAP] is a JavaScript animation library built for professionals.

== Getting feet wet

They have their own https://gsap.com/resources[Docs] that you can look through for
tons of insightful and highly produced learning resources. GSAP used to be **paid**,
hence its support is quite strong. It's after a buyout that it became free for
the World Wide Web.

Since I want to leverage this in a React app, we can have a look at their React
tutorial:

https://www.youtube.com/watch?v=l0aI8Ecumy8[Youtube Tutorial]

== GSAP for React

GSAP is framework agnostic. However React can be paired up with it, the idea of
GSAP is to _imperatively animate anything_. DOM transitions, SVGs, Three.js, Canvas,
WebGL. The limits _are on your mind_.

However, there are pain points when trying to pair **GSAP** with **React**.

It is due to the pain points that the GSAP team made a React hook specifically to drop
into a React component, it's a replacement for `useEffect()` or `useLayoutEffect()`,
`useGSAP()` will handle all sorts of cleanup automatically. It can be used on _SSR_,
you can scope animations to specific containers and state also can be the trigger
of an animation.

So, there's tons of things that had to be implemented manually before the hook was
created by _GSAP_, in short, lots of ugliness, due to the fact that React has
`useEffect()` and things get called twice, and sometimes animations stuck around
still taking memory. The main idea is to always clean animations to avoid **memory
leaks**. The ugliness has been simplified (abstracted) away so that you get clean
code that cleans up for you in the background:

[source, code]
====
import { useRef } from 'react'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

const box = useRef()

useGSAP(() => {
	gsap.to(box.current, { x: 360 })
})
====

== GSAP Basics

[NOTE]
====
I learned the hard way that `basics` are king. (By learning Japanese the wrong way).
So I know that it's best to start small, bit by bit, perhaps by doing "boring"
stuff first. But with a clear goal in mind, and specifically taking whatever you
can get (and leaving behind whatever doesn't feel as useful).
====

And so, this is a really basic introduction to how GSAP works, concepts, lingo,
and ideas to start with to then start actually animating whatever we want to
animate.


=== What is GSAP?

GSAP stands for _GreenSock Animation Platform_. This is a suite of tools (with
lots of backing and rewards) that help you animate practically everything with
JavScript. **In any framework**. The _core library_ has everything one should need
to create **blazingly fast**, cross-browser, friendly animations. This platform
has also tons of **plugins** which help with different (and specific) animation
challenges. (_You don't have to learn all of them mandatorily_)


=== GSAP in React

There are specific things to React, but to start with basics, we need to install
the specific **React package** from `GSAP`.

``` 
pnpm install gsap @gsap/react
``` 

It's after this that we can start making our first animation:

[source, typescript]
----
import { useRef } from 'react'

import gsap from 'gsap' <.>
import { useGSAP } from '@gsap/react' <.>

import './App.css'

gsap.registerPlugin(useGSAP) <.>

function App() {
  const container = useRef(null) <.>

  useGSAP(() => { <.>
    gsap.to('.box', { x: 200 }) <.>
  }, { scope: container }) <.>

  return (
    <>
      <div ref={container}> <.>
        <div className='box green'></div> <.>
      </div>
    </>
  )
}

export default App

----
<.> We have to import `gsap` manually in order to make the registration later.
<.> The magic hook that takes care of cleanup is `useGSAP`.
<.> A good practice is to register the hook in order to avoid React version
discrepancies
<.> In modern React versions we need to provide something to `useRef()` hence we
initialize it as null, as the component gets rendered the reference ends up
attached without issues.
<.> As any hook we should use this in place of a `useEffect()`.
<.> And now, all code that we write inside of the hook should be really similar
to anything we get in the docs (both for React and for the simple HTML versions)
<.> We can provide a specific scope so that the animations only get activated
from that specific container.
<.> It's really important to provide a parent container when it comes to the reference
that we attach with `useRef()`, **because when setting up this way GSAP will look
inside of this element**. So if we were to directly use the reference to the `.box`
element, nothing would move since inside of it there's nothing.
<.> This is the actual element we want to animate, and so by making parallels to
what's inside the `useGSAP` hook we can see that this element is selectable through
its `.box` class name.

If we were to reload the page, we should see how our green box is actually being
moved around based on what we fed to GSAP, he then takes care of the rest.

[NOTE]
====
It's best to use the global styles and the styles that the examples the GSAP
docs provide so that we bootstrap and get to the actual thing we are interested
in. (Which is not styling).
====

== Text Animations

== Scroll Animations
