= Notes

== Everything a .NET dev needs to know about configuration and secret management

Notes taken from https://www.youtube.com/watch?v=Vvl8w6OfDCM

The way the .NET framework is very flexible and very powerful. Many organizations
use it in different ways. However we are going to have a formal look as to the
DOs and DONTs.

**Incorrect secret management**

You can get access, Global access to an organization's dev environment. It's
so easy to make mistakes.

More problems:

- Storing secrets in plain text in repos
- Github token in plain code
- R1 AI assistant had horrible security. With API-Keys that allowed to brick all
devices in the world

**Secret Sprawls**

- Have you ever leaked a secret?

=== Configuration

Settings panel of your app. Feature flags, normal flags, change environment variables
and then switching things on/off without re-deploy.

.NET has a configuration system:

- appsettings.json
- Environment variables
- Command-line arguments
- *Other sources

Everything gets aggregated and abstracted into `IConfiguration`. You don't know
what provider gives you that data.

A thing that .NET has for it, is the **Configuration Structure**. `.json` is
the most logical one and the default.

There are objects with nested values, and you can use them with different sections:

````
Configuration.GetSection("Features");
Configuration.GetRequiredSection("Features"); // This throws an exception
````
Configuration system might not change at runtime, so getting an empty object
back should be invalid, so use `GetRequiredSection`.

You can also get some nested value:

````
Configuration.GetValue<bool>("Features:EnableNewUI");
````

_You shouldn't use this in classes though_

The way it works is a series of steps such as this:

````
var builder = new ConfigurationBuilder();

builder.AddEnvironmentVariables();
builder.AddJsonFile("appsettings.json");

var configuration = builder.Build();
````

This begs the question of: _If we have multiple providers, how does it know what
provider to use?_ If all of them contain values? Then order of registration
**matters**.

.NET create a lot of default setups for us, you don't have to do this manually.

The defaults will work like this:

Priority:

- appsettings.json
- appsettings.{ENVIRONMENT}.json = DOTNET_ENVIRONMENT or ASPNETCORE_ENVIRONMENT
	- By default, Development will be setup
	- For test environments you can set that to TEST, STAGING and PRODUCTION
- User Secrets = Only enabled during development. API Keys, Passwords
	- **Not actually secret!**
- Environment variables = Not used during development, but with containers, env
variables are highly used
- Command-line arguments => This will **always win**

=== The Options Pattern

You shouldn't be using `IConfiguration`, nor `IConfiguration.Section` in your
code.

Wouldn't it be cool to create a class, that captures a section of configuration?
We can test things, we can add controls, this is compilable and with way more
metadata and QoL with static type checking.

````
var settings1 = _configuration
	.GetSection("ExternalApiSettings")
	.Get<ExternalApiSettings>();

var settings2 = new ExternalApiSettings();
_configuration.GetSection("ExternalApiSettings").Bind(settings2);
````

This is _bad_. Magic strings in codebase, class needs knowledge of configuration
structure. At runtime the class might break, perhaps because the things are tightly
coupled.

We can treat configuration as code, but we are tightly coupling it. Instead let's
opt into the Options pattern.

services.Configure<ExternalApiSettings>(configuration);

````
public class ExternalApiClient
{
	private readonly ExternalApiSettings _externalApiSettings;

	public ExternalApiClient(IOptions<ExternalApiSettings> options)
	{
		_externalApiSettings = options.Value;
	}

	public void CallExternalApi()
	{
		// Do something with these settings here...
	}
}
````
So this is a singleton, it's lazy, and everything will just flow, and we are
fully treating the configuration retrieval as code.

Validation:

````
public class ExternalApiSettings
{
	[Required]
	public string ApiUrl { get; set; }

	[Required]
	public string ApiKey { get; set; }

	[Range(1, 1_000_00)]
	public int TimeoutInMilliseconds { get; set ;}
}
````
Your application should not startup if it has been configured incorrectly, what
if the connection string for prod gets put in?

````
.AddOptions<ExternalApiSettings>()
.BindConfiguration(nameof(ExternalApiSettings))
.ValidateDataAnnotations()
.ValidateOnStart(); // Highly recommended => That way it will initialize all options and crash if things don't pass.
````

Of course you won't validate a connection string through annotations, but you can
pass validation lambdas for that.

**Keeping it fresh**

Change things on hot, and configurations get auto-applied, no downtime.

- **IOptions<T>**
	- Singleton
	- Read once
	- Most well known
- **IOptionsSnapshot<T>**
	- Scoped
	- Read every scope
	- Useful with web requests
	- Keep performance in mind!
- **IOptionsMonitor<T>**
	- Singleton
	- Read in real-time
	- Uses change notifications
	- Useful with background services

_IOptionsMonitor_ is pretty useful for BackgroundServices.

=== Dealing with Development

How do we prevent mistakes? **DON'T STORE SECRETS IN THE REPO**. Specially if
they have private repositories.

Stuff will leak at one point, _WHEN WILL IT GO WRONG?_

How do you do it in .NET

**User Secrets**

- Don't create .gitignore, appsettings hacks.

There's an already built-in feature that you should be using:

````
dotnet user-secrets init
dotnet user-secrets set "ConnectionStrings:Database" "Data Source=..."
dotnet user-secrets set "AdminPassword" "hunter2"
````

Then something like this:

````
{
	"ConnectionStrings": {
		"Database": "Data Source=..."
	},
	"AdminPassword": "hunter2"
}
````
Will be created outside of the repository:

- `%APPDATA%/Microsoft/UserSecrets/SECRETS_ID/secrets.json`
- `~/.microsoft/usersecrets/SECRETS_ID/secrets.json`

_Be aware:_ NOT ACTUALLY SECRET. It's plain text, on disk. Do not consider this
a fully secure solution though. If the company you are working for doesn't want
secrets in the machine, DON'T.

**Opinions**

appsettings.json
````
{
	"ConnectionStrings": {
		"Database": "<from-keyvault>"
	},
	"AdminPassword": "<from-keyvault>",
	"WelcomeText": "Hello World!"
}
````

appsettings.Development.json
````

{
	"ConnectionStrings": {
		"Database": "<from-user-secrets>"
	},
	"AdminPassword": "<from-user-secrets",
	"WelcomeText": "Hello Developer!"
}
````

_So, there are so many providers, and you might not know where things are coming from,
but it's good to sort of add a template, a small note that anyone can see to point
them in the right direction_ So in here, the `appsettings` files (which are really
powerful already) can be used to add placeholders that will point people in the
right direction.

When you combine this to a developer, you hand-hold them easily.

- Put it in a `README.md`? NAh.... out of sync is easy.

Docker - Kubernetes => Really environment variables driven, so you can adapt
the notes accordingly. However, be pragmatic, focus on what is easier for you.

=== Pushing to Production

The user secrets, doesn't work in production. We need to look for different approaches.

````
{
	"Logging": {
		"LogLevel": {
			"Default": "Information",
			"Microsoft.AspNetCore": "Warning"
		}
	},
	"ConnectionStrings": {
		"Database": #{CSTRING_DATABASE}#"
	},
	"ApiKey": "${APIKEY}"
}
````
This approach is used in the wild, and it breaks away the mechanism of the priorities
in .NET already. Why overwrite lower providers?. You could change into Environment
Variables => Maybe a bit harder for developers to steal secrets.

.NET Wants you to use another provider, or add your own provider even.

**Azure Key Vault**

- Store keys, secrets and certificates in Azure
- Can be used as a configuration provider, simplifying deployment!
- Integrates with other Azure services
- Useful during development as well!

Many Key Vault providers have their Nuget packages, that you can add into your
DI, and a new provider with higher priority will be added. So that at start-up
your app will go into the vault, grab all the config values it needs and then
apply them into the `IConfiguration` abstraction. This is also really useful
during development. (And with these providers you keep the secrets in memory which
is more secure)

- With a provider, you wouldn't have to spend any time setting up secrets which is
really boring.
	- It can become a Super F5

**Azure App Configuration**

- Configuration as a service
- Store application configuration and feature flags in 1 place
- Change configuration without redeploying
- Integrates with Azure Key Vault

Different approaches you can use, maybe hybrids so that yes, you get the info
from a service, but then you override with your local secrets if you need to swap
out things for your testing or dev purposes.

**But there's a problem.** - How can we securely connect to these services?

- If anyone can access the Key Vault? Not really secured is it?
	- If you can easily just connect, without a user and a password, then it just
	would suck.
- Azure Authentication
	- This is an Azure Service
	- It also has an Azure Authentication Library
