= Notes

== Structured logging, Serilog, Seq, Rust, and .NET 8 with Nicholas Blumhardt

Notes taken from: https://www.youtube.com/watch?v=AHw15plsuN0

- Serilog it's a logging structure that looks like any other logging library
- But in the background/hunder the hood, it smuggles all this structure and
metadata richness that should help make things much more easier when debugging
issues.
	- Many people consume the libraries, without knowing the full capabilities,
	and without really appreciating how amazing it can be to have a rich event
	stream flowing out of applications for free
	- The ideas in Serilog, `Microsoft.Extensions.Logging` are many amalgamations
	of ideas, of compatibility, and improvements of the tooling and the ecosystem
	overall
		- Logs into strings

**Structure Logging:** Completely different story to the usual story of "producing
text logs". It really is about producing an event, a log event, in such a format,
that you can then refine, query, and overall bend to your will. _In a human
friendly way_. The idea is to keep the events rich with correlation info. So
you can slice the data, and navigate the events, and finally reach to that one
thread that explains the cause of your bug, your outage. Etc.

- **Flame Charts won't write themselves**

=== DevOps and Observability

Ten years ago, the DevOps territory was a bit "subversive". No one came to a project
with budget to automate deployments or testing or builds or to build runtime information
like instrumentation into an app. It was always something the developers had to kind
of _squeeze_ in. **In the crumbs of the time left**.

_Now ten years later, it's the imperative to make_. Everything automated, repeatable,
instrumented, observable.

**As developers we should be careful to not lose our claim to that territory**.

- Structured Logging
- OTEL
- Traces
- Metrics
- Single pane glasses

**Observability trends**

- But we always made apps be observable, there were always techniques and ideas.
	- You wouldn't look at logs or whatever.
		- You would use an endpoint hit with Postman, and do an "EXPLAIN" query
		to the database.
			- You would get timings, execution plans, everything would be so
			good. (AND THIS IS BUT ONE OUT OF A MILLION)

_The focus on traces, logs, has made it so easy to comoditize_. But as developers
and ops people we need to creatively build observability and internal state
visibility.

_A lot of what makes DevOps amazing is practices and how devs engage with what
they are doing_

- People, Process AND tools

=== Datalust - Seq

- Logs => Are easy to understand with ONE application
	- But most applications today, are more than just one application. They are
	an orchestra
		- Logging is CHAOS in these environments
			- It creates a lot of noise, and you need to somehow make sense of that

Seq => The power of this tool is that when you have data coming from 10 million
places, like an orchestra, LOTS of noise, you simply walk up, write a query. And
you instantly can hear the music of what melody is being played in an app.

- Seq was built to scratch an itch, **there was a gap between log files and something
(a consulting team)**, the creator was built as something close to a log file, but
with extra bells and whistles. (Reports, easy filtering).

- Use signals
- Filter everything else

_Being able to pick any aspect, go and follow all the events and follow the story,
the trace_.

Seq => Whatever you attach to your logs, Seq doesn't have an off-the-shelf interface,
you create the developer interface that you want. Seq surfaces that implicit schema.

[NOTE]
====
For things you are investing in a long time. Big systems, lots of requirements,
microservices. **Think about your goals for instrumentation and diagnostics**.
Think about how to trace in the domain that you are going to build for.
====

Seq => Parses it all. And we get to search in what is gotten there.

[IMPORTANT]
====
If you build instrumentation from the beginning. You get a feel for what it pays
for itself, and you can tune data collection based on issues and bugs. And all other
things.
====

- When you don't think about observability and logs
	- You just have to create a huge search index over a pile of questionable stuff
		- If you don't build it from the start, you lose the navigation and events,
		and things you can focus on
		- Everything becomes robust if you are actively focusing on this
		- Correlation helps moving from one system from another really seamlessly
			- Deployment ID
				- When recording log events

Once you have all of the data in there

You get to chart as much as you want.

- Seq => True observability. "You need to observe your apps running in the wild".
Things catch on fire, and things get progressively worse. Seq helps with all of
that.

- Log events as a basis for observability => If you are instrumenting a program
you pretty quickly find out is that the only thing you can attach meaningfully to
it is **EVENTS**.

You can't really bind some state into a live-running application, you have to
surface out your app's state through events. In the least kind of intrusive and
destructive way.

- You can construct events to build up metrics
	- Count the order of numbers
		- By not adding it explicitly to your app
- Traces are also the same, events that have to be correlated
	- **BUT YOU CAN'T GO THE OTHER WAY**. Traces are a high level construct.

- PLEASE KICKSTART THINGS WITH CORRELATION IDs.

The neat thing about logs is that you can see all the individual things that happened
when an app reacted and an event took place.

=== Seq CLI

Seq has an API.

Octopus => They rewrote their CLI from C# into Go. And we are (2023) in a CLI
tool renaissance.

There's a "Cobra" framework for CLI tools in Go. C# also has a library for building
CLI tools.

- CLI is a big integration point for automatically provisional a process in Datalust

- Seq's idea => You are searching for newer logs, you are going to get them faster,
we build things from recent to older in terms of speed also.

- Seems they used Rust to build the Seq baseline. (Gotta go FEST)

_It's hard to achieve sweet spots for use cases in which the Garbage Collector
gets in the way_ That's the reason moved onto Rust.

HCL => Hashicorp Configuration Language. Widely popular for Infrastructure as Code.

_Hopefully .NET world embraces Rust_

- FrozenDictionary => Interesting class that you initialize, and it then optimizes
itself for future lookups

- Native AOT = It would be nice if .NET goes further into the way Rust deals with
native compilation.
	- Go it's a good middlepoint with "fast enough", and "optimized enough"
	- Go => Choose over Rust if you don't deal with enough of the problems Rust
	aims to solve

Rust => Great ecosystem, kinda like Nuget. Most ecosystems are pretty robust, and
you can operate with most OS features plus services.

=== Open Telemetry

Metrics, Logs, Traces.

- It was an initiative around 2023. And if you adhere to it, you can get high
quality log data into it
	- "Reduce the total number of standards". But don't think it's the be-all-end-all
	- It would be nice that everything speaks to the same Protocol
		- Gilf is another standard for logs
	- Issues with interops efforts, _on the surface everything seems to work well_,
	but actually getting consistent useful data out of all streams is challenging
		- We should not get too distracted by the transport
		- We should focus on the quality of the data we put it
			- If you don't write useful logs, if you don't control the volume of
			data, (DEVELOPERS ARE RESPONSIBLE OF PRODUCING QUALITY DATA). You need
			to think of how to instrument your domain, and how to make that work
			for you

Open Telemetry => They are writing custom sources, sinks, so they are giving
implementations for their spec and things that are useful for the broad community.

- **It's all down to practices, not tools**

== OpenTelemetry Deep Dive: Resilience & High Availability in the OTel Collector

Notes taken from https://www.youtube.com/watch?v=sSFxavH7S1E

== You are doing logging in .NET wrong. Let’s fix it. - Nick Chapsas - NDC Oslo 2023

Notes taken from https://www.youtube.com/watch?v=d1ODcHi5AI4

**You don't need logging**

- Optimization of string allocations

`logger.LogInformation("Hello!");` => What is this?

=== Rule 1

"The message is actually the message template and shall be treated as such"

If you want to get useful information out of your logs, if you do log messages
bad, that will be a challenge.

=== Rule 2

"I shall not use string interpolation or concatenation in the message template"

- Structured Logs

`logger.LogInformation("Payment with id {PaymentId} failed with status {PaymentStatus}", id, status);`

When you add these template names, you will have them available for query purposes,
you can isolate parameters for specific questions you might have

**BUT THIS IS STILL BOXING**

- Yeah, but we will allocate once this string at the beginning of the application.
	- For each message, this is something that cannot be done with the other
	string allocation tecniques.

=== Rule 3

"I shall use structured logging and give good names to my parameters"

Choose a name, and have that name be consistent, be universal even. That way you
will make **sense of what the parameter belongs to**

- Serilog => Prevents Boxing

**Log Level:**

Verbose,
Debug,
Information,
Warning,
Error,
Fatal

- Any log and trace you are pushing is associated with a log level.

The way logs are "filtered" is because of a **threshold**. You set a threshold,
and that lets different levels go in.

=== Rule 4

"I shall preven unnecessary boxing for inactive log levels"

**Logging source generator**

_GENERICS DO NOT BOX_

=== Rule 5

"I shall consider using source generated loggers"

If you want SUPER DUPER FAST LOGS

**You can build your custom interpolated string handler** So that it's efficient
and you can parse interpolated strings without boxing nor anything. AND THEIR
PARAMETERS ARE EXTRACTED IN LOG ANALYSIS TOOLS.

=== Rule 6

"I shall not get too clever with tooling"

Log Level

- Default level if Information for .NET
	- Microsoft.AspNetCore => "Warning" (Why? Because for a single request you
	get a sea of logs)

Logs are just a single tool - Don't use them for everything. You can use something
as simple as Prometheus, Grafana.

- You only take a look at logs when something goes wrong, and you need to fix it.

**You don't need most of your information logs**, and you certainly don't need them
for all the domain and subdomains of your app.

You mostly care about critical, error logs. Yet, you still need sometimes information
logs to put together what the heck happened.

And so, what if you make a log category? A custom one, and what if you inject it
there? So that only when you use that category you see Information? Even then,
LOG SPARSELY.

- Good Practice: Set things to warning

**LOG WHAT REALLY, REALLY MATTERS**

=== Rule 7

"I shall consider using Warning as the default LogLevel"

[IMPORTANT]
====
Premature optimization is the root of all evil.

DON'T USE THIS QUOTE TO TAKE RESPONSIBILITY OF US DOING THINGS RIGHT. Performance
is a happy little accident of learning about logs and performance with them.
====

- **Why do we log?**

- Treat logging, and writing logs, as the things that you can use to put together
a story. You need to be a story-teller.
	- Aim to be concise, and still know what happened from beginning to end

- Log accurate, descriptive and short messages
- System consistent parameter names
- Properly utilized log levels

=== Rule 8

I shall log only what's necessary to tell a good story
