= Notes

== Structured logging, Serilog, Seq, Rust, and .NET 8 with Nicholas Blumhardt

Notes taken from: https://www.youtube.com/watch?v=AHw15plsuN0

- Serilog it's a logging structure that looks like any other logging library
- But in the background/hunder the hood, it smuggles all this structure and
metadata richness that should help make things much more easier when debugging
issues.
	- Many people consume the libraries, without knowing the full capabilities,
	and without really appreciating how amazing it can be to have a rich event
	stream flowing out of applications for free
	- The ideas in Serilog, `Microsoft.Extensions.Logging` are many amalgamations
	of ideas, of compatibility, and improvements of the tooling and the ecosystem
	overall
		- Logs into strings

**Structure Logging:** Completely different story to the usual story of "producing
text logs". It really is about producing an event, a log event, in such a format,
that you can then refine, query, and overall bend to your will. _In a human
friendly way_. The idea is to keep the events rich with correlation info. So
you can slice the data, and navigate the events, and finally reach to that one
thread that explains the cause of your bug, your outage. Etc.

- **Flame Charts won't write themselves**

=== DevOps and Observability

Ten years ago, the DevOps territory was a bit "subversive". No one came to a project
with budget to automate deployments or testing or builds or to build runtime information
like instrumentation into an app. It was always something the developers had to kind
of _squeeze_ in. **In the crumbs of the time left**.

_Now ten years later, it's the imperative to make_. Everything automated, repeatable,
instrumented, observable.

**As developers we should be careful to not lose our claim to that territory**.

- Structured Logging
- OTEL
- Traces
- Metrics
- Single pane glasses

**Observability trends**

- But we always made apps be observable, there were always techniques and ideas.
	- You wouldn't look at logs or whatever.
		- You would use an endpoint hit with Postman, and do an "EXPLAIN" query
		to the database.
			- You would get timings, execution plans, everything would be so
			good. (AND THIS IS BUT ONE OUT OF A MILLION)

_The focus on traces, logs, has made it so easy to comoditize_. But as developers
and ops people we need to creatively build observability and internal state
visibility.

_A lot of what makes DevOps amazing is practices and how devs engage with what
they are doing_

- People, Process AND tools

=== Datalust - Seq

- Logs => Are easy to understand with ONE application
	- But most applications today, are more than just one application. They are
	an orchestra
		- Logging is CHAOS in these environments
			- It creates a lot of noise, and you need to somehow make sense of that

Seq => The power of this tool is that when you have data coming from 10 million
places, like an orchestra, LOTS of noise, you simply walk up, write a query. And
you instantly can hear the music of what melody is being played in an app.

- Seq was built to scratch an itch, **there was a gap between log files and something
(a consulting team)**, the creator was built as something close to a log file, but
with extra bells and whistles. (Reports, easy filtering).

- Use signals
- Filter everything else

_Being able to pick any aspect, go and follow all the events and follow the story,
the trace_.

Seq => Whatever you attach to your logs, Seq doesn't have an off-the-shelf interface,
you create the developer interface that you want. Seq surfaces that implicit schema.

[NOTE]
====
For things you are investing in a long time. Big systems, lots of requirements,
microservices. **Think about your goals for instrumentation and diagnostics**.
Think about how to trace in the domain that you are going to build for.
====

Seq => Parses it all. And we get to search in what is gotten there.

[IMPORTANT]
====
If you build instrumentation from the beginning. You get a feel for what it pays
for itself, and you can tune data collection based on issues and bugs. And all other
things.
====

- When you don't think about observability and logs
	- You just have to create a huge search index over a pile of questionable stuff
		- If you don't build it from the start, you lose the navigation and events,
		and things you can focus on
		- Everything becomes robust if you are actively focusing on this
		- Correlation helps moving from one system from another really seamlessly
			- Deployment ID
				- When recording log events

Once you have all of the data in there

You get to chart as much as you want.

- Seq => True observability. "You need to observe your apps running in the wild".
Things catch on fire, and things get progressively worse. Seq helps with all of
that.

- Log events as a basis for observability => If you are instrumenting a program
you pretty quickly find out is that the only thing you can attach meaningfully to
it is **EVENTS**.

You can't really bind some state into a live-running application, you have to
surface out your app's state through events. In the least kind of intrusive and
destructive way.

- You can construct events to build up metrics
	- Count the order of numbers
		- By not adding it explicitly to your app
- Traces are also the same, events that have to be correlated
	- **BUT YOU CAN'T GO THE OTHER WAY**. Traces are a high level construct.

- PLEASE KICKSTART THINGS WITH CORRELATION IDs.

The neat thing about logs is that you can see all the individual things that happened
when an app reacted and an event took place.

=== Seq CLI

Seq has an API.

Octopus => They rewrote their CLI from C# into Go. And we are (2023) in a CLI
tool renaissance.

There's a "Cobra" framework for CLI tools in Go. C# also has a library for building
CLI tools.

- CLI is a big integration point for automatically provisional a process in Datalust

- Seq's idea => You are searching for newer logs, you are going to get them faster,
we build things from recent to older in terms of speed also.

- Seems they used Rust to build the Seq baseline. (Gotta go FEST)

_It's hard to achieve sweet spots for use cases in which the Garbage Collector
gets in the way_ That's the reason moved onto Rust.

HCL => Hashicorp Configuration Language. Widely popular for Infrastructure as Code.

_Hopefully .NET world embraces Rust_

- FrozenDictionary => Interesting class that you initialize, and it then optimizes
itself for future lookups

- Native AOT = It would be nice if .NET goes further into the way Rust deals with
native compilation.
	- Go it's a good middlepoint with "fast enough", and "optimized enough"
	- Go => Choose over Rust if you don't deal with enough of the problems Rust
	aims to solve

Rust => Great ecosystem, kinda like Nuget. Most ecosystems are pretty robust, and
you can operate with most OS features plus services.

=== Open Telemetry

Metrics, Logs, Traces.

- It was an initiative around 2023. And if you adhere to it, you can get high
quality log data into it
	- "Reduce the total number of standards". But don't think it's the be-all-end-all
	- It would be nice that everything speaks to the same Protocol
		- Gilf is another standard for logs
	- Issues with interops efforts, _on the surface everything seems to work well_,
	but actually getting consistent useful data out of all streams is challenging
		- We should not get too distracted by the transport
		- We should focus on the quality of the data we put it
			- If you don't write useful logs, if you don't control the volume of
			data, (DEVELOPERS ARE RESPONSIBLE OF PRODUCING QUALITY DATA). You need
			to think of how to instrument your domain, and how to make that work
			for you

Open Telemetry => They are writing custom sources, sinks, so they are giving
implementations for their spec and things that are useful for the broad community.

- **It's all down to practices, not tools**

== OpenTelemetry Deep Dive: Resilience & High Availability in the OTel Collector

Notes taken from https://www.youtube.com/watch?v=sSFxavH7S1E

== You are doing logging in .NET wrong. Let’s fix it. - Nick Chapsas - NDC Oslo 2023

Notes taken from https://www.youtube.com/watch?v=d1ODcHi5AI4

**You don't need logging**

- Optimization of string allocations

`logger.LogInformation("Hello!");` => What is this?

=== Rule 1

"The message is actually the message template and shall be treated as such"

If you want to get useful information out of your logs, if you do log messages
bad, that will be a challenge.

=== Rule 2

"I shall not use string interpolation or concatenation in the message template"

- Structured Logs

`logger.LogInformation("Payment with id {PaymentId} failed with status {PaymentStatus}", id, status);`

When you add these template names, you will have them available for query purposes,
you can isolate parameters for specific questions you might have

**BUT THIS IS STILL BOXING**

- Yeah, but we will allocate once this string at the beginning of the application.
	- For each message, this is something that cannot be done with the other
	string allocation tecniques.

=== Rule 3

"I shall use structured logging and give good names to my parameters"

Choose a name, and have that name be consistent, be universal even. That way you
will make **sense of what the parameter belongs to**

- Serilog => Prevents Boxing

**Log Level:**

Verbose,
Debug,
Information,
Warning,
Error,
Fatal

- Any log and trace you are pushing is associated with a log level.

The way logs are "filtered" is because of a **threshold**. You set a threshold,
and that lets different levels go in.

=== Rule 4

"I shall preven unnecessary boxing for inactive log levels"

**Logging source generator**

_GENERICS DO NOT BOX_

=== Rule 5

"I shall consider using source generated loggers"

If you want SUPER DUPER FAST LOGS

**You can build your custom interpolated string handler** So that it's efficient
and you can parse interpolated strings without boxing nor anything. AND THEIR
PARAMETERS ARE EXTRACTED IN LOG ANALYSIS TOOLS.

=== Rule 6

"I shall not get too clever with tooling"

Log Level

- Default level if Information for .NET
	- Microsoft.AspNetCore => "Warning" (Why? Because for a single request you
	get a sea of logs)

Logs are just a single tool - Don't use them for everything. You can use something
as simple as Prometheus, Grafana.

- You only take a look at logs when something goes wrong, and you need to fix it.

**You don't need most of your information logs**, and you certainly don't need them
for all the domain and subdomains of your app.

You mostly care about critical, error logs. Yet, you still need sometimes information
logs to put together what the heck happened.

And so, what if you make a log category? A custom one, and what if you inject it
there? So that only when you use that category you see Information? Even then,
LOG SPARSELY.

- Good Practice: Set things to warning

**LOG WHAT REALLY, REALLY MATTERS**

=== Rule 7

"I shall consider using Warning as the default LogLevel"

[IMPORTANT]
====
Premature optimization is the root of all evil.

DON'T USE THIS QUOTE TO TAKE RESPONSIBILITY OF US DOING THINGS RIGHT. Performance
is a happy little accident of learning about logs and performance with them.
====

- **Why do we log?**

- Treat logging, and writing logs, as the things that you can use to put together
a story. You need to be a story-teller.
	- Aim to be concise, and still know what happened from beginning to end

- Log accurate, descriptive and short messages
- System consistent parameter names
- Properly utilized log levels

=== Rule 8

I shall log only what's necessary to tell a good story

== Practical OpenTelemetry in .NET 8

Notes taken from https://www.youtube.com/watch?v=WzZI_IT6gYo

**What is Observability?**

_Control Theory => It's not new, it's something we have repurposed_

- Is about understanding and debugging unknown-unknowns; the ability to understand
any inner system state just by asking questions from outside the system.
	- Things that we needed to know when we wrote the code
	- The outputs are "telemetry", "telemetry signals"

The definition doesn't include logs, traces, profiles, events. Nothing of what
Open Telemetry has currently.

**Observability:** The ability to understand the inner system state. CAN YOU?
HOW??? **NOT IMPORTANT**

**ASK QUESTIONS**

- What was the impact of my change?
- Is the code being used?
- Is the feature being used?
- Has the time for any action changed?
- How are those third parties doing?
- How is cross-region latency going?

CAN WE ANSWER THOSE QUESTIONS?

_Why does Observability Matter?_

- Engineers are overworked

We're asking engineers to:

- Ship more often
	- Not 6 month-cycle => Customer expectations have changed
- Produce better code
- Spend lesse time fixing bugs and more time creating value
- Decrease downtime

**The expectations of stakeholders, are not where they were**. Now downtime can
lose you millions.

_Generally, if something goes down for 30 seconds, we will go somewhere else_

- If we don't give engineers better tools, better ways to do all these things with
these new expectations, is just not sustainable.

=== Working in production is challenging

- There's way more to know
	- Event Driven Architecture
	- Multiple Services
- We're afraid to break things
- We've forgotten what we've built by the time it ships
- We can't figure out what's wrong and fix it

**Production is scary**

- How do we move from a scaredy-cat culture, then make production **a member of
the team**
	- A way to deliver value to your customers. THAT'S WHERE OPEN TELEMETRY COMES IN.

=== What is OpenTelemetry?

- Protocol
	- How do we transfer in a standards compliance way all sorts of telemetry
	data to a backend to which we can then visualize and start answering all the
	**questions**
	- _This is what OPTL is powerful_
		- No vendor
		- Opinionated on TRANSFER, NO STORAGE, NO ANALYSIS
- SDKs => You move between different languages, BUT CONCEPTS STICK.
- Current Signals:
	- Traces (Stable) => The first thing that was built, and the most stable
	- Metrics (stable)
	- Logs (Only Protocol is stable)
		- .NET is stable with Logs, so you are COVERED

=== What is a Trace?

- The "thing" that is being done
	- We don't create a Trace
	- We create spans with the same trace id
- When we create a span, we use the same trace id
	- A trace represents a context, a path through your system

=== What is a span?

- Structured Blob of data that also has:
	- UniqueId (SpanId)
	- CorrelationId (TraceId)
	- Duration
	- Timestamp
	- CausalityId (ParentSpanID)
		- Thanks to this, you can get a trace waterfall

Traces => **FANCY LOGS**

=== What is a Log?

- Designed for humans
	- We took those, threw them into JSON, and made **structured logs**
- Useful for:
	- Access logs
	- Audit logs
	- Debugging tracing

=== Doing logging wrong

Everything you do on a log, can be replaced by a span, or span event.

You can't? => Legacy systems => Yeah probably logging.

What is a log? - Logs are fine

=== What is Auto-instrumentation?

- Codeless Instrumentation
- Environment Variable Config
- Sideloaded
	- An agent gets in the middle, it wraps exception data, and stuff
	- An OPTL agent is pretty nice
- Getting started
- Verbose
	- Lacks your context
	- Because it adds every single action that happens, and that data gets very
	large. And we are not going towards that. PLEASE BE INTENTIONAL WITH WHAT YOU
	ADD TO YOUR TELEMETRY.

=== Install with Powershell

There are powershell modules you can bring in, you can also bring stuff in with
containers.

You get auto-instrumentation, and you can configure with env variables with where
to send telemetry.

You can START LIKE THAT.

=== Chat is Coded Instrumentation?

- Application Startup
- Targeted => You target the libraries you think will give you good insights
	- SqlServer => You want a span?
	- ITERATIVE PROCESS, add, remove, FIND WHERE YOUR BALANCE IS
- Full control (what are you instrumenting? How? What context you are adding?)
- **Intentional**, we are adding OUR context, we are far away from there

=== Adding Logging

- `dotnet add package OpenTelemetry`
- `dotnet add package OpenTelemetry.Exporter.OpenTelemetryProtocol`

````
var builder = WebApplication.CreateBuilder(args);

builder.Logging.AddOpenTelemetry(loggingOptions => {
	loggingOptions.AddOtlpExporter();
});

var app = builder.Build();
````

=== Adding Metrics


- `dotnet add package OpenTelemetry`
- `dotnet add package OpenTelemetry.Extensions.Hosting`

````
var builder = WebApplication.CreateBuilder(args);

builder.Logging.AddOpenTelemetry()
	.WithMetrics(mp => {
		mp.AddOtlpExporter();
	})
});

var app = builder.Build();
````

=== Adding Traces


- `dotnet add package OpenTelemetry`
- `dotnet add package OpenTelemetry.Extensions.Hosting`

````
var builder = WebApplication.CreateBuilder(args);

builder.Logging.AddOpenTelemetry()
	.WithTracing(mp => {
		mp.AddOtlpExporter();
	})
});

var app = builder.Build();
````

[IMPORTANT]
====
It's not hard dude. WHY ARE YOU DOING AUTO INSTRUMENTATION?
====

=== ResourceBuilder Setup

Everything that gets sent to a backend, is separated into two segments:

- Resource Attributes
	- The moment you set these up, then every single signal that is sent to the
	backend, will inherit these
	- Good for data center region, your pod name, pod IP address, start time of
	your pod, name of your service
	- DON'T USE SLOTS BECAUSE NOTHING CHANGES UNTIL YOU RESTART AN APP

- You might send 100 spans, but you send resource attributes ONCE.

**Add Attributes, it's not hard**

[source, csharp]
----
builder.Services.AddOpenTelemetry()
	.ConfigureResource(resourceBuilder =>
		resourceBuilder
			.AddService("practical-otel")
			.AddAttributes(new List<KeyValuePair<string, object>> {
				new("my-attribute", "my-value")
			})
	)
----
Applies to: Spans, Metrics, Log Entries. Examples: Cloud/Datacentre Region, Pod
Name, AppService Name, Application Version

=== Instrumentation Libraries

We need to generate span data.

- Language and SDK specific
- Opinionated Library instrumentation
	- SQLClient
	- HttpClient
	- gRPC/Http
	- All of the backing services that you have, they might get instrumentated
	libraries

Basics:

- `OpenTelemetry.Instrumentation.AspNetCore`
- `OpenTelemetry.Instrumentation.Http`
- `OpenTelemetry.Instrumentation.SqlClient`

- `AddAspNetCoreInstrumentation()`
- `AddSqlClientInstrumentation()`
- `AddHttpClientInstrumentation()`
- `AddOtlpExporter()`

- `.WithTracing()`
- `.WithMetrics()`

In `.NET 8` there are some extra meters that you can use:

- `AddMeter("Microsoft.AspNetCore.Hosting")`
- `AddMeter("Microsoft.AspNetCore.Server.Kestrel")`

With all of these things you can build pretty dashboards. With them you can tell
management and show what you do.

- _They are not really useful, but yeah_

`Npgsql.Telemetry`, `OpenTelemetry.Instrumentation.EntityFrameworkCore`

- Redis
- GO TO DOCS AND COPY THE CODE

=== Metric Instrumentation

There is some debate, whether a static class, Singleton, or whatever:

[source, csharp]
----
public static class DiagnosticsConfig
{
	public const string ServiceName = "practical-otel-bff";
	public static Meter Meter = new(ServiceName);
	public static Histogram<double> SalesValue = Meter.CreateHistogram<double>("sales.value");
	public static Histogram<double> SalesMarkupValue = Meter.CreateHistogram<double>("sales.markup");
	public static Counter<long> SalesCount = Meter.CreateCounter<long>("sales.count");
	public static ActivitySource Source = new ActivitySource(ServiceName);
}

builder.Services.AddOpenTelemetry()
	.WithMetrics(meterProviderBuilder => {
		meterProviderBuilder
			.AddMeter(DiagnosticsConfig.Meter.Name)
			.AddOtlpExporter();
	});
----
The meter work on the name, nothing else. You would want to create one or two
meters per assembly. Why the second? That could be the filter level.

In activity sources you can say: Listen to this activity source, but not these
other activity source.

- Kinda are like log levels
	- Low Level
	- High Level

- **We create a Meter, and then we create different instruments**
	- We register them by adding a name
		- Everything runs OFF THE NAME, hence that is your ID

[source, sql]
----
public static void AddSalesMetrics(int productId, decimal price, decimal priceWithMarkup)
{
	var labels = new KeyValuePair<string, object?> (DiagnosticsNames.ProductId, productId);

	DiagnosticsConfig.SalesValue.Record((double)priceWithMarkup, labels);
	DiagnosticsConfig.SalesMarkupValue.Record((double)(priceWithMarkup - price), labels);
	DiagnosticsConfig.SalesCount.Add(1, labels);
}
----
**Remember that metric systems are LOW CARDINALITY, they are time series, you shouldn't
send hundreds of time series to databases**. Every unique combination of labels
is a unique time series. HIGH LEVEL COST SIGNALS. They can tell something is going
wrong. It doesn't why WHAT, but a fuzzy idea. Tracing or logs give **GRANULAR
INFO**

=== Tracing Instrumentation

- Time bound analysis
	- Span => OTel concept. Activity (that's what is called in .NET)
	- I want to wrap this piece of code, how long it took. You are scoping bits
	of code and tracing it through an activity. You want to know the time of.
- Scoped piece of work
- Causality
	- It gives you a trace waterfall
		- You can debug through the whole thing
- Correlation
	- This comes by default => This is our parent, and he has the correlation
- Useful for measuring complex code
- ...Everything a log has and more

=== Creating ActivitySource - Static

[source, csharp]
----
public static class DiagnosticsConfig
{
	public const string SourceName = "product-service";
	public static ActivitySource Source = new ActivitySource(SourceName);
}

public IActionResult Load()
{
	using var activity = DiagnosticsConfig.Source.StartActivity("Load Page");
	return View();
}
----
DO NOT SINGLETON, DO NOT SCOPED. But an activity source as a static should be
wrapped with the DI service.

=== Additional Context Best Practices

If you want to add a ton of data into a span, build extension methods that make
things standard and clean up code:

[source, sql]
----
static class ActivityExtensions
{
	public static void EnrichWithPerson(this Activity activity, Person person)
	{
		activity.SetTag("firstname", person.Firstname);
		activity.SetTag("surname", person.Surname);
	}
}

app.MapGet("/person", ([AsParameters]Person person) => {
	Activity.Current?.EnrichWithPerson(person);

	return TypedResults.Ok($"Hi {person.Firstname} {person.Surname}");
});
----

**Manual Spans**

- Create an activity that wraps the bit of code that we think will change in
performance
	- We will add attributes before, and then after
	- **We don't know if this will be useful** But we'd like to have that data
		- Tracing signals are something you keep for a short amount of time,
		NOT FOREVER
		- Keep metrics for as long as you want, they are cheap
			- Since traces should be cleaned up periodically, ADD MORE DATA TO THEM.

CREATE CONSTANTS THAT DEFINE THE CONCEPTS:

````
public static class DiagnosticsNames
{
	public const string ProductCategoryId = "product.category.id";
	public const string OriginalProductPrice = "product.price.original";
	public const string NewProductPrice = "product.price.with_markup";
	public const string CalculateProductMarkupName = "Calculate Product Price With Markup";
}
````
Everybody calls things differently, you don't want to be cleaning up data, because
everyone chose a different thing and now you don't have anything standarized. And
not only that, you can add some documentation on top of everything that you are
putting behind a static class. (When should you use this? How? Why?)

**No magic strings: EASIER TO NAVIGATE**

- Use Extension methods for consistency, not wrapper
	- Add the parameters of your method before calling the activity, not after (performance
	gains)

````
using var activity = DiagnosticsConfig.Source
	.StartActivityWithTags(DiagnosticNames.CalculateProductMarkupName,
	new() {
		new(DiagnosticsNames.ProductCategoryId, categoryId),
		new(DiagnosticsNames.OriginalProductPrice, productPrice)
	});

````

=== Activity vs Activity.Current

If you haven't registered an activity in OTel, then when trying to create the
Activity it will return null so better to write defensive code that will try
to get the Activity, and then attach something:

````
using var activity = //...;
activity?.SetTag(...)
````

If you use `Activity.Current` you will have spans from perhaps other trace, getting
attached whatever attributes you are attaching

=== Adding Additional Context
