= Notes

Notes taken from https://www.youtube.com/watch?v=CTknA1gykmg

Basically this is a video about tips, principles, good advice that is the result
of 15 years of experience, and what to look out for, or keep in mind as constants
or truths from the trade.

== Disruption moves very fast, adaptation is very slow

Experience can be "big". However, you might not have the experience that is
demanded TODAY.

If you can influence the speed at which you adapt => You will be much better off.

Example: AI

AI capabilities => LLMs, AI features

If you have a lot of experience, you have more skills, and you need to spend just
a bit of time skilling up in AI. (You have an advantage). And when you are in the
other end of the spectrum, you can focus a lot on the skills that are being asked
today.

Fundamentals + AI enhanced development & learning

**Pair things with AI learning and the usage of Agents**

- Agentic Software Engineering

== Find mentors

Try to find a person you can offload skills from. Person to person is going to give
you the most value.

- _Engineering blogs_
- _Finding a podcast you might be interested in_
	- Instead of just tutorials, because that's where the real value is
	- LLMs can explain, give examples
		- But experiences, sharing tricks of the trade, is something you get from
		PEOPLE

_You learn how people think, what's valuable, what's not valuable, problems people
face_.

_Note: Check out Discord's article on their NO-SQL decision_

Sometimes people jump from tutorial to tutorial, learning things that yes build
over time and might give you an edge, but most of the time, you get so much more
value, and in a fraction of the time, by weaving together concepts and experiences
from someone that's better than you, or that has _more experience_

== Adapting fast - Learning from experienced people

- 30 years of wrong experience
	- Or the same experience over and over again

You need to balance out the new things, and how they can or cannot help you,
and **connect**. Read from someone, message them.

- People need to understand the bigger picture
	- That's why roadmaps are popular

== General Learning + Specialization

Specialization can be broad: Backend Development.

So you should cover a large base of things. And on top of that foundation you
can build a **skyscraper**.

Specialization => Means becoming very good at a specific number of things.

You are not too good at something to do something special.

**Courses:** End to end. Efficiently building, and with a weaved together goal.

A good way to learn "similar concepts" can be captured in this example:

You learn loops in Python. And then you can learn loops in Typescript.

However, this shouldn't be the same journey as Python, you can encapsulate the
translation of the syntax by asking a simple question:

_How are loops different from Python to TS?_

When you start building these connections amongst concepts and realms of knowledge,
you inevitably enhance, and strengthen your memory's access to both of the realms
of knowledge and your skill goes up even further, it's higher value than just
thinking of them as their own silo.

By understanding the key concepts and then picking out the differences between
programming languages and the like will allow you to cover more and faster.

- Learning is actually painful. So if you are learning and this is **hard**. That's
a good thing, unless it's too difficult.
	- If you walk away without concrete things out the experience. Something is bad.
		- You have to contrast info, take notes, and deep learning in general, has
		to hurt just enough. With that, things can translate.

[IMPORTANT]
====
Don't spend time learning the same thing but under a different environment. You
won't progress that way.
====

**Knowledge Vault**

This has to be reference for you and the AI.

- I've been doing this, a markdown file folder.

- Write skills within AI
	- Research
	- Code-translations
	- Alternatives => Really valuable
		- Conquering the topic from different angles. This is one of the biggest
		challenges in modern learning which is silos concepts, and not understanding
		how to translate that into the real world

Skill: A prompt you give to an LLM, but you can reuse it all the time.

**Stop thinking of AI as the enemy to learning, think of it as an enhancement to it**

A great example of AI:

- When you are reading docs, and there's some fact or note stated, whereas before
you could've just trusted whatever it said (without a really clear understanding),
you can ask AI to generate an example of what the docs say. And then you yourself
can run it, and the concept can then get DEEPER inside of you.
	- Where would you run different approaches, scenarios and real world examples.
	Let's not focus on one isolation solution, use AI to get multiple approaches,
	multiple things

- Get more randomness to get more ideas, so fire off multiple agents and get multiple
approaches to things.

=== Building your own software

- Real provable experience
	- A little less true with AI. However, with Agents you are still supervising them
		- Product mindset
			- What features do we actually want
			- What do we need?
			- How much do things cost?
			- We learn how code can be then used for practical applications
	- Work with real data
		- Work with customers
	- Security
	- You will be challenged and hopefully motivated

You can short-circuit a lot of skills' acquisition time, BY BUILDING THINGS YOURSELF.

- Live migrations?
	- Protect data in production
		- Whilst morph the data model
		- How do you not corrupt data?
			- How to push updates without affecting users

[IMPORTANT]
====
Resourcefulness => Biggest skills. Somehow, make it work.

Search for help in AI, people, alone. Etc.
====

=== Career moves

Career + Life strategy

- Stop being tied up in a role, title, company
