= Notes

Notes based on https://www.youtube.com/watch?v=HdHlfiOAJyE&list=PLmSGbCS0swswHGaytV6QQkyA9tGR7i0tV[MIT's Finance Theory I]

== Motivation

Try to find individuals or a group of individuals that represent the subject or
thing you want to study or get into

**What is Finance**

Mathematics + $$$ = Finance

Systematic study of financial transactions and money.

**Inaccurate and inappropriate to say I'm not that good in math**

- Pedestrian and obvious maths vs arithmetics still is **MATHS**
	- You should not have background in upper level maths, computations or whatever

There's a lot of mathematics that can be applied to get money and find a job in
finance

James Simons:

Math Professor => **Was**. A quite well known as a _math professor_. Diferential
geometer.

Hedge Fund => This is probably the most succesful hedge fund firm, with a track
record that has beaten all other hedge funds. Quantitative investment strategies.

They use SUPER advanced maths, and kept top secretly, and are successful.

Warren Buffett:

Richest man on Earth. (In 2008) - Omaha, Nebraska. Small office, and works doing
"simple", or well, not "fancy" stuff. He does accounting. And clearly with some
skills that have maths, but not the ones that James Simons uses.

Jack Welch:

His PhD is engineering. General Electric. Became CEO, and at that time the revenues
of General Electric is 26$ billion a year.

An engineer, yet that made good decisions about investments, good decisions about
costs, he was able to understand the language of finance despite the fact that
he used none of his PhD skills in his job.

- **Engineer by training, not manager**

[IMPORTANT]
====
All of these succesful individuals understand deeply, fundamentally, innately.
The language **of finance**
====

== Dramatis Persona

A Flow Model of the Economy

Households => Capital Markets => Nonfinancial Corporations
		FINANCIAL INTERMEDIARIES

Not focusing:
- Labor Market
- Product Market

[NOTE]
====
We are focusing only on these four main components
====

Financial Analysis => Applies to all the components.

== Fundamental Challenges of Finance

There are **two aspects**.

- The valuation of assets
	- This is gonna be more challenging
- The Management of Assets
	- Which of two possibilities is valuable
		- You take the more valuable one (that's it)

**Valuing and Management**

Any kind of business decision is based around these two components.

**Valuation** is a challenge because, you don't really know what is defined as
"valuable". Water? Diamonds?

Objectives + Valuations => Decisions

Pick the decision that's more valuable for achieving the objectives we want.

**Price Discovery mechanism**

- Knowing nothing
	- Without ANY information
		- We established VALUE

**However, there IS information**. There are lots of constraints, lots of preconceptions
on how you can assign value.

- Whether this was good or bad value. THAT'S DEBATABLE

- Price Discovery Process
	- Lack of transparency, devalued something

How the Market comes up with **THE VALUE**? => That's hard, it's a challenge.

_Empiric Knowledge:_ If you are trying to get rid of an asset, site-unseen, and
you sell it, for a 66% discount, that's actually. Not that bad.

== Framework of Financial Analysis

Accounting is the lexicon of Finance. It's the beginning of measuring financial
movements.

- You need to learn accounting to get the concepts

**Stock** => Stock of assets. The level of assets.
**Flow** => Rate of change, of assets.

**Think about things in a more intuitive manner, do not get lost in academic
speech**

- Think of a bucket with a hose getting filled with water.
	- The **stock** is the level of the water
	- THe **flow** is the rate at which the water is coming out

**Okay, some people find buckets with water intuitive, and others find Derivatives
intuitive**

The counterparts of accounting are:

- Balance Sheet = Measures the stock of wealth. What your assets are, and your
claims/liabilities are on those assets
- Income Statement = The flow of wealth that comes into a company, this says how
much the company is making in a measure of time vs its losses

**Framework of corporations**

**_Balance Sheet_**

Assets | Liabilities

Cash     Equity
Capital  Debt
Intangibles

This tells you half the story of what's going on, you still wouldn't be able to
properly assess how a company is doing by looking at the balance sheet.

**_Income Statement_**

This gives the other half, you would typically want to see:

Sources of Funds = Uses of Funds

ΔS + ΔB + NI = I + D + T + C

These are the tools at their core that the great succesful managers use. It's
a set of ideas that are **extremely powerful**. But that you need to understand
so well, that you make use of them.

**Corporate Financial Decisions**

So whenever you are dealing with decisions to make, you will always fall into
5 types of decisions:

1. Cash raised from investors (selling financial assets)
2. Cash invested in real assets (tangible and intangible)
3. Cash generated by operations
4. Cash reinvested
5. Cash returned to investors (debt payments, dividends, etc)

[IMPORTANT]
====
Cash should be considered the **lifeblood** of a company. The finance guy (Financial
Manager), is in charge of overseeing and leveraging the cash that comes in and
out of the company. If you follow the cash, you will find the corporations
key components
====

A variety of carreer and paths take care of different financial decisions:

**Management**

- Real Investment: 2, 3
- Financing: 1, 4
- Payout: 5
- Risk management: 1, 5
- Objective: create and maximize shareholder value.  Do well by the owners

Too theoretical. So let's make it more personal.

Take these ideas and apply them to yourself. See the cash flows that are flowing
through your life right now.

**Personal Financial Decisions**

1. Cash raised from financial institutions (selling financial assets)
	- Student Loans
	- Borrowing
	- Home Equity
2. Cash invested in real assets (tangible and intangible)
	- What's the biggest asset you would be investing at uni or school?
		- Human Capital - Yourself through Education
3. Cash generated by labor supply
	- When you get a job you get cash
4. Cash consumed and reinvested in real assets
	- Beer, Pretzels = Consume
	- Yourself, home, children = Reinvested
5. Cash invested in financial assets
	- 401K Plans
	- Social Security
	- You are invested in these

The **Household** sits between real economic activities, i.e., **your job** and
assets and liabilities. Which are all the financial decisions that you take.

So the cash flow process that works for corporations, it works for you too.

**Management**

- Real Investment: 2, 3
- Consumption/financing: 1, 4
- Saving/investment: 5
- Risk management: 1, 5
- Objective: Maximize lifetime "happiness" or expected utility

With that objective in mind, you would manage your real and financial assets to
maximize the likelihood of achieving those objectives.

**Take the idea, course, PERSONALLY**

And ask yourself:

- How can I use that in my life? How can I use this knowledge in my own personal
activities?
	- If you learn to do that instinctively, you can then take any idea, apply it
	to a management context in your carreer

== Importance of Time and Risk

1. Time
	- Cashflows now are different from cashflows later
	- Time flows in only one direction (as far as we know)
	- How should we model temporal differences?
2. Risk
	- Under perfect certainty, finance theory is complete
	- Risk creates significant challenges
	- How should we model the unknown?

Without these two elements, Finance is **complete**, there's no more research
to be done, no more analysis. Everyone would be able to intuit decisions that
you are forced to make.

**To Address these two issues:**

- Use historical data
- Use mathematics (probability and statistics)
- Challenges can easily overwhelm current mathematical abilities

Without time and risk, financial decisions would be somewhat binary, supply and
demand, that would be it. The only reason finance is interesting, the only challenges
that are here, is because of time and risk

There's a deep philosophical connection between finance and physics.

You don't have to be a physicist to know and understand financial concepts. A
lot of people that work in finance understand the principles intuitively.

- A dollar today is not a dollar next year
- A dollar today with risk is not a dollar today with a little bit of risk

**Risk:** To understand you need a set of tools first.

First Weeks = Focus only on time. Once we have machinery necessary to capture
RISK.

_When we put these two together, we get modern finance_

== Six Principles of Finance

You might not get these principles today, now. But maybe one day, they will click.
So don't forget about them

P1: There Is No Such Thing As A Free Lunch = Approximations to a much more complex
truth.
P2: Other Things Equal, Individuals:
	- Prefer more money to less (non-satiation)
	- Prefer money now to later (impatience)
	- Prefer to avoid risk (risk aversion)
This is generally true.
P3: All Agents Act To Further Their Own Self-Interest = Economists re-define
preferences to even argue that Mother Theresa is incredibly selfish. Finance makes
economics practical.
P4: Financial Market Prices Shift to Equalize Supply and Demand
P5: Financial Markets are Highly Adaptive and Competitive
P6: Risk-Sharing and Frictions Are Central to Financial Innovation

_Note:_ The last lecture will be more "honest", as it will look back at the framework
the teacher gives you and points out the holes, it asks of the student to suspend
their desbelief, and take these **approximations** as they are, a good way to
grasp concepts and get into the knowledge. But the teacher in the end is going to
provide guidance as to what other advanced courses you can take to fill-in the gaps
of the framework exposed here. (The last 3 principles will be used to show the
gaps)

== Course Overview

A. Introduction
	- Fundamental challenges of finance
	- A framework for financial analysis
	- Six principles of finance
	- Cashflows and the time-value of money
B. Valuation
	- Discounting and the mathematics of net present value
	- Pricing stocks, bonds, futures, forwards, and options
C. Risk
	- Measuring risk
	- Managing risk (portfolio theory)
	- Incorporating risk into valuation methods
D. Coporate Finance
	- Capital budgeting and project finance (applying things practically)

**Final Lecture: Market Efficiency (putting it all together)**

- Do financial markets always work well in discovering prices?
- What about behavioral biases and human psychology?
- How should finance theory be used in practice?

== How to Get the Most Our of this Course

There's a set problem sets that the teachers prepared for the students. That
you won't be able to finish in the whole semester, but are there, are optional,
but are highly recommended.

The way to get finance, is to **do finance**.

Teaching = Is not that you force-feed material. You need to want to learn the
material, you have to be an active participant, you need to **PULL THE KNOWLEDGE**
out the teacher and material and make it your own.

Finance is not an spectator sport, you have to do it, confront yourself with problems,
think about how to apply the principles you learn, and solve the problems.

**Your job is to do the analysis**

Financial Analysis => Alien to the typical human thinking. It takes time to get
it, to sink-in.

_Note:_ It's interesting that verbatim, from the problem sets the test problems
will come. So if you spend a lot of time grinding, you can ace the course. This
is done with the hope that people are not as scared, and dive into the subject
for the knowledge and leave the other unpreferred indifferents somewhere else in
their mind.

**Theory vs. Practice**

- Most of this course will be devoted to theory
- What about practice?
- The origins of theory is common elements deduced from practice!

**Some Helpful Hints**

- Do readings ahead of time (skim textbook chapters in advance)
- Take copious notes during lectures (lecture notes are NOT complete)
- Review the lectures afterwards with your study group
- Work on assignments in groups and alone
- "Finance is not a spectator sport"
- Ask Ask Ask Questions!

**Finance Is One of The Most Difficult Subjects You Will Ever Love!**

GET ENGAGED, THAT'S THE ONLY WAY YOU WILL BE ABLE TO SOAK THE KNOWLEDGE IN, BROTHER

== Books:

Principles of Corporate Finance - Brealey, Richard, Myers

Can't cover the textbook. It's too big, some readings.

Chapters 1 - 2 => Responsible for it are students

