= Introduction

== Why ASP.NET Core developers will love Aspire?

Notes taken from a [youtube video](https://www.youtube.com/watch?v=aHqw6mPpJSc).

Some stats:

Know what Aspire is? - 76%
Believe Aspire is relevant to their current projects? 46%

_One of the goals of the .NET Aspire team is: **_We want for EVERY .NET developer
to think of a Aspire as a tool they could use_**_.

Think Aspire is mature enough for production use? 22%

May 2024 => Built for GA (General Availability)

- Aspire deployment => Least Mature of the features of Aspire.

**Please do not change your deployment right now for Aspire, DON'T TOUCH IT**

A Dev Tool => You can use on your team, you can share, and do cool stuff with it,
YES PLEASE. It's being USED in production.

- It doesn't blow up your apps, the idea is to add an extra layer of support, and
fix.

**.NET Aspire is currently the most fast growing of the .NET enviroment**. The
platform is moving quickly, whilst keeping the retro-compatibility.

Think Aspire is easy to add to their projects? 22%

- If you give it your best shot. IT CAN BE SO EASY

Use Aspire regularly? 21%

A couple of millions

Are likely to use Aspire in the next 6 months? 39%

=== The Investment

.NET Aspire is one of the largest investments that the .NET team has made in a
really long time.

- Build, test, and deploy apps seamlessly from code to cloud

- Streamlined Inner-Loop
- Developer Dashboard
- Integrations
- Deployment

**Add to Any App. Ready for Any Cloud.** `dot.net/aspire`

- "... it's not for container developers, for Azure developers, there's a lot of
value and gains that you can take advantage of from the toolkit"
	- Again, **Every single developer of ASP.NET Core**

- You don't have to use the `deployment model`, but you can still take pieces of it
and gain something out of it.

**WHAT IS .NET ASPIRE**

- It's a bundle of tools, templates and packages for MODERN applications. It's like
**glue**, something you build on top of, and turn into whatever you want. But
you are **NOT STUCK WITH IT**. It connects things you already have.

- **Everything is glued together through the central AppHost project. It's simple
C# code**
	- Declaratively in C# you say: I have this project that's a Web API, this is
	a Frontend, there's a database that I will run locally with docker/podman/rancher,
	and all of these things need to talk to each other.
		- Because it's C#, you have IntelliSense and type safety
- People that are already in Docker Compose might argue that they already have
all of that setup
	- But what if you could tab - complete in Docker Compose, or if you get a
	squiggly line telling you that you can't do that, or you couldn't really debug
	your docker compose

- Example use case:
	- We install extensions, for example, Redis, and that allows you to declare
	with C# that you will spin up a Redis instance, and through an API we expose
	the internal Redis configurations so that you set it up as you see fit, and the
	application itself takes care of spinning up a container for it and glue it
	together with all the other components.

It tries to bridge the gap/trivialize setup tasks that are a bit annoying everytime:

- Setup your logging
- Setup Https correctly

There's an opinion, recommendation on how all these things should be setup, and that
is by default already solved/figured out. Exposed to you to start consuming it,
with the option to change it as you see fit.

`ServiceDefaults` => Real Template => It wires up directly all services to start
adhering to Open Telemetry, (to avoid teams incurring in tech debt, Aspire does all
of that for you). There's resilience already built in, so that apps retry requests
if they fail to hit a container. **This feels like boiler-plate**, and that is
given directly to us. (You can comment things you don't like).

All of the things that Aspire uses are currently existing features of the language/
framework probably for a long time. But many people don't know about them or find
them too obtuse to work with. So an Aspire solution, will sort of give you
code samples of how things should be used or can be used. Things that the .NET
team believes should be in your applications, not the framework, yet go that
extra mile to show you a guideline. **Every ASP.NET Core could benefit from this**,
these are defaults for existing .NET projects. (That doesn't tie you to Azure)

**Please don't touch deployment**. That's a growing fear. But the idea is to not
mess up with that. What the team sees in the AppHost.cs file, is a blueprint, that
you can run some tools against to generate something usable for you on your deployment
processes:

- JSON file
- Bicep Template
- Docker-compose
- Something else that is usable on CI/CD pipelines to then generate artifacts

Everything is opt-in, NOTHING is forced. However, many successful use cases see
how the deployment process is simplified through the usage of aspire and its
deployment features.

=== Dashboard

It's probably the biggest piece of the tool that gives it its purpose and value.
When you run an Aspire solution you see everything that the app is running, ports,
logs, you don't have to click through 100 console windows, and you see all the
data flowing between them.

All the open telemetry data streams into the user interface, and it even has
some integrations with AI to analyze and understand the data.

"Modeling your system to enable anything and everything" - Onboarding, installation,
dev cycle, testing, autodocumentation of the real architecture.

- I have an IIS cluster, can I still use Aspire? - YES

[IMPORTANT]
====
Your AppHost.cs class, is NOT A DEPLOYABLE ASSET. The description of the whole
architecture/app. You don't put in a server, a service. It's a manifest with types
and debugging options.
====

However: **there's service discovery baked into the mix**, and this lets Aspire handle
the ports, and communication amongst components. (But you can turn that off, or
just change the name of services in the build/deployment scripts so that it integrates
seamlessly). You don't have to change your deployment pipeline/process at all
whilst still getting the benefits of the development experience full time.

MsBuild => But better. With C# code, not XML.

- Distributed tracing also a big added value.

**The deployment sub-domain is completely optional, and you can choose to adhere
to it or not. Although it's recommended if you want to simplify things with it**

- Happy path deployments to Azure (because this is .NET/Microsoft)

=== How to get started

[NOTE]
====
NO VENDOR LOCK. YOU CAN USE DOCKER, PODMAN, RANCHER. Aspire integrates with any
of these.
====

By default, everything uses OpenTelemtry. So you get structured logging and
structured traces.

**It's a good F5**. Just use the AppHost.cs

````
We want an experience that can literally be: Bob walks into a project, clones it,
and runs it. No issues.
````

- There's even integrations with Add Python, Add Java. Literally just running
executables, nothing fancy. So you can declare your architecture in a polyglot
environment.
	- AppHost.cs => Magical clone and run enabler

**The extension methods:**

- It doesn't do anything more than codify/abstract how most tutorials or most
people that know a certain service/technology bootstrap it with .NET. So the
extension methods in Aspire simply take those opinions/conventions and expose
all of that through an extension method.
	- **Codifying opinions**

**We don't have in built-in support for IIS debugging** => Most people use docker
now. IIS is somehow hooked in for local development, it is possible. (You won't
get the features of aspire with it though)

Through `ServiceDefaults.cs` all projects you create, will have the same behavior,
the same configuration, everything turned on. Repeatable, interchangable!

**All opt-in, IF YOU DON'T WANT TO, DON'T**

=== Service Discovery

Port conflicts are a big issue. And clone - and run gets threatened by them.

**There's no real service discovery, it's just environment variables**

On your AppHost.cs => You give a name to the service, a magic string. And on
your client, you can reference that same name, an internal proxy resolves what
container/service needs to respond to that.

- Dashboard => It's all a Blazor Server App

**What if there are existing apps**

Not crazy heavy-lift.

`Launch profiles` => And you set `if (IsDevelopment())`, `if (IsMobile())`

- `appsettings.json` is the `.env` version in .NET
	- User Secrets => Has support built in, but ENV VARIABLES are still usable

- Central package management = A bit iffy. But it works.

Copilot? MS Docs MCP. Copilot instructions can also help. But raw copilot, is still
developing.

- Even in a monolith => Still use Aspire, because you get the dashboard for free,
and best codified practices.

== What Is .NET Aspire? The Insane Future of .NET!

Notes taken from: https://www.youtube.com/watch?v=DORZA_S7f9w

**Project TIE:** Superset over TIE, without deployment stuff.

- We tend to sometimes develop architectures of small components, or components
in general that have to intercommunicate amongst themselves. And Aspire is trying
to bridge the gap, to stop making this configuration/wiring a pain point. It wants
to streamline it. Everything should be really easy to implement.

=== DEMO

You have a web app, and then a Web API. When you have services coming together in
one environment. **You can nail everything down as things change**. But as the
app evolves, then things get out of sync easily, and the orchestration falls
apart.

Aspire is trying to solve that issue, by changing how things are coming together
and are wired.

- `dotnet install workload aspire`
- `dotnet new aspire`

**You need to install Aspire SDK to start working with Aspire**

- ServiceDefaults => That you can change how you see fit.

The Aspire project is an `Sdk` project, with a small flag to mark it as `Aspire`.

VS Tooling can help you implement Aspire and configure everything by default
for you. _Literally a right-click away_.

- You should right click all the projects you want to wire through Aspire to then
let the IDE do all the heavy lifting.

````
The VS tooling just adds an extra support. Rider, and other IDEs should still
work seamlessly.
````

If you setup the aspire project in a way such as:

[source, csharp]
----
var builder = DistributedApplication.CreateBuilder(args);

var api = builder.AddProject<Projects.WeatherApp_Api>("weatherapi"); <.>

builder.AddProject<Projects.WeatherApp_Web>("frontend")
	.WithReference(api);

builder.Build().Run();
----
<.> Based on the name that you add under a resource in the `AppHost` project,
you can then reference from other components this identifier, that way you stop
hardcoding ports and hosts, and just use identifiers instead. (Aspire under the hood
takes care of proxying and wiring things seamlessly).

**And again => This becomes a Super F5**

- You can see all the environment variables with a click. (Many are Open Telemetry
ones)
- You can see logs

You get out the box metrics, out the box logs, traces. Everything "just werks"
because it's cleverly set up with standards.

- Even if you want to add `Redis` you can also add things with extension methods
such as `OutputCache`.

[NOTE]
====
Apparently you can cache web pages themselves in Redis. WHAT?? A literal blazor
component can be put into cache. (With `[OutputCache]`)
====

**Redis is a standard for distributed applications hence Aspire comes with it
pre-installed**

And how can you prove fast-easily that you are hitting the cache? By simply
going to the `Traces` that are in the dashboard, we should be able to see how
a request hits the API, and even talks to Redis, and subsequent requests are not
by any means doing these operations.

- Everything "just werks" because the _"aspire components"_ are already instrumented,
and feed traces, logs automatically without you having to do much.
	- You can also see how the **Redis cache gets hit**

**HOW DO YOU DEPLOY?**

- Microsoft chose to not do it.
	- Deployment is tricky because everyone does it differently
	- dotnet run --publisher manifest --output-path manifest.json
		- A high level abstraction of how the whole environment comes together

== .NET Aspire if Finally Awesome in .NET 9

- `dotnet workload uninstall aspire`, `dotnet new install Aspire.ProjectTemplates`

**Don't need to install the workload separately** it comes `pre-packaged`.

- Aspire got start/stop buttons
- Dashboard is also mobile (why?)
- You can now wait for a resource to be enabled, to then start acting, attempt
to start => `.WaitFor(maindb)`, `.WaitFor(rabbitmq)`
- Healthcheck integration was also done-in
- The idea is to wait for a dependency, and for it to report that it's healthy
- You can then extend the healthcheck endpoints with an extension methods:
`.WithHttpHealthCheck("/health")`
- You can now have persistent containers:
	- Everytime you run the API, Aspire can kill all containers and delete them.
	Or not, so that the start-up is faster, and you can also focus more on
	development efforts (state can be kept)
		- If you see a `pin` on a component in the dashboard, that means that this
		is a persistent container
		- Simplifies debugging, one execution to another, etc.
- All the components are now registered under ONE network

[NOTE]
====
You can literally start Redis, WITH Redis Insight as a web client to manage it.
====

[IMPORTANT]
====
Azure Function support
====

**.NET Aspire** has a different support model. Different release cycle. They want
to move fast, but no LTS, STS support. If a new version drops, the old one is
literally scrapped.

== .NET Aspire Tutorial For Beginners 

Notes taken from https://www.youtube.com/watch?v=41PD08tSH4E

- dotnet clone
- aspire run
- Access a URL
- Hit an endpoint

The pitch:

**Clone > F5 (run) > Ready!

.NET Aspire is a development stack that handles infrastructure setup to clone
and start building from day one.

The tool is at a stage that should give: Enhanced development experience > Deployment.

=== What is .NET Aspire

It's a set of Tools, Templates, Packages to build: `Observable`, `Prod-ready`,
`Distributed apps`.

- Simplified Dev Experience
	- Booting a whole application infrastructure right after a clone
- It has dozens of pre-built building blocks for popular backing services that
seamlessly connect to the app you are building, with no extra config
- Aspire lets you define your infra entirely on C# making builds predictable,
easy to reproduce and easy to put from dev all to the way to production
- It includes a real-time dashboard to monitor the whole infrastructure in order
to detect slowness, dependency failures in dev before this hits prod

**Production-ready**

- An app with a scalable database (Postgresql)
- A caching service (to improve response times and reduce database load)
- Resiliency: Smart retry-policies to handle inevitable service failures gracefully
- Health Checks: The application can self-heal through these alerts that are raised
when dependencies or apps themselves have issues
- Observability: Having enough logs, traces, to troubleshoot the application effectively

The app we are going to use as a model for Aspire integration is a games' portal.

- Sqlite database => Pretty easy to start straight away.
	- For production, you need a scalable database. So you would have to move away
	from sqlite to PostgreSQL
	- We need to get Postgres installed in our box, and the traditional approach
	would rely on actually installing the service. But ideally we should aim
	at using containers, they make life easier.

`connectionstrings.com` => Great cheatsheet for connecting to many different
backing services (since they all have different connection strings)

`Npgsql` => official package to connect to Postgres in .NET. (Need EntityFramework)

- You can use .NET Aspire to integrate Postgres into the app, in a more **streamlined
way**

`AppHost` => Orchestrator of the whole solution of the application.

The whole `AppHost.cs` file is referred as `the Application Model`. In here
yes you will define the .NET components for the application, **ON TOP** of external
dependencies.

- Hosting Integration: Nuget packages that we can consume and he will take care of
provision the docker container for the respective backing service
	- The available integrations are many, Postgres is one of them
		- There's client integration and server integration. We are going to focus
		in **SERVER**

`builder.AddPostgres("postgres");` => With a one-liner you can literally tell Aspire
that the application model should have a postgres backing service, and it will
spin it up immediately.

- `aspire run` => And this should show the dev certificate trust stuff

If you run the aspire solution, and go to the dashboard you should be able to see
the details of a database such as postgres and see its connection string if
you ever need access to it. Environment variables are also another things that
you can access pretty easily. A bunch of smart defaults are already baked-in so
that you focus on building the application.

- By default, it assigns a random port to a database resource, but if we don't
like it. You can literally "hard code" the port, that should always be one specific
port. You can also customize a specific image, a specific image tag.

And you can then start building child resources of resources, the database use case
is great to show case that, since a database "service" will hold inside of it many
`databases`. So you can literally add `AddDatabase("GameStore")` and on the dashboard
you will see it listed under the parent `database` resource.

Thanks to how we are declaring the Application Model through the extension services,
all the services are configured and spun up seamlessly, everything gets wired in
the background for you to readily just start using and developing. Even path binding
is already understood.

=== App Host and the application model

The Application Model is a blueprint that defines all the application resources
that are used. E.g.,:

- PostgreSQL Resource
- PostgreSQL DB Resource

AppHost.cs is an orchestration layer, but that doesn't do it on its own, it leverages
the `DCP (Developer Control Plane)`, which delegates to a container runtime such
as Docker the spinning up of specific containers. And lastly the DCP will launch
the Aspire Dashboard.

=== Client Integrations

So Aspire even has its own set of Client extension integrations, so that under
the understanding that the underlying gel is actually Aspire, it will also integrate
seamlessly with all the information and baselines put in charge by a database resource
modeled by hosting integrations. Adds resilience, health checks and telemetry.

E.g., `dotnet add package Aspire.Npgsql.EntityFrameworkCore.Pgsql`

We can then use an extension method to then simply declare the name of the database,
and everything under the hood will take care of hooking up our service to the
orchestated resource. It's really "magical", the ConnectionString will end up
allocated dynamically from now on.

- And to then get the database with the right structure and even seeded data,
you should create migrations. (Since this example is of a database that used to
integrate with Sqlite that also was integrated through EF Core and had migrations,
you have to delete those migrations and run the EF core tool again so that we now
generate migrations that should adhere to Postgres)

=== Resiliency

Sometimes you will have to deal with Network hiccups, planned maintenance,
throttling => When a database is temporarily brought offline for a bit. (This is
really common on the cloud apparently, but yeah even in some environments that
are interconnected across countries and stuffs)

In this instance, you don't want for your application to fail immediately, you
might want to wait a bit, and retry the query/connection. If that fails again,
you wait a _a bit more_, and you try again. You can then **increase the delay**,
until the issue resolves, and your flow continues. Resiliency is the ability of
your system to react to failure and still remain functional, it goes beyond just
retries, it can extend to recover from failures, and return to health.

**Because we can use the Dashboard to start/stop components at will, we can easily
simulate a resource being dead**. So we can stop a database, and then try to use
a Web API service.

- We will immediately see how in our client, we don't see an immediate error,
and if we check the logs in the API, we will see how the application keeps retrying
the database connection automatically. The client integration for Postgres is
wired up immediately for resiliency. You get that AUTOMATICALLY if you use the
client extensions. **So that's another big value**
	- You can then turn on the database, and you can then see how the application
	responds to the client

=== Health Checks

How can you tell if your backend application is alive?

ASP.NET Core API => Container in the Cloud. Mobile devices and desktop apps could
be talking to it. If the application starts getting hit with too many requests,
the container might collapse. Health checks can become crucial for this possible
risk.

We would have an orchestrator, and he would be pulling all of the containers under
his care, the moment he stops getting responses on health checks from a specific
container, then the orchestrator can spin up a new container to take its place so
that users are served, whilst the orchestrator gets the original container back
up again.

[NOTE]
====
An API can also extend the readiness check so that all the backing services (dependencies),
also can become part of the healthcheck. That way if a database (e.g.) is dead,
the API will respond with an error as well.
====

An easy way to check the issue is to stop the database, and see how the API marks
as healthy still.
	- But because we know the database is down, we know the API's service will be
	faulty. We should have a way to detect this error easily, which brings us to
	healthchecks.

**ServiceDefaults:** This default list of templates that we can wire to our projects
that are under a specific project should be used as much as possible so that all
the services keep a consistent behavior and configuration.

`AddDefaultHealthChecks()` => This is a small extension method that adds the
healthchecks middleware, it has an `alive` tag, and it also wires the healthcheck
to the service itself. Bear something in mind, all the client extensions for
external dependencies **WILL ALSO INTEGRATE SEAMLESSLY INTO THE HEALTHCHECK ENGINE
SO THAT THE BACKING SERVICES BECOME PART OF THE HEALTHCHECK AS WELL**

Another part of the healthchecks infrastructure is the `MapDefaultEndpoints()`
extension that takes care specifically on development environments to expose the
health check endpoints. It maps two endpoints, one for readiness (`/health`) and
another for liveness (`/live`).

Invoke `AddServiceDefaults()` and `MapDefaultEndpoints()`, so that all the
smart defaults are integrated seamlessly.

We should let the application model understand **there's a health check integration
on a service**. And that is done with a simple extension: `.WithHttpHealthCheck("/health")`.
That way .NET Aspire integrates with the service's health check endpoints.

And we can chain another call so that we wait until the database is ready with:
`.WaitFor(database)`. This will wait for the database to start, and it will also
wait for the healthchecks to pass.

- This is so powerful, because the integrations with external dependencies can
be monitored easily, and we can find issues way faster and easier than without
all of this architecture and wiring. That way the orchestrator can report and
take action if configured to do so.

- Healthchecks are not that critical locally, but as soon as you deploy, .NET
Aspire helps you with smart defaults, the dashboard also helps with testing and
scenario mocking.

=== Observability

- App is deployed, clients start complaining
	- What happened?
	- How is the app performing?
	- Where is the bottleneck?
	- If you have a blackbox of an application, you will be blind, and won't know
	exactly where to start looking for the problem

**You should aim at having a transparent application**. How can you make your
application transparent?

- You should feed metrics into it, so that you can see how the application is
performing
- Logs that can tell you exactly what went wrong
- Traces that help you find bottlenecks across the system, and also troubleshoot
faulty dependencies

**These three elements are the pillars of Observability**. Observability is the
ability to measure and understand the internal state of a system based solely
on its external outputs.

**Best way to enable all the observability elements is through: `OpenTelemetry`**.
This is an observability framework and toolkit designed to facilitate the generation,
export and collection of telemetry data.

It facilitates the instrumentation of application data so that we emit signals
(logs, traces, metrics), and it also faciliates the way we output all of that
telemetry into visualization tools, and stores. (E.g., .NET Aspire Dashboard).
All of that is through the Open Telemetry Protocol (OTLP), it helps emitting
info through GRPC and Rest endpoints.

`ServiceDefaults` is pre-wired with OpenTelemetry. What we add in these smart
defaults is `Metrics, Tracing, Logs`. The Metrics can be defaults, or custom
metrics as well. Tracing helps correlating and piecing together data flow across
components.

The Dashboard exposes an endpoint that will collect telemetry data. Any other
telemetry tool or visualization tool can use the telemetry data that's emitted.

Even when integrating with `Redis` you can add the Redis spin up, and also install
the Aspire Redis Client and wire it up to the respective resource name.

[NOTE]
====
When working with the redis Nuget, sometimes it adds too much noise on the logs.
So a good way of stopping that is to add its namespace in the log config value
under `appsettings.json`: `"LogLevel": { "StackExchange.Redis.ConnectionMultiplexer": "Warning" }`
====

Because of the OpenTelemetry integration it's easy to search for specific values
or parameters. We get `Trace`, the TraceIds are used to then reconstruct the entire
story of an HTTP call.

With OpenTelemetry's traces, you can clearly see all the actors involved in a call
and easily identify the bottlenecks.

**Metrics:** We even get metrics that are coming from the client integrations.
Such as `Npgsql`. You can TOTALLY add your own metrics and observability, however
the defaults are really nice.

=== Clone + F5

The biggest advantage you get from Aspire is the amazing on-boarding experience.
It's literally a Clone + F5. The configuration can "just work" without extra
overhead.

What are other integrations that .NET Aspire provides:

It can interface with Identity Providers:

- Keycloak
- Entra ID

It can integrate easily with Azure Services:

- PostgreSQL
- Key Vault
- Blob Storage

It can work with multiple frontend stacks:

- React
- Blazor

It can deploy everything to the cloud with:

- Container Apps
- Biceps

== Intro to Aspire 9.5 - Get Started Quickly with This Essential Tool

Notes takes from https://www.youtube.com/watch?v=x2KAfsFydIo

[IMPORTANT]
====
Take INFORMED DECISIONS. Based on facts and knowledge.
====

_Apparently you can just install the Aspire Templates and then everything should
work...?_ But yeah, the CLI could be the best thing to get.

What is .NET Aspire? Why is it so valuable?

AppHost => This is a project that becomes a launching point for the whole application.
LOCALLY.

[IMPORTANT]
====
This is all about local development. Making our local development, much much easier,
making developers much more faster and efficient.
====

`ServiceDefaults` => Adds a lot of extensions that many developers might not be
doing.

_I don't understand any of the extensions?_ Well, great, it's time to learn about
them.

**What's the point?**

Imagine you don't have aspire. You have a web project, web api project. You have
a hosting service. You have redis also hosted somewhere else. (This is prod/deploy)

Locally, we do not have access to those services. Containers, through a container
runtime, we can get all those dependencies up and running and ready to be used
by our application.

You need to setup things manually to get everything working, api depending on web.

- What if we didn't have to worry about spinning containers even?
	- What if it all just worked?
	- When we are wiring our services, we reference identifiers, no hard-coded
	urls or ports. **Service discovery handles everything for us**
- EVERYTHING IS DONE FOR US THROUGH THE ASPIRE AS THE HIGH LEVEL APPLICATION MODEL/
BLUEPRINT.

Using methods such as: `WithReference()` and `WaitFor()` helps us wire up things
through service discovery. And once we launch the project through the Aspire launch
profile/project. We will run into a Dashboard. The Aspire Dashboard.

_Small tip:_ If something is wrong, maybe your container runtime is not running,
or some other external problem, the Aspire Dashboard gives you a lot of alerts
and understandable messages to help you troubleshoot.

- When you are working with systems and resources that it's not just one monolith,
the Dashboard allows you to visualize the interactions and connections. Also to
manage, to troubleshoot, to debug.

**Clone + F5 + Ready!**

Whether it's a simple or complex project, you get more information in a graphical
manner, and helps you wrapping your head around the whole app more easily.

- You can see all your logging _LIVE_ at the same time
- There's structured logging OUT THE BOX ready for you to consume
- Tracing => See what's happening in the application and track commands that are
taking place
	- You can see all the information in regards to multiple components and their
	interactions. The whole story, all the interactions, everything gets logged
	into one trace statement. So you get even further information into how your
	application is working, how it's interacting.

**Million Dollar Question:**

How do I deploy then? The dashboard into Azure?

- You don't want to do that
	- Well you kinda want to, at least the dashboard?
- This is all focused on our local development experience, bringing more value to
users and the systems faster and with much more in-depth knowledge
	- The goal in production is not to track so many things
		- Not done this way

- So apparently the "typical scenario" is that in production you get access to
all of this services, setups that are great for debugging and stuffs. But on local
you didn't have access to all of these things, apparently, what? So now Aspire
brings all of that richness into local development.
	- You don't want to test in production, do you?

=== Extending Aspire defaults

Finally found an answer for the recommendation on logs to use parameter names
such as:

````
LogInformation("Counter value is {Counter} and it's {EvenOddResult}", counter, (counter % 2 == 0) ? "even" : "odd")
````

By putting these specific parameter names, when outputting the logs as structured
logs, we gain these fields as searchable/queryable fields.

That way we can filter out logs, we can filter out many things.

When you see errors on the structured logs, if you have launched Aspire with
your IDE and it's integrated with Copilot, you will get access to the copilot
chat to explain errors, or just overall, integrate with everything else. And give
you support. (The idea is that Copilot is aware of both the code, and the running
error, it can give you pointers to what file, and  how to fix the error even)

**Span ID:** The ID that is passed around services. It's so easy to track down how
everything is done, what is going on.

**There's only a couple of things to go through:**

- AppHost project => The project you launch. And you write on its Application Model
all the things you want to spin up.
- You have a `ServiceDefaults` with all codified industry standard setups for
observability, traceability.
- Any project you want to wire with Aspire, needs to reference the AppHost

=== Deployment

Everyone wants Aspire to deploy. There's more and more things moving Aspire towards
the deployment side of things.

**Aspire was meant to be for local development**. So don't feel as though it's
"incomplete", its original intention was local development enhancements.

Aspire is open source.

- Deployment of the dashboard not a wise idea (apparently)
	- Your open telemetry integrations should integrate easily with the whole
	architecture

- Aspire can integrate with React, Python. Not just c# projects
- You get so much information, that you can limit test your changes, you can performance
check
	- It makes lifes easier, faster, better as developers
	- Try to use the latest bits

== Build Better Apps with .NET Aspire - Complete Beginner's Guide & Tutorial 

Notes taken from video: https://www.youtube.com/watch?v=e36NEWqO7GQ

What do applications need to be?

- Observable: Want to see what's inside of the application, see logs of what's
happening, so that we diagnose problems
- Resilient: If things go wrong, or some service goes down we should have a way
to handle that gracefully
- Scalable: As needs are introduced and applications grow, we need to have a clean
getaway solution to scale up or down
- Manageable: Easy to get up, get down, easy to scaffold our architecture and
add more services in

`.NET 8` incorporates more patterns and templates so that all the applications are
more: **Observable, Resilient, Scalable, Maneagable**

However, it's not easy to set all of this. But:

- Complex
- Getting Started is Hard
- Too Many Choices
- Not a clear path

There's so much you can choose from, and not much time to test all of it. How do
we get rid of all of that complexity and choices as developers?

Aspire is the solution to that: A cloud ready stack for building observable,
production ready, distributed applications. (NO MATTER WHAT YOU ARE BUILDING)

- What does that mean? Who should use it?

Aspire grows and scales WITH YOU.

=== Use Cases

You might even prototype, and Aspire can be used at that stage. You grow a bit
that prototype, Aspire still will hold.

Complex architectures and orchestration of services => Aspire will STILL hold up,
if anything it will shine even further.

.NET Aspire => Are building blocks for cloud native development, distributed applications,
ANY application:

- Smart Defaults
- Developer Dashboard
- Orchestration
- Service Discovery
- Integrations
- Deployment

The components are meant to be used to make developers more productive.

=== Adding .NET Aspire to an existing project

- If you want to start multiple projects you need the Multiple Project Startup
and you have to run and get 10 tabs, 10 console windows. Navigating amongst all
of those is a hassle, and you get confused pretty quickly.

_How can this be smoother?_

Add .NET Aspire into the project.

The easiest way to make work of it, is by using Visual Studio and `Right Click >
Add Aspire Orchestrator Support`.

This does a lot in the background:

- Adds an AppHost project
- Adds a ServiceDefaults project
- Sets the Aspire project as the startup project

**If you analyze the ServiceDefaults:** You can see how all of these opinions are
ready to be wired up to any application. One of the great things of the design
choices here is that the OPTL configuration is open to modifications, meaning that
you can pipe into any other exporter/collector you want, not just the aspire
dashboard.

- **The orchestrator needs to reference all other applications**, that way it
generates auto-generated classes to then hook up and orchestrate accordingly.

[NOTE]
====
By default, the resiliency smart defaults will attempt to retry to connect to
a dependency. (E.g., If an API is failing, we try a few more times because it
has `AddStandardResilienceHandler()`)
====

- If we want to deploy the same exact application, we would just update an environment
variable to refer the specific .NET Aspire application setup.

**We get rid of a lot of developer toil**, service discovery with a few lines of
code helps us getting back on track of app development.

[NOTE]
====
There are two parts to the integrations of Aspire: Integrations for the AppHost,
and integrations for the projects that are wired to Aspire. (Even if you deploy
them, these integrations, working with the default open telemetry standard and
all the principles of Aspire, the clients will seamlessly be instrumented with
telemetry data)
====

`RedisCommander` => A Redis inspector client.

You can use [OutputCache] to literally cache ENDPOINT RESPONSES.

[NOTE]
====
The difference between a `healthy` and `alive` endpoint is that healthy will show
healthy only if ALL DEPENDENCIES ARE ALSO HEALTHY. `alive` will show healthy if
the component itself is good. (It won't go and double check dependencies)
====

=== Deployment

This is complicated.

- Every Apps Is Different
- Tons of Choices
- IT & Security Requirements
- Complex

There's no "ONE" solution at the end of the day. But there are nice ways of exposing
an API that we can opt-into and that be seamlessly integrated.

- If you are already deploying your application, you can keep using the same thing.
	- ConnectionString updates, adjust to a Schema that Aspire uses.
	- There's nothing in Aspire that don't get deployed
		- You still deploy your individual components

**But there's an easy way to streamline deployment:**

- AWS CDK
- Azure Dev CLI
- Visual Studio

- You generate a .NET Aspire Manifest => And that can be read and then translated
to different technologies' manifests.
	- Turn things into a definition for Kubernetes
	- Turn it into a definition for Azure

- You can literally use the IDE, to right-click and Publish the "Aspire project"

This is a magical way that abstracts everything from you. But we can analyze and
rebuild what's happening with commands:

````
dotnet run --publisher manifest --output-path aspire-manifest.json
````

This creates a `json` file that will describe everything that the `AppHost` project
holds inside of it. It's a great way to see how everything is brought together,
and how they reference each other in a really clever way.

**Extra key insight:**

If you want for a specific component to not be just working internally (privately
exposed to the architecture), but also the outside you can literally add a small
extension method:

- `.WithExternalHttpEndpoints()`

Manifest => Doesn't really do anything, it's a simple spec and description. The
Azure CLI can read it though, and turn it into something that then is deployed.

However, there's a community tool that can translate it to Kubernetes

`azd` => Azure Developer CLI. `az` => Azure CLI

- `azd init` => Detects an Aspire project and can offer you a possible strategy
to deploying it
- `azd infra synth` => Output files that `azd up` will create on its own, without
actually running them. It literally has different yaml/bicep files for each resource
that is declared in the AppHost
- `azd up` will then start creating and doing everything for you based on the
generated manifests/artifacts

And once you go to Azure you should see the whole **resource group** with all the
components that should be a 1:1 parallel to what you had in local.

[NOTE]
====
When you deploy to Azure, things are dropped as Container Apps, but you also get
the Dashboard for free? And it has ALL THE OPTIONS?? Is this a Azure Cloud only
option? Besterds
====

Dashboard => Is more real-time. If you want more in-depth analysis of the logs and
stuffs. You need to go to other services.

=== Aspire goes Beyond .NET

- You can integrate React, Vue, Angular and pass env variables to them
- You can add Python projects

**Developer Dashboard in my machine**

You can also use the Dashboard **Standalone**. You pipe telemetry into it, that's
it.

`aspiredashboard.com` => Community built info on .NET Aspire

You can spin up a docker container that will have the Aspire dashboard in **Standalone
version**

And then you can integrate whatever application you want, (say a `ConsoleApp`),
and you can see how all the telemetry information will be fed onto it seamlessly.

In short, the way that other technologies integrate with Aspire is by using the
open telemetry framework (there's an npm package for it) and it will allow you
to connect to an OPTL endpoint (that will be our dashboard) and we will start
visualizing these application traces/logs. That way, you can integrate with
ANY APPLICATION that's out there.

== Aspire: Cloud-Native Development Simplified

Notes taken from https://www.youtube.com/watch?v=aXouOsBh4ro

What is Aspire?

- It's a lot of things. So better to talk about it by mentioning the things that
it helps with:
	- Modern applications => Service, container, database, cache, many microservices,
	monolithic but with a bit of modularity.
		- The more cloneable, the more reproducible you want your app to be
- Aspire is a tool for code-first, extensible, observable dev and deploy

**Anatomy of an Aspire App:**

- Aspire AppHost + CLI
- Aspire Integrations
- Aspire Dashboard

`aspire update --self` => We are in Aspire 13.

- There's now a template for React (vite), and FastApi (python)

**There's an Aspire extension in VS Code**

And the extensions with other technologies:

[source, csharp]
----
var frontend = builder.AddViteApp("frontend", "./frontend")
	.WithReference(app)
	.WithNpm(install: true)
	.WaitFor(app);
----

Your c# organizes your javascript, your python. The simplification of things is
done with intent and purpose. We are using c# to describe how the application
should fit together.

````
builder.AddCSharpApp("api.cs");
````

You can debug csharp code on VS Code, and you can even debug PYTHON. You should
be able to run all three languages at once and debug ALL of them.

=== DevTunnels

**Dev localhost URL:** Support for more custom URLs. Don't have to remember ports,
URLs. But an URL.

This is a hosted service, code spaces uses it, visual studio and visual studio
code use that.

`aspire add devtunnel` => We can model a dev tunnel inside my aspire project.

[source, csharp]
----
builder.AddDevTunnel("devtunnel")
	.WithReference(webfrontend)
	.WithAnonymousAccess();
----
Apparently dev tunnels are this interesting tool that helps you expose a localhost
"thing" to anyone through the internet, with a static URL. More info at https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=linux[Docs]

Yeah, Aspire now has devtunnels integration.

_Deployment story has been getting more investment_

- Deployment needs to be more flexible
	- People want to hook things into workflows
	- People want to run mocks

`publish` - `deploy` were too chunky.

`aspire do <>`

You can still do `aspire publish`, `aspire deploy`.

But `aspire do` runs under the hood now.

With these new developments in the deployment story, we can now model not just the
architecture, but the DEPLOYMENT.

That's how we can see that with the patterns:

````
builder.AddAzureContainerAppEnvironment("cae");
builder.AddDockerComposeEnvironment("env");
````

All of these are Nugets, that focus a specific deployment strategy. You target
any deployment strategy.

- New deployment pipeline, but integrated with Aspire.

- aspire.dev => New site

== Modernize Legacy .NET Projects With Aspire

Notes taken from: https://www.youtube.com/watch?v=hEKEBCShBLM

The idea is that Aspire, the dashboard, can show you a lot of information, but
a lot of things have to be put in place.

You can have an application be "integrated" yet not being able to feed really
anything to the dashboard. So the `ServiceDefaults` is this extra codified convention
bundle that gets added to your C# app and then starts integrating with the OpenTelemetry
framework.

**Aspire is an upgrade to the Debug experience (local)**

- The Local Development **Story** in .NET was really weak
	- It was really clunky
		- And we can now check into source control all the right settings, the
		right order. A super F5

An interesting improvement on the default docs approach for Aspire:

[source, csharp]
----
new(builder.Configuration["Api"])
----

That way we avoid magic strings and have them behind configuration values, however
the actual value should also be an ID, not a localhost or specific port. We should
try to integrate with the Service Discovery addresses that are solvable.

Never forget that this is trying to stop you from doing the Multi Project startup,
per machine, per user configuration. But if you put into source control. The
onboarding is streamlined so much.

So Aspire, is designed to be added to existing projects, there can definitely be
more complicated setups, more complicated projects. However, to get things up and
running and improve the local development experience.

Aspire => More than just .NET. It's built in it, but you can integrate with many
other things.

== Highlights of Container support

- The .NET Team has assumed containers to be the **Primary Deployment Model**

Containers became the assumed target for the new .NET features, not an afterthought.

[quote, Conversation about containers]
----
It's now just assumed as the primary deployment model for new features and
scenarios... It's also the way our TechEmpower benchmark tests are run.
----

- CGOATs as the Biggest Cloud Trend

The team explicitly identified containers as the most important trend in cloud
computing, requiring major investment

[quote, The best of Docker – NET5 further embraces container technology]
----
We think containers are the most important cloud trend and are investing
significantly in this area.
----

- Environment Consistency

Containers provide an unmatched guarantee that your application will run identically
from development to production

[quote, Conversation about containers]
----
They provide a greater level of assurance that your build output will work in
your target environment than we have ever had before... All the requirements,
including the old runtime they work with, are encapsulated in that one Docker
artifact.
----

- Security & Supply Chain

Immutable containers that dont' change as they move between environments align
perfectly with modern secure software supply chain standards

[quote, Conversation about containers]
----
[The container image] isn't changed—and shouldn't be changed—as it goes through
the environment promotion process. As image signing becomes more commonplace,
this model will become standard.
----

=== Example Scenarios

- "Lift and Shift" (Legacy Modernization)

**Goal:** Get existing .NET Framework apps (like WebForms or WCF services) into
containers without a full rewrite.

- We can get containerse with a full Windows Environment ensuring compatibility.
- You can dramatically improve the deployment and DevOps processes for and old
app without re-architecting it immediately

- High-Density, Cost-Effective Hosting

**Goal:** Run many small .NET services on a single server to maximize hardware
usage and reduce cloud bills

- The focus on tiny image sizes, fast startup times, and runtime awareness of
resource limits
- A .NET app in a container is lightweight and starts quickly, meaning you can
pack far more of them onto a single VM than a traditional .NET Framework app

- Cloud-Native Development (.NET Aspire)

**Goal:** Make the entire developer experience for building distributed, containerized
apps not just possible, but simple.

- The .NET Aspire tools can even build automatically container images for you
- This automates manual, error-prone work of creating Dockerfiles and orchestrating
multi-container apps, letting you focus on code

=== Sources

- https://devblogs.microsoft.com/dotnet/conversation-about-containers/?ref=daveabrock.com[Conversation about containers]
- https://cloud.tencent.cn/developer/article/1958158?from=15425
- https://aws.amazon.com/cn/blogs/modernizing-with-aws/modernize-legacy-net-apps-to-amazon-eks-using-windows-containers-and-cloudhedge-chai/?nc1=b_rp
