= Notes

Container runtimes are not just **Docker**. There are tons of them out there,
just to name a few:

- Docker
- Podman
- Rancher

Amongst the options that are available for OSs such as **Red Hat** we have `podman`
as part of the default tools when it comes to container management.

Installing it in distros such as `arch` can have sometimes issues, so this is
but logs when trying to install podman (and also configuration of Quadlets in case
you hate yourself and are constrained by all possible directions)

== Installing podman on Arch

Sometimes by doing a `yay -S`, you might run into issues such as `mirror synchronization`.
The package may exist in the repo metadata, but some mirrors might not be fully synced
yet. Which can lead to `404` errors.

You should try to sync the mirrors again:

- `sudo pacman -Syyu`
- `sudo pacman-mirrors --fasttrack`
- `yay -S podman`

== Errors on trying to use podman as docker

You might run into an issue such as:

````
netavark: nftables error: "nft" did not return successfully while applying ruleset
````

First, why would this pop-up? If you have Docker already working you might wonder,
**docker works?**

- **Docker** uses its own networking stack (iptables + dockerd daemon)
- **Podman (rootless) uses:**
	- `netavark` (network engine)
	- `nftables` (kernel firewall interface)

So Podman might be trying to configure firewall via `nft` and that might fail.

You can try to restart/reset the nftables state:

- sudo systemctl restart nftables
- sudo nft flush ruleset

However, the `nftables` configuration might be broken, so you might have to reset
the file:

- `sudo hx /etc/nftables.conf`

Replace everything with:

````
flush ruleset

table inet filter {
  chain input {
    type filter hook input priority 0;
    policy accept;
  }

  chain forward {
    type filter hook forward priority 0;
    policy accept;
  }

  chain output {
    type filter hook output priority 0;
    policy accept;
  }
}
````

- `sudo systemctl restart nftables`

Even after all of this, you might try to build a `Dockerfile` with podman and still
run into issues such as:

NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json
Resource temporarily unavailable (api.nuget.org:443)

When trying to use network to get data, the DNS might be faulty, so another thing
to look out for:

- podman run --rm alpine cat /etc/resolv.conf
- sudo mkdir -p /etc/containers
- sudo nano /etc/containers/containers.conf

And add:

````
[network]
dns_servers=["1.1.1.1", "8.8.8.8"]
````

You can then try to hit nuget manually with podman and a test image like alpine:

````
podman run --rm alpine ping -c 1 api.nuget.org
podman run --rm alpine ping -4 api.nuget.org
podman run --rm curlimages/curl https://api.nuget.org/v3/index.json
````

And if you run into any of these commands with an error such as: `ping: bad address 'api.nuget.org'`
and or `short-name "curlimages/curl" did not resolve
no unqualified-search registries are defined`

This means that Podman networking might be broken, and also that a default container
registry might not be set in place. So:

- `sudo nano /etc/containers/registries.conf`

Add inside:
`unqualified-search-registries = ["docker.io"]`

**Double check if the dns configuration is correctly setup**

After all of that:

- `podman system reset -f`
- `podman run --rm alpine cat /etc/resolv.conf`
- `podman run --rm alpine ping api.nuget.org`

== The podman-compose debacle (Quadlets)

There are bugs and edge cases for `podman-compose` involving:

- shutdown ordering
- sd_notify
- restart semantics
- rootless containers
- podman-restart.service behavior

However:

- Red Hat heavily recommends systemd integration
- Podman is deeply integrated with systemd
- Quadlets are becoming the preferred operational model

`systemd` is a process supervisor, not a cluster orchestrator.

What Red Hat actually expects smaller deployments to do:

````
Podman
+
systemd / Quadlets
+
Ansible
````

`Podman` introduced Quadlets specifically because:

- generating giant systemd units was painful
- compose semantics were inconsistent
- people wanted declarative infra

A quadlet looks like:

````
[Container]
Image=nginx
PublishPort=8080:80
Volume=data:/data

[Service]
Restart=always

[Install]
WantedBy=multi-user.target
````
systemd then generates the underlying service. This is much cleaner than raw
generated unit files.

"Recommendation" is:

If you want:

- single-node orchestration
- declarative config
- restart guarantees
- dependency ordering
- health checks
- minimal moving parts

Then you can build a lightweight orchestration layer yourself.

And many companies effectively do.

The simplest and reliable architecture:

````
Git repo
  ↓
Ansible or shell deploy
  ↓
Quadlet files
  ↓
systemd
  ↓
Podman containers
````

The biggest limitation with `systemd` is though: **No higher-level deployment abstraction**

Compose gives:

- a single application model
- dependency graphs
- one-file infra definition

systemd does not naturally model:

-“this whole app stack”

without custom tooling.

Translating a `docker-compose` would mean you would have to create container files,
network files, and a `target` file

And then executing something like:

````
systemctl daemon-reload
systemctl enable --now *.service
````

This is how a network would be declared so that all the containers can attach
themselves to it:

````
# /etc/containers/systemd/aspire.network

[Network]
NetworkName=aspire
Driver=bridge
````

You could leverage an `.env` file, but it's... not really something like in
docker. However here's how it would look like:

````
# /etc/containers/systemd/aspire.env

APISERVICE_IMAGE=aspireapp1.apiservice
APISERVICE_PORT=8080

RABBIT_PASSWORD=12345678
RABBIT_USERNAME=admin

RABBITCONSUMER_IMAGE=aspireapp1.rabbitconsumer
RABBITCONSUMER_PORT=8080

SQL_PROBE_IMAGE=mssqlprobe.apiservice
SQL_PROBE_PORT=8080

WEBFRONTEND_IMAGE=aspireapp1.web
WEBFRONTEND_PORT=8080
````

When you save the container files, (will be referred as Quadlet), will become
a systemd service unit automatically, the name will follow:

`<filename>.service`

Examples:

````
seq.container  → seq.service
apiservice.container → apiservice.service
rabbitmq.container → rabbitmq.service
````

So actually, Quadlets are **systemd generators**

At boot or during `daemon-reload`, systemd does:

````
*.container  ──► generates ──► *.service (Podman-managed)
````

You would start the containers as services through:

````
sudo systemctl daemon-reload
sudo systemctl start portainer.service
sudo systemctl enable portainer.service
````

So where do the different files go?

- `/etc/containers/systemd`
	- `*.container`
	- `*.network`
- `/etc/systemd/system`
	- `*.target`

[IMPORTANT]
====
Careful, because `podman` tries to work with `rootless` and you can get to build
the images that way. But system will try to leverage podman `rootful` so unless
you have the images in the root images layer. Then rootful podman won't be able
to see them and pull them
====

So a good workaround is to pull down the images from `rootless` and upload them
with `rootful`:

- `podman save -o apiservice.tar localhost/aspireapp1.apiservice:latest`
- `sudo podman load -i apiservice.tar`

And you can see logs as easily as docker:

`sudo podman logs webfrontend`

If you setup the Quadlets as `PartOf=aspire.target` for example, then you will
gain the behavior of EVERYTHING GOES UP, EVERYTHING GOES DOWN.

== Quadlets, Pods, and working with the latest Podman, Podman 5

Notes taken from: https://www.youtube.com/watch?v=LsZB_mI7TcQ

**What is a Pod:**

Normally when you make a container, you have this **one instance** that has a
bridge into your host's network. But a Pod, becomes this _bag_, or _box_, in which
**many containers can live**. They all see each other within the pod, and the
pod itself has this bridge to the host's TCP stack. _However_, you can configure
the pod to have specific ports opened up to the host, and have those ports also
be bound to specific containers of the pod.

Examples of things that don't need to be accesible:

- A database
- Redis
These things can be in the pod, yet have no access from the outside. So you have
services that serve the outside, and services that are just on the inside.

_There's DNS resolution also inside of the pod, you can call containers by name
within the pod, and other nice additions_

**What is a difference between a container and a pod**

- When you spin up a container, you get your own namespace. Your network, binds,
etc. Unless you expose things to the host, it has no access.
- When you spin up a pod, it's a container of containers, it establishes a shared
namespace amongst these containers. Unless you set things up specifically, there's
no access to the outside
	- You can start-stop the whole thing as a stack
	- **Drawback:** You can't tell it "which containers to start first". Database
	first, and then other things. (Apparently with Podman 5.0 there's a solution
	for that???)

=== Creating and Managing Pods

Let's start with a small problem:

We have some database and services that we want to spin up. And we want to actually
bundle them together, yet keep them non accesible from the outside.

`podman pod`

- `podman pod create --name mysql-test` => Hit Enter, this creates an empty pod

When you are building the pod, you would also just add `-p xxx`, and you need
to think about this detail when creating the pod.

_If you have a pod with multiple containers, how much do you need to allocate_?

Putting it in a pod, no overhead should be added. It will depend on what you are
running inside. E.g., A huge database container => Plan resources accordingly

Podman = Mostly namespaces. A pod is actually a **container**. You can do
a `podman ps -a` and you should see some infra-image container present.

**How do you put a container in a pod?**

You would run a container like always and then add a pod parameter: `--pod=mysql-test`.

- `podman run --pod=mysql-test -d registry.redhat.io/rhel9/mysql-80 --name mysql-server`

If you attach a second container, say a mysql client to connect to a mysql database,
you can actually refer `localhost` or `127.0.0.1` or the container name that
you want to connect to. Due to the two containers being part of a pod, they will be
able to resolve the respective host without issue. **Because the pod becomes like
a master process that has its own ports, and the containers share that same namespace
and ports**

- `podman pod logs mysql-test` => This shows the logs of all containers attached
to a pod.
- `podman pod stop mysql-test`
- `podman pod start mysql-test`
- `podman pod ps mysql-test`

If there's a pod, and some attached container is stopped, if you do a `podman pod
ps` the pod entry will show up as **Degraded**. So this opens up the possibility
of scripting a bit, checking for degraded pods and take action. Like automatic
restarts, self healins, and/or alert sending. There be smarter ways than writing
a `bash` script; but if it works, it works.

- Quadlets => Systemd flavored config files, that allows to generate systemd
services for containers.

**Kubernetes:**

Larger, more, clusterable container management platform. Open Shift is based on
it. It uses yaml to define about everything, and one of those things are **pods**.

[NOTE]
----
`podman generate kube mysql-test` => This will spit out on the screen a `yaml`.
You have to accomodate other things. But this is really cool to go from single
host containerization to clusters.
----

[source, yml]
.wordpress-pod.yml
----
apiVersion: v1
kind: Pod <.>
metadata:
  labels:
    app: wordpress <.>
  name: wordpress
spec:
  containers:
  - name: db
    envFrom:
	- configMapRef:
		name: wordpress-env <.>
		optional: false
	image: docker.io/library/mariadb:lts-ubi
	resources: {}
	securityContext:
	  allowPrivilegeEscalation: true
	  capabilities: {}
	  privileged: false
	  readOnlyRootFilesystem: false
	volumeMounts:
	- mountPath: /var/lib/mysql:Z <.>
	  name: db-vol
	workingDir: /
  - name: wordpress
    envFrom:
	- configMapRef:
		name: wordpress-env
		optional: false
	image: docker.io/library/wordpress:latest
	ports:
	- containerPort: 80
	  hostPort: 80
	  protocol: TCP
	resources: {}
	securityContext:
	  allowPrivilegeEscalation: true
	  capabilities: {}
	  privileged: false
	  readOnlyRootFilesystem: false
	volumeMounts:
	- mountPath: /var/www/html/wp-content:Z
	  name: wp-content-vol
	workingDir: /var/www/html
  volumes: <.>
  - hostPath:
	  path: /srv/container-data/wordpress/wp-content
	  type: Directory
	name: wp-content-vol
  - hostPath:
	  path: /srv/container-data/wordpress/db
	  type: Directory
	name: db-vol
status: {}
----
<.> The `kind` helps a lot to typify the artifact. So really careful around it
<.> By changing these values you can then give a name that you see when you do
a `podman ps`
<.> And this is a great way to abstracta away configuration values, further down
is the contents of such as `configMapRef`
<.> You can point to the containers paths that need to be persisted through a
bind with the host
<.> Lastly you have your volume definition

[source, yml]
.wordpress-configmap.yml
----
apiVersion: v1
kind: ConfigMap
metadata:
	name: wordpress-env
data:
	MARIADB_ROOT_PASSWORD: "MyRewtPassword"
	MARIADB_DATABASE: wordpress
	MARIADB_USER: wordpress
	MARIADB_PASSWORD: "WordPressPassword"
	WORDPRESS_DB_HOST: wordpress-db
	WORDPRESS_DB_NAME: wordpress
	WORDPRESS_DB_USER: wordpress
	WORDPRESS_DB_PASSWORD: "WordPressPassword"
----

And now you can easily pipe all of these types of files to a `kube` file, by
creating such a kube like so:

[source, kube]
----
[Install]
WantedBy=default.target

[Unit]

[Kube]
Yaml=/etc/containers/systemd/wordpress-pod.yml <.>
ConfigMap=/etc/containers/systemd/wordpress-configmap.yml <.>
PublishPort=80:80 <.>
----
<.> You can literally set up your whole architecture and point to it
<.> Then we need to manually point to the config file, otherwise this won't be
recognized
<.> And then we need to also establish what port we are going to publish

**This will spit out a whole systemd unit file with the pod**. At once.

If you stop the pod, if you restart it. It will actually destroy the pod, and bring
back a new instance, which means that all references for images for example, will
pull the latest version from the respective repos (so it's an auto-update or well
sleek way to auto-update your pod). **If you don't want that, then you should
tag your container so that you use a specific version not `latest`**

- Need to change the configuration? Just change your configuration file, and
restart the pod, that's it BROTHER.

=== Quadlet

_Extra:_ Most projects come with a `docker-compose` file, many DevOps will grab
that, read it, translate it to pods, which sometimes come with their own challenge
in mind, so guestimates are a thing.

Once the pod is created, then the `kube` generation can be run.

There's this new `[Pod]` unit, a new format that apparently is the native podman
way of dealing with `docker-compose`.

- Create a `.pod` file
	- `hx sql.pod`

````
[Pod]
PodName=forgejo
PublishPort=3000:3000
PublishPort=222:22
````

_Note:_ A nice thing about keeping config files, parameters, conventions in place,
is that when new tools, or similar tools come into the mix, you reuse a lot of the
same concepts and ideas, which makes it way more intuitive to understand what's
going on or how to use tools and configure them.

And now, based on the conventions used by Quadlets. It looks as though inside
your `.container` file you should be able to attach it to a pod with:

````
[Container]
...
Pod=forgejo

[Service]
...

[Install]
....
````
Things are stitched together based on all the different files with conventions and
the tool.

[IMPORTANT]
====
Why when using podman you need to fully qualify the image name? Example:
`Image=registry.redhat.io/rhel9/mysql-80`. Because podman makes no assumptions
as to from where you want to pull an image, `docker` **DOES**. If you don't specifiy
the registry, podman will ask "From which registry will you get this?"
====

.mysql.container
````
[Container]
Image=registry.redhat.io/rhel9/mysql-80
Environment=MYSQL_ROOT_PASSWORD=forgejo
Environment=MYSQL_USER=forgejo
Environment=MYSQL_PASSWORD=forgejo
Environment=MYSQL_DATABASE=forgejo
Pod=forgejo
````

How do you define volumes with Quadlets?

_Question:_ How can we centralize all definitions? Maybe with a Pod?

Host Path in the `.container` file Easily:

`Volume=/mysql:/var/lib/mysql`

So the way you would dump your files to the respective paths would be something
like this:

- With files that look like this:
	- forgejo-data.volume
	- forgejo.container
	- forgejo.network
	- forgejo.pod
	- mysql.container
- You would run: `sudo cp forgejo* /etc/containers/systemd`
- And then you need to copy the specific container into: `sudo cp mysql.container /etc/containers/systemd/``
- `sudo systemctl daemon-reload`

Now of course, things cannot work at all, and the journal entry helps not at all.

So you have a tool that helps running a dry run, and it outputs any errors it founds
with what you tried to setup:

`sudo /usr/libexec/podman/quadlet --dryrun`

The video failed, it seems and the solution seems to be that when you are declaring
`Pod=forgejo` you actually have to suffix it like this: `Pod=forgejo.pod`. On
all containers you are attaching to a pod, you should reference it like that.

And then it didn't work entirely, but 95% of the way there, because the service
at least was created correctly.

== Podman containers, quadlets, and automation | Into the Terminal 178

Notes taken from: https://www.youtube.com/watch?v=go8LCGe_eBA

Run podman containers in a more accesible way. Something that can be actually
used in a company.

OpenShift and Kubernetes are great for heavy scale enterprise solution. But there's
a niche in the middle in which you don't that heavy of a solution. Yet you still
need to do some containerization.

**Basics**

Let's run a container:

`podman run -d --name httpd -p 8080:80 docker.io/httpd`

_Commands in podman are pretty identical to docker. The idea is to be interchangable._

We are going to start up an apache container. We are running _detached_, and we will
publish a port on the host so that it pipes any traffic there to the container's
port `80`. You can use **any registry you want**, even docker hub.

[NOTE]
====
You can bind a container to a specific IP address, or to some domain. That way
on the same IP Address you can setup your containers to run services.
====

Running a container feels the same as in docker.

Podman:

- Groups containers together
- Adds them to a network
- Adds them to a namespace

It's good to put a lot of components that run together in a pod, that way it's
orchestrated easily.

Once you define pods, you can export with them to a yaml file, that looks just like a
`yaml` file.

That means, that if you migrate to OpenShift or Kubernetes, you are halfway there.

[NOTE]
====
When you set volumes, be sure to create the host's paths. Podman won't create
them for you, unless you have setup your containers and pods a certain way, which
in the `.yaml` file translates to suffixing the paths with `:Z`. But don't take
it for granted.
====

The way you can run the whole orchestrated "group" is by running:

- `podman play kube ./wp-pod.yml`

When you run a `kube` you will always have N + 1 containers, because there's an
infrastructure container always created.

If everything has been setup correctly, you should be able to see your services
and websites working.

The magic behind `yml` files and also volumes that are just physical paths to
your host, is that migrating/moving to another host is quite straightforward.
You would copy the `.yml` and you would copy the respective paths' contents to
the other host, put the content in the same path, and use the **whatever** tool
you want to bring the `.yml` into podman and instantiate all the architecture.
And seamlessly you would get your app backup easily.

=== A flaw of running podman containers manually

- Docker => Runs things as a daemon.
- Podman => Runs everything under the context of a user, it doesn't need to be
`root`
	- If someone breaks away from a container, you would then only have a specific
	user's privileges.
- **The flaw:** You leave the app running, but then you reboot, none of everything
comes back up
	- Podman has a `restart always` but it doesn't really work the same way as
	docker
- The pod would be defined, but it wouldn't be running (after a restart)
	- Podman integrates always with systemd
		- Quadlet = Systemd generator. You can define these files that Quadlet will
		then parse and write systemd unit files for

So in order to get around that, we will make usage of two files:

````
[Unit]
Description=Httpd Container

[Container]
Image=docker.io/httpd.latest
#Environment=SOMEVARD=value
PublishPort=8080:80

[Install]
WantedBy=multi-user.target
````

This is a Quadlet. A lot of directives are under `[Container]` that you would
normally use for running containers.

**Note:** You **CAN** run Quadlets as a normal user, you can setup `systemd` so that
it knows that it can look up in your user directory, and then try to startup services
or whatever. But for this demo's purposes we will just use the root paths:

- `cp httpd````-podman.container /etc/containers/systemd`

And then you can test out if it will work by executing a dry run:

- `sudo /usr/lib/podman/quadlet --dryrun`
	- _Note:_ This is for arch. Maybe in Red Hat it's under `libexec64` so be
	aware that the CLI tool may vary.

If you run the dry run you will see how quadlet will take care of setting up a lot
of expanded instructions and configurations. By design, when you start or stop
a service, the container is completely taken out. A brand new container comes back
up. "The container is completely undefined"

It makes it a lot easier to update containers, because of this behavior.

And now, let's run the quadlet for real:

- `sudo systemctl daemon-reload`

When systemd reloads the daemon, it will re-read the quadlet, quadlet will execute
and run all the definitions that we configured.

- `sudo systemctl start httpd-podman`
- `systemctl status httpd-podman`

After the daemon reload, you wouldn't have your container/pod running, you have
to boot it up yourself, and yes, you can easily check the status by using the
built-in systemctl commands to, because in the end, the container/pod becomes
a service.

**Quadlets** are designed to do everything you should be able to do with podman
but in their own respective use case and architecture. (Build pods, containers,
networks, volumes). You can define your entire architecture in quadlet files,
and have them go up immediately.

And then, to make a thin abstraction layer, we can leverage `.kube` so that we
run our `yaml` that we might generate based on a pod definition:

.wordpress-pod.kube
````
[Install]
WantedBy=default.target

[Unit]

[Kube]
Yaml=/etc/containers/systemd/wp-pod.yaml
PublishPort=8081:80
````

`sudo cp wordpress-pod.kube /etc/containers/systemd/`

The location of the yaml file is up to you, you can even leverage the relative
path of `/etc/containers` so bear in mind all of this.

Also, _if you run a quadlet as root, it would make no sense to put the volume
paths in the home directory of a user_. So a good path to put it might be:

- `/srv/containers/<name>` / `/srv/`

`srv` => Is a place that's immutable.
`var` => Another place you can put things, but in here they should be mutable

If you run a `sudo systemctl daemon-reload` and you try to list the new container
service, you should see it as generated/defined, but not running

- `sudo systemctl status wordpress-pod`
- `sudo systemctl start wordpress-pod`
- `sudo podman ps`

**Do these things persist in reboot?**

- Let's see if systemd will bring back the kube on startup
- **It does**

And yes, you should be able to see the containers running:

- `sudo podman ps`
- `sudo podman pod ps`

And that's it. Okay, no. It's not. Let's have a look at automations.

- There's a RHEL role that can help with that. You can automate this whole process.

=== Automation

This makes usage of `Ansible`. Which apparently can be used as a deploy tool
directly? Huh.

So we can create a playbook that will take care of doing everything for us:

- It uses the system role to figure out what you are trying to deploy, and it
deploys it as a quadlet
	- Makes sure all the supporting things are there
	- Makes sure the firewall is configured
	- Automate all the heavy lifting
	- Everything is automatic, the whole instruction set, the whole logic comes
	with ansible already aware of that. We don't have to do anything.

````
- name: Deploy a single container using RHEL System Roles
  hosts: podman-hosts
  become: true
  vars:
    # Ensure the required firewall ports are open
	podman_firewall:
	  - port: 8080/tcp
	    state: enabled
	# Define the container specification
	podman_quadlet_specs:
	  - name: httpd-podman
	    type: container
		Container:
		  Image: docker.io/httpd:latest
		  PublishPort: "8080:80"
		  # Optional: Add environment variables or volumes
		  # Environment: "FOO=BAR"
		  # Volume: "/host/path:/container/path:Z"
		Service:
		  Restart: always
		Install:
		  WantedBy: multi-user.target

roles:
  - rhel-system-riles.podman
````
If we didn't set the `firewall` bit, maybe it wouldn't have installed the respective
dependency that is `firewalld` so he makes super ultra duper sure that you have
everything that you need to then start everything you have.

And then you can just run a:

`ansible-playbook -i ./inventory container/httpd-podman.yaml`

**EXTRA:** An `inventory file` tells Ansible _which machines (hosts)_ it should
manage.

An inventory file is basically a list of hosts and groups:

````
[webservers]
server1.example.com
server2.example.com

[db]
db1.example.com
````
This says:
- There is a group called `webservers`
- It contains two hosts
- Another group called `db`

The playbook can then target those groups

You can both put `.ini` files or `.yaml` files as the ansible playbook. And you
can put direct IPs too. Some useful commands:

_View inventory hosts_

- ansible-inventory -i ./inventory --list

_Ping all hosts_

- ansible all -i ./inventory -m ping

_Run against localhost only_

- ansible-playbook -i localhost, playbook.yaml
	- NOTE: If you put a `,`, comma after `localhost` this tells Ansible it's an
	inline inventory list, not a filename

Now, you can technically "undo" all the deployment that Ansible does, but it's not
built into the tool and the manifest/playbook. You have to create a an undo playbook
yourself, by going in reverse of everything your original playbook did.

Big note: Ansible is **idempotent**

Safer strategies:

1. Use containers/VMs => That way a deployment only uses a container

2. Use tags => You can separate deploy and cleanup:

````
- name: Deploy
  tags: deploy
- name: Cleanup
  tags: cleanup
````

Which then allow you to: `ansible-playbook playbook.yaml --tags cleanup`

3. Use infrastructure snapshots

In production people often rely on:

- VM snapshots
- cloud images
- Kubernetes rollbacks
- immutable infrastructure
- GitOps

Rather than trying to reverse arbitrary server mutations

An `ansible` playbook takes a bit of time, but after everything is done, you should
be able to run a `curl` on the machine that had everything deployed. And you
should be receiving the a response according to the apache quadlet that was
deployed.

If you go into the deployed host, you should also be able to see the container
present:

`cat /etc/containers/systemd/httpd-podman.container`

And yeah, the file might not looks exactly the same, but it's functional and
you have everything you need so that it runs.

Also, the whole process of

- Have a system role, generate the kube
- Have a Quadlet to use the kube as its manifest to get the whole architecture
- Semi-manually do things

Is good, and works, but you can be better.

=== Fancier deploys

- Might be able to use "Jinja" templates
	- These are for services that look almost the same, and you want to run over
	and over again
	- But there are setups in which this isn't the case, and it doesn't work like
	that, so we can still have the definition `yaml` and then use it to spin up
	our architectures

You can make things a bit more dynamic by putting some placeholders in the file:

````
- name: Deploy the wordpress pod
  hosts: podman-hosts
  become: true
  vars:
    app_name: "wordpress"
	svc_name: "{{ app_name }}-pod"
	quadlet_config: "/etc/containers/systemd"
	pod_yaml_path: "{{ quadlet_config }}/{{ svc_name }}.yaml"
	additional_folders:
	  - /srv/containers/wp/db
	  - /srv/containers/wp/wp-content
	podman_firewall:
	  - port: 8081/tcp
	    state: enabled
	podman_kube_specs:
	  - state: started
	    kube_file_src: files/wordpress-pod.yaml
		  #kube_file_dest: "{{ pod_yaml_path }}"
		quadlet_options:
		  - ConfigMap:
		      PublishPort: "8081:80"
		  - Service:
		      Restart: always
  pre_tasks:
    - name: Create required folders
	  ansible.builtin.file:
	    path: "{{ item }}"
		state: directory
		mode: "0755"
		setype: container_file_t
      loop: "{{ additional_folders }}"
  roles:
    - linux-system-roles.podman
````
When dealing with automation, you wouldn't want to leave to chance, whether the
filesystem that your architecture needs exists on the server or not.

So if you make a list of directories that your architecture depends on with `additional_folders`
you will see how the respective filesystem gets created.

`pre_tasks` => Run this before you run the normal tasks, before you run the roles.
Pre Tasks will always run first. That way you setup the environment to run your
roles.

You can run it like this:

- `ansible-playbook -i ../inventory wordpress-pod.yaml`

**Note:** `podman pull` => This will be pulled into your local podman images.
`podman image list` => Local cache. `podman tag` can help tagging with a registry
of your local registry. And then you can use `podman push` so that you can
push the image to that other registry.

- So you downloaded from a public registry
- And then you push that to your internal registry
	- Now you are in charge of that image and updates
	- There's lots of way to run registries
		- There's a docker container
		- There are lightweight git/registry combinations in a container
		- Gitlab => You can run your own instance, your own CI/CD can be setup
		to push to a local registry. That's as local as it can be

`forgejo` => Also another registry option

If you edit your inventory file, and add a second host, you can literally add it
to the file and re-run the ansible command.

- That way you easily reproduce the deployment across multiple hosts, easily and
quick
- The previously configured instance will be skipped

Ansible can make things pretty easily automatable

== Make systemd better for Podman with Quadlet

Notes taken from blog at: https://www.redhat.com/en/blog/quadlet-podman

One of the best features of `Podman` is how well it works with systemd. Podman uses
the standard fork/exec model, which is easily adaptable to the systemd system and
service manager model.

````
"Running containerized workloads in systemd is a simple yet powerful means for
reliable and rock-solid deployments. The systemd integration further lays the
foundation for more advanced Podman features such as auto updates and rollbacks
or running Kubernetes workloads in systemd. This integration allows systemd to
manage service dependencies, monitor the lifecycle and service state, and possibly
also restart services in case of failure."
````

Once administrators realized that Podman works well in systemd unit files, the
Podman upstream started getting questions on best practices for running Podman
as a systemd service. Red Hat studied the issues and worked with the upstream
systemd team to template these best practices. Podman added `podman generate systemd`
command to create a unit file directly from a running container.

Alex Larsson created the Quadlet project after _figuring out a better way to use
this templating_ using systemd generators to regenerate services on the fly using
a generic systemd unit file definition. Quadlet hit the complexity of running
containers under systemd from users, making writing unit files from scratch much
easier to maintain. Think of it as `Compose` or Kubernetes file but for systemd.
Once written, you can deploy it anywhere.

_What do you get if you squash a Kubernetes kubelet? A quadlet_

Quadlet is a tool for running Podman containers under systemd in an optimal way by
allowing containers to run under systemd in a declarative way. it has been merged
into Podman 4.4

As the (now frozen) Quadlet repository says:

_Paraphrasing:_

- Containers are often used in Cloud contexts and with Kubernetes as an orchestrator.
They are also commonly used during development and testing to manually manage
containers on an ad-hoc basis. But there's a niche for automatic container management,
but on a smaller, single-node scale. Also more tightly integrated with the rest
of the system. The recommended way to do this is to use systemd to orchestrate the
containers, this is **an already running process manager**. There are many documents
that describe how to use podman with systemd directly, but the end results are generally
large, hard to maintain systemd config files. And often the container setup isn't
optimal.

Basically, anywhere you want to run a containerized system service without requiring
human intervention, it's wise to use systemd to manage your locally running Podman
containers.

=== Using Quadlet in Podman

You can create `CTRNAME.conatiner` unit files taht can be placed in one of the
following directories:

````
/usr/share/containers/systemd/
/etc/containers/systemd
````

For rootless users:

$HOME/.config/containers/systemd

This is an example that creates a `mysleep.container` unit file that runs the
`sleep 1000` command on a **ubi9-minimal** container image:

````
cat $HOME/.config/containers/systemd/mysleep.container
[Unit]
Description=The sleep container
After=local-fs.target

[Container]
Image=registry.access.redhat.com/ubi9-minimal:latest
Exec=sleep 1000

[Install]
# Start by default on boot
WantedBy=multi-user.target default.target
````

Notice that in the `[Container]` section. You just need to specify the `Image` you
want to run and the command `Exec` that you want to run, and then you can use all
of the other fields normally specified in a systemd unit file.

After that, you just need to inform systemd about the new unit file. Type:

`systemctl --user daemon-reload`

This will create a `mysleep.service` file based on the `mysleep.container` file

`systemctl --user status mysleep.service`

Now you can enable this service or start it up:

`systemctl --user start mysleep.service`

The `podman` command inside the generated service will download the **ubi9-unit**
image and start the specified command, `sleep 1000`

You can check the status of the service like this:

`systemctl --user status mysleep.service`

When `Podman` is installed, it registers a `systemd-generator` tool that looks for
files in the above directories and runs the `/usr/libexec/podman/quadlet` executable.

You can also do a dry run to see everything the quadlet executable will do:

````
$ /usr/libexec/podman/quadlet -dryrun -user
quadlet-generator[265731]: Loading source unit file /home/dwalsh/.config/containers/systemd/mysleep.container
---mysleep.service---
[Unit]
Description=The sleep container
Before=local-fs.target
SourcePath=/home/dwalsh/.config/containers/systemd/mysleep.container
RequiresMountsFor=%t/containers

[X-Container]
Image=registry.access.redhat.com/ubi9-minimal:latest
Exec=sleep 1000

[Install]
# Start by default on boot
WantedBy=multi-user.target default.target

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
KillMode=mixed
ExecStopPost=-/usr/bin/podman rm -f -i --cidfile=%t/%N.cid
ExecStopPost=-rm -f %t/%N.cid
Delegate=yes
Type=notify
NotifyAccess=all
SyslogIdentifier=%N
ExecStart=/usr/bin/podman run --name=systemd-%N --cidfile=%t/%N.cid --replace --rm --log-driver passthrough --runtime /usr/bin/crun --cgroups=split --sdnotify=conmon -d registry.access.redhat.com/ubi9-minimal:latest sleep 1000
````

The Quadlet-generated service file uses the same libraries as `podman generate systemd -new`
but hides the complexity from the user.

One benefit is if a newer version of Podman is released with fixes or enhancements
to the generator, your service is updated with the enhanced version the next time
`systemctl daemon-reload` executes, such as upon reboot.

The container descriptions focus on the relevant container details, with no technical
details about how the Podman integration works. This means they are straightforward
to write and maintain, and integration can automatically improve as new Podman
features become available. Now you can use the other cool features of Podman in
systemd, like `auto-update and rollback`, for hands-free management of your
containerized service's lifecycle.

Quadlet supports other advanced unit files, in addition to **.container**

- `.kube` allows you to specify a Kubernetes.yaml file, which tells Quadlet to
create a service file to run pods and containers under systemd services based on
Kubernetes
- `.network` tells Quadlet to create a service file that defines a Podman container
network device. These network devices can then be used within `.container` and
`.kube` unit files
- `.volume` tells Quadlet to create a service file that defines a Podman volume.
These volumes can then be used within `.container` unit files

**In summary**

Quadlet allows running containers under systemd in a declarative way. Similar to
Compose or Kubernetes files, you can declare what you want to run without having
to deal with all the complexities of running the workload.

Podman has a long history of integrating well into a modern Linux system, and
Quadlet pushes the integration to the next level. Podman 4.4 has already been
released to many Linux distributions, such as CentOS Stream and Fedora.

Extras:

https://docs.podman.io/en/latest/markdown/podman-quadlet-basic-usage.7.html[Docs on podman Quadlets]
