= Notes

Container runtimes are not just **Docker**. There are tons of them out there,
just to name a few:

- Docker
- Podman
- Rancher

Amongst the options that are available for OSs such as **Red Hat** we have `podman`
as part of the default tools when it comes to container management.

Installing it in distros such as `arch` can have sometimes issues, so this is
but logs when trying to install podman (and also configuration of Quadlets in case
you hate yourself and are constrained by all possible directions)

== Installing podman on Arch

Sometimes by doing a `yay -S`, you might run into issues such as `mirror synchronization`.
The package may exist in the repo metadata, but some mirrors might not be fully synced
yet. Which can lead to `404` errors.

You should try to sync the mirrors again:

- `sudo pacman -Syyu`
- `sudo pacman-mirrors --fasttrack`
- `yay -S podman`

== Errors on trying to use podman as docker

You might run into an issue such as:

````
netavark: nftables error: "nft" did not return successfully while applying ruleset
````

First, why would this pop-up? If you have Docker already working you might wonder,
**docker works?**

- **Docker** uses its own networking stack (iptables + dockerd daemon)
- **Podman (rootless) uses:**
	- `netavark` (network engine)
	- `nftables` (kernel firewall interface)

So Podman might be trying to configure firewall via `nft` and that might fail.

You can try to restart/reset the nftables state:

- sudo systemctl restart nftables
- sudo nft flush ruleset

However, the `nftables` configuration might be broken, so you might have to reset
the file:

- `sudo hx /etc/nftables.conf`

Replace everything with:

````
flush ruleset

table inet filter {
  chain input {
    type filter hook input priority 0;
    policy accept;
  }

  chain forward {
    type filter hook forward priority 0;
    policy accept;
  }

  chain output {
    type filter hook output priority 0;
    policy accept;
  }
}
````

- `sudo systemctl restart nftables`

Even after all of this, you might try to build a `Dockerfile` with podman and still
run into issues such as:

NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json
Resource temporarily unavailable (api.nuget.org:443)

When trying to use network to get data, the DNS might be faulty, so another thing
to look out for:

- podman run --rm alpine cat /etc/resolv.conf
- sudo mkdir -p /etc/containers
- sudo nano /etc/containers/containers.conf

And add:

````
[network]
dns_servers=["1.1.1.1", "8.8.8.8"]
````

You can then try to hit nuget manually with podman and a test image like alpine:

````
podman run --rm alpine ping -c 1 api.nuget.org
podman run --rm alpine ping -4 api.nuget.org
podman run --rm curlimages/curl https://api.nuget.org/v3/index.json
````

And if you run into any of these commands with an error such as: `ping: bad address 'api.nuget.org'`
and or `short-name "curlimages/curl" did not resolve
no unqualified-search registries are defined`

This means that Podman networking might be broken, and also that a default container
registry might not be set in place. So:

- `sudo nano /etc/containers/registries.conf`

Add inside:
`unqualified-search-registries = ["docker.io"]`

**Double check if the dns configuration is correctly setup**

After all of that:

- `podman system reset -f`
- `podman run --rm alpine cat /etc/resolv.conf`
- `podman run --rm alpine ping api.nuget.org`

== The podman-compose debacle (Quadlets)

There are bugs and edge cases for `podman-compose` involving:

- shutdown ordering
- sd_notify
- restart semantics
- rootless containers
- podman-restart.service behavior

However:

- Red Hat heavily recommends systemd integration
- Podman is deeply integrated with systemd
- Quadlets are becoming the preferred operational model

`systemd` is a process supervisor, not a cluster orchestrator.

What Red Hat actually expects smaller deployments to do:

````
Podman
+
systemd / Quadlets
+
Ansible
````

`Podman` introduced Quadlets specifically because:

- generating giant systemd units was painful
- compose semantics were inconsistent
- people wanted declarative infra

A quadlet looks like:

````
[Container]
Image=nginx
PublishPort=8080:80
Volume=data:/data

[Service]
Restart=always

[Install]
WantedBy=multi-user.target
````
systemd then generates the underlying service. This is much cleaner than raw
generated unit files.

"Recommendation" is:

If you want:

- single-node orchestration
- declarative config
- restart guarantees
- dependency ordering
- health checks
- minimal moving parts

Then you can build a lightweight orchestration layer yourself.

And many companies effectively do.

The simplest and reliable architecture:

````
Git repo
  ↓
Ansible or shell deploy
  ↓
Quadlet files
  ↓
systemd
  ↓
Podman containers
````

The biggest limitation with `systemd` is though: **No higher-level deployment abstraction**

Compose gives:

- a single application model
- dependency graphs
- one-file infra definition

systemd does not naturally model:

-“this whole app stack”

without custom tooling.

Translating a `docker-compose` would mean you would have to create container files,
network files, and a `target` file

And then executing something like:

````
systemctl daemon-reload
systemctl enable --now *.service
````

This is how a network would be declared so that all the containers can attach
themselves to it:

````
# /etc/containers/systemd/aspire.network

[Network]
NetworkName=aspire
Driver=bridge
````

You could leverage an `.env` file, but it's... not really something like in
docker. However here's how it would look like:

````
# /etc/containers/systemd/aspire.env

APISERVICE_IMAGE=aspireapp1.apiservice
APISERVICE_PORT=8080

RABBIT_PASSWORD=12345678
RABBIT_USERNAME=admin

RABBITCONSUMER_IMAGE=aspireapp1.rabbitconsumer
RABBITCONSUMER_PORT=8080

SQL_PROBE_IMAGE=mssqlprobe.apiservice
SQL_PROBE_PORT=8080

WEBFRONTEND_IMAGE=aspireapp1.web
WEBFRONTEND_PORT=8080
````

When you save the container files, (will be referred as Quadlet), will become
a systemd service unit automatically, the name will follow:

`<filename>.service`

Examples:

````
seq.container  → seq.service
apiservice.container → apiservice.service
rabbitmq.container → rabbitmq.service
````

So actually, Quadlets are **systemd generators**

At boot or during `daemon-reload`, systemd does:

````
*.container  ──► generates ──► *.service (Podman-managed)
````

You would start the containers as services through:

````
sudo systemctl daemon-reload
sudo systemctl start portainer.service
sudo systemctl enable portainer.service
````

So where do the different files go?

- `/etc/containers/systemd`
	- `*.container`
	- `*.network`
- `/etc/systemd/system`
	- `*.target`

[IMPORTANT]
====
Careful, because `podman` tries to work with `rootless` and you can get to build
the images that way. But system will try to leverage podman `rootful` so unless
you have the images in the root images layer. Then rootful podman won't be able
to see them and pull them
====

So a good workaround is to pull down the images from `rootless` and upload them
with `rootful`:

- `podman save -o apiservice.tar localhost/aspireapp1.apiservice:latest`
- `sudo podman load -i apiservice.tar`

And you can see logs as easily as docker:

`sudo podman logs webfrontend`

If you setup the Quadlets as `PartOf=aspire.target` for example, then you will
gain the behavior of EVERYTHING GOES UP, EVERYTHING GOES DOWN.

== Quadlets, Pods, and working with the latest Podman, Podman 5

Notes taken from: https://www.youtube.com/watch?v=LsZB_mI7TcQ

**What is a Pod:**

Normally when you make a container, you have this **one instance** that has a
bridge into your host's network. But a Pod, becomes this _bag_, or _box_, in which
**many containers can live**. They all see each other within the pod, and the
pod itself has this bridge to the host's TCP stack. _However_, you can configure
the pod to have specific ports opened up to the host, and have those ports also
be bound to specific containers of the pod.

Examples of things that don't need to be accesible:

- A database
- Redis
These things can be in the pod, yet have no access from the outside. So you have
services that serve the outside, and services that are just on the inside.

_There's DNS resolution also inside of the pod, you can call containers by name
within the pod, and other nice additions_

**What is a difference between a container and a pod**

- When you spin up a container, you get your own namespace. Your network, binds,
etc. Unless you expose things to the host, it has no access.
- When you spin up a pod, it's a container of containers, it establishes a shared
namespace amongst these containers. Unless you set things up specifically, there's
no access to the outside
	- You can start-stop the whole thing as a stack
	- **Drawback:** You can't tell it "which containers to start first". Database
	first, and then other things. (Apparently with Podman 5.0 there's a solution
	for that???)

=== Creating and Managing Pods

Let's start with a small problem:

We have some database and services that we want to spin up. And we want to actually
bundle them together, yet keep them non accesible from the outside.

`podman pod`

- `podman pod create --name mysql-test` => Hit Enter, this creates an empty pod

When you are building the pod, you would also just add `-p xxx`, and you need
to think about this detail when creating the pod.

_If you have a pod with multiple containers, how much do you need to allocate_?

Putting it in a pod, no overhead should be added. It will depend on what you are
running inside. E.g., A huge database container => Plan resources accordingly

Podman = Mostly namespaces. A pod is actually a **container**. You can do
a `podman ps -a` and you should see some infra-image container present.

**How do you put a container in a pod?**

You would run a container like always and then add a pod parameter: `--pod=mysql-test`.

- `podman run --pod=mysql-test -d registry.redhat.io/rhel9/mysql-80 --name mysql-server`

If you attach a second container, say a mysql client to connect to a mysql database,
you can actually refer `localhost` or `127.0.0.1` or the container name that
you want to connect to. Due to the two containers being part of a pod, they will be
able to resolve the respective host without issue. **Because the pod becomes like
a master process that has its own ports, and the containers share that same namespace
and ports**

- `podman pod logs mysql-test` => This shows the logs of all containers attached
to a pod.
- `podman pod stop mysql-test`
- `podman pod start mysql-test`
- `podman pod ps mysql-test`

If there's a pod, and some attached container is stopped, if you do a `podman pod
ps` the pod entry will show up as **Degraded**. So this opens up the possibility
of scripting a bit, checking for degraded pods and take action. Like automatic
restarts, self healins, and/or alert sending. There be smarter ways than writing
a `bash` script; but if it works, it works.

- Quadlets => Systemd flavored config files, that allows to generate systemd
services for containers.

**Kubernetes:**

Larger, more, clusterable container management platform. Open Shift is based on
it. It uses yaml to define about everything, and one of those things are **pods**.

[NOTE]
----
`podman generate kube mysql-test` => This will spit out on the screen a `yaml`.
You have to accomodate other things. But this is really cool to go from single
host containerization to clusters.
----

[source, yml]
.wordpress-pod.yml
----
apiVersion: v1
kind: Pod <.>
metadata:
  labels:
    app: wordpress <.>
  name: wordpress
spec:
  containers:
  - name: db
    envFrom:
	- configMapRef:
		name: wordpress-env <.>
		optional: false
	image: docker.io/library/mariadb:lts-ubi
	resources: {}
	securityContext:
	  allowPrivilegeEscalation: true
	  capabilities: {}
	  privileged: false
	  readOnlyRootFilesystem: false
	volumeMounts:
	- mountPath: /var/lib/mysql:Z <.>
	  name: db-vol
	workingDir: /
  - name: wordpress
    envFrom:
	- configMapRef:
		name: wordpress-env
		optional: false
	image: docker.io/library/wordpress:latest
	ports:
	- containerPort: 80
	  hostPort: 80
	  protocol: TCP
	resources: {}
	securityContext:
	  allowPrivilegeEscalation: true
	  capabilities: {}
	  privileged: false
	  readOnlyRootFilesystem: false
	volumeMounts:
	- mountPath: /var/www/html/wp-content:Z
	  name: wp-content-vol
	workingDir: /var/www/html
  volumes: <.>
  - hostPath:
	  path: /srv/container-data/wordpress/wp-content
	  type: Directory
	name: wp-content-vol
  - hostPath:
	  path: /srv/container-data/wordpress/db
	  type: Directory
	name: db-vol
status: {}
----
<.> The `kind` helps a lot to typify the artifact. So really careful around it
<.> By changing these values you can then give a name that you see when you do
a `podman ps`
<.> And this is a great way to abstracta away configuration values, further down
is the contents of such as `configMapRef`
<.> You can point to the containers paths that need to be persisted through a
bind with the host
<.> Lastly you have your volume definition

[source, yml]
.wordpress-configmap.yml
----
apiVersion: v1
kind: ConfigMap
metadata:
	name: wordpress-env
data:
	MARIADB_ROOT_PASSWORD: "MyRewtPassword"
	MARIADB_DATABASE: wordpress
	MARIADB_USER: wordpress
	MARIADB_PASSWORD: "WordPressPassword"
	WORDPRESS_DB_HOST: wordpress-db
	WORDPRESS_DB_NAME: wordpress
	WORDPRESS_DB_USER: wordpress
	WORDPRESS_DB_PASSWORD: "WordPressPassword"
----

And now you can easily pipe all of these types of files to a `kube` file, by
creating such a kube like so:

[source, kube]
----
[Install]
WantedBy=default.target

[Unit]

[Kube]
Yaml=/etc/containers/systemd/wordpress-pod.yml <.>
ConfigMap=/etc/containers/systemd/wordpress-configmap.yml <.>
PublishPort=80:80 <.>
----
<.> You can literally set up your whole architecture and point to it
<.> Then we need to manually point to the config file, otherwise this won't be
recognized
<.> And then we need to also establish what port we are going to publish

**This will spit out a whole systemd unit file with the pod**. At once.

If you stop the pod, if you restart it. It will actually destroy the pod, and bring
back a new instance, which means that all references for images for example, will
pull the latest version from the respective repos (so it's an auto-update or well
sleek way to auto-update your pod). **If you don't want that, then you should
tag your container so that you use a specific version not `latest`**

- Need to change the configuration? Just change your configuration file, and
restart the pod, that's it BROTHER.

=== Quadlet

_Extra:_ Most projects come with a `docker-compose` file, many DevOps will grab
that, read it, translate it to pods, which sometimes come with their own challenge
in mind, so guestimates are a thing.

Once the pod is created, then the `kube` generation can be run.

There's this new `[Pod]` unit, a new format that apparently is the native podman
way of dealing with `docker-compose`.

- Create a `.pod` file
	- `hx sql.pod`

````
[Pod]
PodName=forgejo
PublishPort=3000:3000
PublishPort=222:22
````

_Note:_ A nice thing about keeping config files, parameters, conventions in place,
is that when new tools, or similar tools come into the mix, you reuse a lot of the
same concepts and ideas, which makes it way more intuitive to understand what's
going on or how to use tools and configure them.

And now, based on the conventions used by Quadlets. It looks as though inside
your `.container` file you should be able to attach it to a pod with:

````
[Container]
...
Pod=forgejo

[Service]
...

[Install]
....
````
Things are stitched together based on all the different files with conventions and
the tool.

[IMPORTANT]
====
Why when using podman you need to fully qualify the image name? Example:
`Image=registry.redhat.io/rhel9/mysql-80`. Because podman makes no assumptions
as to from where you want to pull an image, `docker` **DOES**. If you don't specifiy
the registry, podman will ask "From which registry will you get this?"
====

.mysql.container
````
[Container]
Image=registry.redhat.io/rhel9/mysql-80
Environment=MYSQL_ROOT_PASSWORD=forgejo
Environment=MYSQL_USER=forgejo
Environment=MYSQL_PASSWORD=forgejo
Environment=MYSQL_DATABASE=forgejo
Pod=forgejo
````

How do you define volumes with Quadlets?

_Question:_ How can we centralize all definitions? Maybe with a Pod?

Host Path in the `.container` file Easily:

`Volume=/mysql:/var/lib/mysql`

So the way you would dump your files to the respective paths would be something
like this:

- With files that look like this:
	- forgejo-data.volume
	- forgejo.container
	- forgejo.network
	- forgejo.pod
	- mysql.container
- You would run: `sudo cp forgejo* /etc/containers/systemd`
- And then you need to copy the specific container into: `sudo cp mysql.container /etc/containers/systemd/``
- `sudo systemctl daemon-reload`

Now of course, things cannot work at all, and the journal entry helps not at all.

So you have a tool that helps running a dry run, and it outputs any errors it founds
with what you tried to setup:

`sudo /usr/libexec/podman/quadlet --dryrun`

The video failed, it seems and the solution seems to be that when you are declaring
`Pod=forgejo` you actually have to suffix it like this: `Pod=forgejo.pod`. On
all containers you are attaching to a pod, you should reference it like that.

And then it didn't work entirely, but 95% of the way there, because the service
at least was created correctly.
