= Notes

Notes taken from:

Vue - The Complete Guide (incl. Router & Composition API) - Udemy

== Section 1: Getting Started

=== What is "Vue.js"

_Note:_ Apparently we are at Vue 3. Vue 2 was released some time ago and then
things changed.

_Vue.js (Vue) is a JavaScript framework that makes building interactive and reactive
web frontends (= browser-side web applications) easier.

"JavaScript" => A programming language that is supported by all browsers. It allows
to manipulate the already-running page and hence provide richer user experiences.

"framework" => This is a third-party library that exposes utility functionalities
AND a "set of rules" (a clear guidence) on how to build your JavaScript application.
It gives you a clear idea and structure of how to write your application code, so it's
utility functions plus the rules.

"reactive" => The idea is that we want to give the user a modern look and feel.
Most of the time we are imitating mobile app UI/UX.

"web frontends" => With javascript we control what the user sees. Vue helps us
build javascript driven interfaces. It's all about the browser side code.

**Why use Vue?**

- Let's talk about mobile applications. They are really responsive, they are snappy,
smooth animations. It all feels like one "unit". Mobile apps and desktop apps
feel very reactive. We don't have to wait for html getting downloaded and rendering.

The only thing that might take time is data loading.

_In a traditional web page, we always waiting, it's a client-server model. Request
and response_. **But JavaScript can help us circumvent this**. And that is by
manipulating the DOM of the browser. The modern paradigm is always: We do a request
ONCE, and then everything else gets changed in the browser.

- Technically, just javascript can be used without frameworks.
	- But you have to write all code on your own (re-invent the wheel)
	- You might write suboptimal code or introduce errors & bugs
	- Working in a team might be harder because not everyone knows your structure
	and "code philosophy"
	- So frameworks try to bridge that gap, to focus more on business requirements,
	and features that help you solve the problem you are analyzing

=== Different Ways of Using Vue

We can use Vue in two main ways.

- To control parts of an HTML page, so that it's more interactive and responsive
	- Chat overlay, pieces of HTML (we don't have to use Vue for everything on a
	page if we don't need interactive elements)
	- We can build "Widgets" so that parts of a page can be controlled by Vue 

- We can also use Vue to control **everything**. This is the SPA approach. So
no markup is sent on the first request/render, but all the javascript necessary
for the bootstrapping and working of the app.

**We will start with the widget approach for simplicity's case**.

[IMPORTANT]
====
It's not about "the better approach". Move away from Dogma, each problem, will require
either one of the approaches to using Vue.
====

=== Exploring Vue Alternatives

Vue => Complete component-based UI framework, includes most core features for
modern web applications. A bit less popular than React & Angular.

Reach.js => Alternative to Vue. It's officially a library. Lean and focused
component-based UI library. Certain features (e.g. routing) are added via community
packages. (Vue has everyting built in, e.g., routing)

Angular => Complete component-based UI framework, packed with features. Uses TypeScript.
Can be overkill for smaller projects. (Big in Enterprise, and it's TypeScript-based)

In general all three are very popular and used alot. If you want to switch to a
different alternative, switching is easier once you know **one framework**. The
core concepts and paradigms are interchangable

=== Building A First App With Just JavaScript

There will be course resources that can be downloaded. The recommended editor
is `VS Code`. And of course, there are Vue extensions for it.

We will first start by writing vanilla code, to then appreciate actual Vue code.

Thje `gs-1` folder has 3 files:

- app.js
- index.html
- style.css

With just javascript we want to code a simple Todo app.

It doesn't react at all. So we need access to the markup's button, input, list

[source, html]
====
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>A First App</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <div id="app">
      <div>
        <label for="goal">Goal</label>
        <input type="text" id="goal" />
        <button>Add Goal</button>
      </div>
      <ul>
        <li>Test</li>
      </ul>
    </div>
    <script src="app.js"></script>
  </body>
</html>

====

[source, js]
====
const buttonEl = document.querySelector('button'); <.>
const inputEl = document.querySelector('input');
const listEl = document.querySelector('ul');

function addGoal() {
    const enteredValue = inputEl.value;
    const listItemEl = document.createElement('li');
    listItemEl.textContent = enteredValue;
    listEl.appendChild(listItemEl); <.>
    inputEl.value = ''; <.>
}

buttonEl.addEventListener('click', addGoal); <.>
====
<.> With vanilla javascript this is the pattern. You have to select all the
elements that are living in the markup file, you use selectors for that.
<.> And you can them programatically add new markup elements, or change properties
that after the execution "look reactive", without a page reload
<.> This is a QoL type of change, so that after you input the goal to add to the list,
then the input is cleared (so you add something new and don't have to delete yourself)
<.> And this is also another really common pattern, you will attach callbacks to
different functions that are triggered on all sorts of interactions with the UI
elements (this idea is still used in the frameworks, albeit, in more elegant and
declarative ways)

=== Re-building the App with Vue

You can import vue directly into an html by doing this:

````
<script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js"></script> 
````

(The course has a note that the import changes, because it used to be something
else)

_In order to switch to vue, first, comment the `app.js`_.

That way the code won't have any effect now on markup interactions.

The course makes a remark: The docs are there to help you, and are extremely useful.

https://vuejs.org/guide/quick-start.html

In there you can see many ways of installing/setting up Vue. However, for our purposes
and also just to know this, the easiest way to start interfacing with it, is by
importing it into your markup through a CDN.

You should import it like this:

````
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>A First App</title>
  <link rel="stylesheet" href="styles.css" />
</head>

<body>
  <div id="app">
    <div>
      <label for="goal">Goal</label>
      <input type="text" id="goal" />
      <button>Add Goal</button>
    </div>
    <ul>
      <li>Test</li>
    </ul>
  </div>
  <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js"></script>
  <script src="app.js"></script>
</body>

</html>
````

_Before you `.js` script.

Now, we can access vue's functions.

Let's get this something out the way:

[IMPORTANT]
====
The vanilla way is an **imperative** approach. We literally declare every single
thing manually. But by using something such as `Vue` we switch to a **declarative
approach**, we declare the inputs/base components, and then let Vue figure out what
to do with it, by leveraging its own functions and pre-conceptions.
====

After we have imported Vue, we can then add "directives" that then tie into javascript
code:

[source, html]
====
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>A First App</title>
  <link rel="stylesheet" href="styles.css" />
</head>

<body>
  <div id="app">
    <div>
      <label for="goal">Goal</label>
      <input type="text" id="goal" v-model="enteredValue" /> <.>
      <button v-on:click="addGoal">Add Goal</button> <.>
    </div>
    <ul>
      <li v-for="goal in goals">{{ goal }}</li> <.>
    </ul>
  </div>
  <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js"></script>
  <script src="app.js"></script>
</body>

</html>
====
<.> If you want to hook into an input and bind its value so that then the model
(backend code) is constantly receiving changes, you'd use the `v-model` directive.
<.> When hooking into UI element's events, you'd use `v-on:click="function"`
<.> And lastly if you want to iteratively render something `v-for="..."`

As you can see we are using directives that will tell Vue what we want, but he
will do the heavy lifting in the background.

[source, js]
====
Vue.createApp({ <.>
    data() { <.>
        return {
            goals: [],
            enteredValue: ''
        };
    },
    methods: {
        addGoal() { <.>
            this.goals.push(this.enteredValue); <.>
            this.enteredValue = '';
        }
    }
}).mount('#app'); <.>
====
<.> We will feed a whole object to `Vue.createApp` in there all the data of
the screen will respond to a specific property of the object, and then another
property will hold methods that then will more than likely all act as callbacks
<.> This is "by convention" always `data()`, inside you would return all the
values you would need to be tied to UI element's values
<.> This is but one method that will react to some UI element event
<.> As you can see this is referring to `goals` as in the ones that are under
`data()`, Vue does a bit of magic here, but the convention is that if you set
`this.xxx` it will trace back to the bound data that is right now the "Model" of
the screen.
<.> Lastly, we need to tell vue where is the markup that it needs to watch and
then manipulate, luckily the HTML has a selector `id="app"`, by calling `mount("#app")`
which is a CSS selector syntax, vue will find the markup, and just after setting this
we would have the same behavior that we created with vanilla javascript.

=== Vue vs "Vanilla JavaScript" (just JavaScript)

There's a lot of magic happening. But the key thing: **With Vue we define the end
result, and with the features offered by it, data and logic and UI end up connected**.

Vue allows to build any kind of app, by following this "declarative-result". Which
allows us to declare the steps, not the "how we get there".

The bigger the applications, with just JavaScript it will grow just more and more
in terms of maintenance, whilst with something like Vue, things can still remain
lean, but evolvable and maintainable. (And hopefully less-error-prone)

=== Setting Up The Course Development Environment

- VS Code
  - Dark Theme
- Shortcut
  - Format document => Ctrl + K, Ctrl + F **really important**
  - If this isn't working, install the Prettier format extension
    - And then on settings make sure prettier-vscode is selected
      - This is the baseline to have more readable code

=== Course Outline & What's In the Course

Basics => No prior Vue knowledge. Syntax, templates, directives, data, computed
properties, watchers (Foundation)
Intermediate => Components, component communication, Behind the Scenes, Forms,
Http, Routing, Animations
Advanced => Vuex, Authentication, Deployment & Optimizations, Composition API,
Re-using Code

- Dozens of Small Demos / Mini Projects
- Multiple bigger Course Projects
- Assignments, Challenges

=== How To Get The Most Out Of This Course

- Watch the Videos: At your pace
- Code along: Try things on your own (code along, code ahead)
- Repeat Concepts - Repeat videos or sections if unclear
  - All concepts should come together through a project
- Google, Stackoverflow: Search the web, on threads with the solutions. However if
you are stuck => Q&A Section. You will learn more if you help fellow students.
(Forum for discussion)
- Facing an Error? - Compare course code to your own
- Code snapshots => Can be used for debugging, troubleshooting.

== Section 2: Basics & Core Concepts - DOM Interaction with Vue
