= Notes

Notes taken from:

Vue - The Complete Guide (incl. Router & Composition API) - Udemy

== Section 1: Getting Started

=== What is "Vue.js"

_Note:_ Apparently we are at Vue 3. Vue 2 was released some time ago and then
things changed.

_Vue.js (Vue) is a JavaScript framework that makes building interactive and reactive
web frontends (= browser-side web applications) easier.

"JavaScript" => A programming language that is supported by all browsers. It allows
to manipulate the already-running page and hence provide richer user experiences.

"framework" => This is a third-party library that exposes utility functionalities
AND a "set of rules" (a clear guidence) on how to build your JavaScript application.
It gives you a clear idea and structure of how to write your application code, so it's
utility functions plus the rules.

"reactive" => The idea is that we want to give the user a modern look and feel.
Most of the time we are imitating mobile app UI/UX.

"web frontends" => With javascript we control what the user sees. Vue helps us
build javascript driven interfaces. It's all about the browser side code.

**Why use Vue?**

- Let's talk about mobile applications. They are really responsive, they are snappy,
smooth animations. It all feels like one "unit". Mobile apps and desktop apps
feel very reactive. We don't have to wait for html getting downloaded and rendering.

The only thing that might take time is data loading.

_In a traditional web page, we always waiting, it's a client-server model. Request
and response_. **But JavaScript can help us circumvent this**. And that is by
manipulating the DOM of the browser. The modern paradigm is always: We do a request
ONCE, and then everything else gets changed in the browser.

- Technically, just javascript can be used without frameworks.
	- But you have to write all code on your own (re-invent the wheel)
	- You might write suboptimal code or introduce errors & bugs
	- Working in a team might be harder because not everyone knows your structure
	and "code philosophy"
	- So frameworks try to bridge that gap, to focus more on business requirements,
	and features that help you solve the problem you are analyzing

=== Different Ways of Using Vue

We can use Vue in two main ways.

- To control parts of an HTML page, so that it's more interactive and responsive
	- Chat overlay, pieces of HTML (we don't have to use Vue for everything on a
	page if we don't need interactive elements)
	- We can build "Widgets" so that parts of a page can be controlled by Vue 

- We can also use Vue to control **everything**. This is the SPA approach. So
no markup is sent on the first request/render, but all the javascript necessary
for the bootstrapping and working of the app.

**We will start with the widget approach for simplicity's case**.

[IMPORTANT]
====
It's not about "the better approach". Move away from Dogma, each problem, will require
either one of the approaches to using Vue.
====

=== Exploring Vue Alternatives

Vue => Complete component-based UI framework, includes most core features for
modern web applications. A bit less popular than React & Angular.

Reach.js => Alternative to Vue. It's officially a library. Lean and focused
component-based UI library. Certain features (e.g. routing) are added via community
packages. (Vue has everyting built in, e.g., routing)

Angular => Complete component-based UI framework, packed with features. Uses TypeScript.
Can be overkill for smaller projects. (Big in Enterprise, and it's TypeScript-based)

In general all three are very popular and used alot. If you want to switch to a
different alternative, switching is easier once you know **one framework**. The
core concepts and paradigms are interchangable

=== Building A First App With Just JavaScript

There will be course resources that can be downloaded. The recommended editor
is `VS Code`. And of course, there are Vue extensions for it.

We will first start by writing vanilla code, to then appreciate actual Vue code.

Thje `gs-1` folder has 3 files:

- app.js
- index.html
- style.css

With just javascript we want to code a simple Todo app.

It doesn't react at all. So we need access to the markup's button, input, list

[source, html]
====
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>A First App</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <div id="app">
      <div>
        <label for="goal">Goal</label>
        <input type="text" id="goal" />
        <button>Add Goal</button>
      </div>
      <ul>
        <li>Test</li>
      </ul>
    </div>
    <script src="app.js"></script>
  </body>
</html>

====

[source, js]
====
const buttonEl = document.querySelector('button'); <.>
const inputEl = document.querySelector('input');
const listEl = document.querySelector('ul');

function addGoal() {
    const enteredValue = inputEl.value;
    const listItemEl = document.createElement('li');
    listItemEl.textContent = enteredValue;
    listEl.appendChild(listItemEl); <.>
    inputEl.value = ''; <.>
}

buttonEl.addEventListener('click', addGoal); <.>
====
<.> With vanilla javascript this is the pattern. You have to select all the
elements that are living in the markup file, you use selectors for that.
<.> And you can them programatically add new markup elements, or change properties
that after the execution "look reactive", without a page reload
<.> This is a QoL type of change, so that after you input the goal to add to the list,
then the input is cleared (so you add something new and don't have to delete yourself)
<.> And this is also another really common pattern, you will attach callbacks to
different functions that are triggered on all sorts of interactions with the UI
elements (this idea is still used in the frameworks, albeit, in more elegant and
declarative ways)

=== Re-building the App with Vue

You can import vue directly into an html by doing this:

````
<script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js"></script> 
````

(The course has a note that the import changes, because it used to be something
else)

_In order to switch to vue, first, comment the `app.js`_.

That way the code won't have any effect now on markup interactions.

The course makes a remark: The docs are there to help you, and are extremely useful.

https://vuejs.org/guide/quick-start.html

In there you can see many ways of installing/setting up Vue. However, for our purposes
and also just to know this, the easiest way to start interfacing with it, is by
importing it into your markup through a CDN.

You should import it like this:

````
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>A First App</title>
  <link rel="stylesheet" href="styles.css" />
</head>

<body>
  <div id="app">
    <div>
      <label for="goal">Goal</label>
      <input type="text" id="goal" />
      <button>Add Goal</button>
    </div>
    <ul>
      <li>Test</li>
    </ul>
  </div>
  <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js"></script>
  <script src="app.js"></script>
</body>

</html>
````

_Before you `.js` script.

Now, we can access vue's functions.

Let's get this something out the way:

[IMPORTANT]
====
The vanilla way is an **imperative** approach. We literally declare every single
thing manually. But by using something such as `Vue` we switch to a **declarative
approach**, we declare the inputs/base components, and then let Vue figure out what
to do with it, by leveraging its own functions and pre-conceptions.
====

After we have imported Vue, we can then add "directives" that then tie into javascript
code:

[source, html]
====
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>A First App</title>
  <link rel="stylesheet" href="styles.css" />
</head>

<body>
  <div id="app">
    <div>
      <label for="goal">Goal</label>
      <input type="text" id="goal" v-model="enteredValue" /> <.>
      <button v-on:click="addGoal">Add Goal</button> <.>
    </div>
    <ul>
      <li v-for="goal in goals">{{ goal }}</li> <.>
    </ul>
  </div>
  <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js"></script>
  <script src="app.js"></script>
</body>

</html>
====
<.> If you want to hook into an input and bind its value so that then the model
(backend code) is constantly receiving changes, you'd use the `v-model` directive.
<.> When hooking into UI element's events, you'd use `v-on:click="function"`
<.> And lastly if you want to iteratively render something `v-for="..."`

As you can see we are using directives that will tell Vue what we want, but he
will do the heavy lifting in the background.

[source, js]
====
Vue.createApp({ <.>
    data() { <.>
        return {
            goals: [],
            enteredValue: ''
        };
    },
    methods: {
        addGoal() { <.>
            this.goals.push(this.enteredValue); <.>
            this.enteredValue = '';
        }
    }
}).mount('#app'); <.>
====
<.> We will feed a whole object to `Vue.createApp` in there all the data of
the screen will respond to a specific property of the object, and then another
property will hold methods that then will more than likely all act as callbacks
<.> This is "by convention" always `data()`, inside you would return all the
values you would need to be tied to UI element's values
<.> This is but one method that will react to some UI element event
<.> As you can see this is referring to `goals` as in the ones that are under
`data()`, Vue does a bit of magic here, but the convention is that if you set
`this.xxx` it will trace back to the bound data that is right now the "Model" of
the screen.
<.> Lastly, we need to tell vue where is the markup that it needs to watch and
then manipulate, luckily the HTML has a selector `id="app"`, by calling `mount("#app")`
which is a CSS selector syntax, vue will find the markup, and just after setting this
we would have the same behavior that we created with vanilla javascript.

=== Vue vs "Vanilla JavaScript" (just JavaScript)

There's a lot of magic happening. But the key thing: **With Vue we define the end
result, and with the features offered by it, data and logic and UI end up connected**.

Vue allows to build any kind of app, by following this "declarative-result". Which
allows us to declare the steps, not the "how we get there".

The bigger the applications, with just JavaScript it will grow just more and more
in terms of maintenance, whilst with something like Vue, things can still remain
lean, but evolvable and maintainable. (And hopefully less-error-prone)

=== Setting Up The Course Development Environment

- VS Code
  - Dark Theme
- Shortcut
  - Format document => Ctrl + K, Ctrl + F **really important**
  - If this isn't working, install the Prettier format extension
    - And then on settings make sure prettier-vscode is selected
      - This is the baseline to have more readable code

=== Course Outline & What's In the Course

Basics => No prior Vue knowledge. Syntax, templates, directives, data, computed
properties, watchers (Foundation)
Intermediate => Components, component communication, Behind the Scenes, Forms,
Http, Routing, Animations
Advanced => Vuex, Authentication, Deployment & Optimizations, Composition API,
Re-using Code

- Dozens of Small Demos / Mini Projects
- Multiple bigger Course Projects
- Assignments, Challenges

=== How To Get The Most Out Of This Course

- Watch the Videos: At your pace
- Code along: Try things on your own (code along, code ahead)
- Repeat Concepts - Repeat videos or sections if unclear
  - All concepts should come together through a project
- Google, Stackoverflow: Search the web, on threads with the solutions. However if
you are stuck => Q&A Section. You will learn more if you help fellow students.
(Forum for discussion)
- Facing an Error? - Compare course code to your own
- Code snapshots => Can be used for debugging, troubleshooting.

== Section 2: Basics & Core Concepts - DOM Interaction with Vue

=== Module Introduction

The Essentials:

- How does Vue interact with HTML? - Templates
- How do you output dynamic content?
- How do you react to User Input?

=== Creating and Connecting Vue App Instances

Don't forget for the import:

````
<script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script> 
````

We are going to use a basic starter "project". Downloaded from the course. It
has basic css, and html and js files.

We already mentioned this, we need to mark a part of the page, that vue is going
to attach to. (You need to control that with vue app).

[source, html]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vue Basics</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="styles.css" />
    <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script> 
    <script src="app.js" defer></script>
  </head>
  <body id="app">
    <header>
      <h1>Vue Course Goals</h1>
    </header>
    <section id="user-goal"> <.>
      <h2>My Course Goal</h2>
      <p></p>
    </section>
  </body>
</html>
----
<.> We want to attach to this specific section of the markup, so we need to be
sure to make usage of `id`, this is the best candidate for marking a section to
attach Vue to.

And then we can start writing Vue code:

[source, js]
----
const app = Vue.createApp({ <.>
    data() { <.>
        return {
            courseGoal: 'Finish the course and learn Vue!' <.>
        };
    }
});

app.mount('#user-goal'); <.>
----
<.> Notice how we can create an app object, with `Vue.createApp()`, and this
can be saved under a reference variable.
<.> The pre-defined `data` property, should be a function that **always returns an
object**
<.> And inside of there we can define all sorts of properties and what type of properties
they are based on our use case/need/goal. That way they can be bound to UI elements
and things.
<.> The `app` object needs to be mounted somewhere, and you do that by calling `mount()`
and inside feeding in the form of a _css selector_ the metadata that will help
find the element we want to mount Vue to.

=== Interpolation and Data Binding

[IMPORTANT]
====
The import of Vue tip from the course is **mega important**. If you import vue
"wrongly" none of the reactivity nor anything will work as expected. So be sure
to import vue correctly.
====

And, so lastly, the final piece of the puzzle to then start displaying whatever
vue has as state, you can make usage of special syntax that only when Vue is attached
will behave in a certain way:

````
<section id="user-goal">
  <h2>My Course Goal</h2>
  <p>{{ courseGoal }}</p>
</section>
````
When you use double curly braces and inside put a name (that should refer to a
property that is under `data()`), then Vue takes care of injecting the value there
and rendering in HTML. Without vue attached to the page **you will see literally
as a string `{{ courseGoal }}`, but thanks to Vue, the module itself, you can
see magic happening. Things are scored through javascript, and rendered on the view.

**Interpolation** => Is the concept that helps declare values inside the vue app
object, and that then gets rendered in some UI component.

**Note:** Unless you are editing the HTML that is bound to the Vue app, you won't
get the "swapping" of the property value, **bear that in mind, it's key**.

Interpolation and Vue attaching is the takeaway from all of this, this is the base
concept that will allow you to bring together whatever it is that Vue offers for
reactivity and responsive UIs.

=== Binding Attributes with the "v-bind" Directive

You don't always want to use interpolation for binding data.

Let's say you want links, (you'd use an anchor `<a href...`). The link could be
hardcoded. However, we could also store the value in the vue state. And this will
allow us to make things dynamic.

````
const app = Vue.createApp({
    data() {
        return {
            courseGoal: 'Finish the course and learn Vue!',
            vueLink: 'https://vuejs.org/'
        };
    }
});

app.mount('#user-goal');
````

[source, html]
----
<section id="user-goal">
  <h2>My Course Goal</h2>
  <p>{{ courseGoal }}</p>
  <p>Learn more <a href="{{ vueLink }}">about Vue</a></p> <.>
</section>
----
<.> If you want to bind state values to properties of markup. You can't use the
double curly braces, it will be rendered as the literal string.

And so, we will have to add a specific directive. An instruction that will be
picked up by Vue, so, in this instance to set the value of an attribute dynamically,
you can write:

````
<p>Learn more <a v-bind:href="vueLink">about Vue</a></p> <.>
````
<.> In essence you have to prefix with `v-bind` and then write after a colon,
the name of the attribute you want to bind to, the value then inside will reference
directly the vue's _data property name_.

This is another key concept to know when it comes to Vue, inside of html markup
you'd use double curly braces, and when trying to bind to attributes of html
elements, you would use `v-bind`

=== Understanding "methods" in Vue Apps

For outputting and managing data, Vue offsets the responsibility to the HTML code.

Now, let's add a new requirement:

- Roll a dice, and then render based on the result a "goal".

For this, we have to code some logic. And now leverage `methods`

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            courseGoal: 'Finish the course and learn Vue!',
            vueLink: 'https://vuejs.org/'
        };
    },
    methods: { <.>
        outputGoal() { <.>
            const randomNumber = Math.random();
            if (randomNumber < 0.5) {
                return 'Learn Vue!';
            }

            return 'Master Vue!';
        }
    }
});

app.mount('#user-goal');
----
<.> Another reserved name is `methods`. This receives an object that inside will
hold different functions.
<.> In this instance we are adding a function that will calculate a goal based on
a random number

We can then actually call this method from the `HTML`

````
<section id="user-goal">
  <h2>My Course Goal</h2>
  <p>{{ outputGoal() }}</p>
  <p>Learn more <a v-bind:href="vueLink">about Vue</a></p>
</section>
````
When you use string interpolation, inside you can technically run any JS code,
the function is registered under the vue object, so this gets resolved and
executed correctly, however you _could_ also just write code _in-line_.

And if you keep on reloading the page, you will se how the goal text changes,
due to the logic that calculates a random number on each iteration. This is the
base concept to understand so that later down the line you can build tons of
dynamic pages based on logic, binding and string interpolation.

=== Working with Data inside of a Vue App

It all depends on what you're building, and the goal. However, let's talk about
how to register Vue data, and how to leverage it.

By leveraging Vue `data()`, you can see how magic can happen:

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            courseGoalA: 'Finish the course and learn Vue!', <.>
            courseGoalB: 'Master Vue and build amazing apps!',
            vueLink: 'https://vuejs.org/'
        };
    },
    methods: {
        outputGoal() {
            const randomNumber = Math.random();
            if (randomNumber < 0.5) {
                return this.courseGoalA; <.>
            }

            return this.courseGoalB;
        }
    }
});

app.mount('#user-goal');
----
<.> You can register some extra properties, in this instance for saving goals.
<.> And you can then leverage `this` to reference those state properties by name.
This might look super strange, since `this` is a really tricky reserved name in
javascript

Vue, will always take all the properties under `data()` and it will register them
(alongside the methods in `methods`) as part of a global state. **This** is what
enables us having the ability to call them with `this` and also for the markup
to reference both methods and properties directly, regardless of interpolation or
data binding constraints.

=== Outputting Raw HTML Content with v-html

There's another directive that is really useful. And that comes when you have
scenarios in which you want to render structured HTML code. If you use html
elements in a string and you output with interpolation, then for security measures
it will not process the HTML. However, you can intentionally turn on that
processing: `v-bind`

````
<p v-html="outputGoal()"></p>
````
So you add it as an attribute, and then call any of the methods or properties that
the vue object is holding together.

The use cases for this html rendering switch are not _that many_, remember that it's
for security, it protects you against cross-site scripting. But if you ever need
to pass dynamically rendered HTML, `v-html` is your friend.

=== A First Summary

The moment we attach vue to some specific section, all the children also can get
manipulated. And when you attach vue to a section, you get access to special features
that javascript reads and then acts on. Lots of behavior under the scenes is computed,
but you only care about **declaring** what you want the behavior to be.

You _pass an object to your vue app_, and this object configures the vue app.

- data
- methods

These are all really important components of a vue object. The references across
methods and properties can be referred as `this`. The approach that Vue takes is
**_A declarative approach_**. Vue does all the magic behind the scenes, it updates
real DOM, it changes things around, _on our behalf_. As developers we define the
**final picture**, we architect based on behavior, we declare goals and those get
executed.

=== Assignment 1: Time to Practice: Data Binding

Need to create a Vue instance, use all the learned things so far.

Tasks:

- Output name
- Output age

Use vue.js. Save as properties, and output them from there.

- Output age + 5
- Output random number, and this needs to be outputted two times, one with a method
and another one without a method
- Output an image, go to Google, search for some random free to use image URL and
output the image (not throwing the URL, store that URL in the vue instance and
fetch it from there and output with vue syntax)
- Setting an `input` value with the _value attribute_

[source, html]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vue Basics</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="styles.css" />
    <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script> <.>
    <script src="app.js" defer></script>
  </head>
  <body>
    <section id="assignment">
      <!-- 1) Output your name -->
      <h2>{{ name }}</h2>
      <!-- 2) Output your age -->
      <p>{{ age }}</p>
      <!-- 3) Output your age + 5 -->
      <p>{{ age + 5 }}</p> <.>
      <!-- 4) Output a random number (0 to 1) -->
      <p>Favorite Number: {{ getRandomNumber() }}</p>
      <p>Favorite Number: {{ Math.random() }}</p>
      <div>
        <!-- 5) Display some image you found via Google -->
        <img v-bind:src="imageUrl" /> <.>
      </div>
      <!-- 6) Prepopulate the input field with your name via the "value" attribute -->
      <input v-bind:value="inputText" type="text" />
    </section>
  </body>
</html>
----
<.> Don't forget that the import of the course is "wrong". So this has to be changed.
<.> This evaluates javascript, it can just be a property reference or in-line
code execution, hence this works just fine.
<.> Remember that if you want to dynamically control attributes of HTML elements,
you have to use `v-bind:<attribute>`. That is key, after you declare the attribute
like that, you can safely execute js code or call methods or reference a property.

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            name: 'Diego',
            age: 26,
            imageUrl: 'https://future-architect.github.io/images/2025/20251022a/image.png',
            inputText: 'YO'
        }
    },
    methods: {
        getRandomNumber() {
            return Math.random();
        }
    }
});

app.mount('#assignment'); <.>
----
<.> Decided to do it like this for order purposes, and also because I noticed that
this element was encasing all the html elements for the assignment.

[IMPORTANT]
====
You can declare multiple "vue apps". Don't think it's just **one** mount that
works. But be sure to decide a good css selector. An id (`#id`) is probably the
best candidate, they have to be unique, otherwise Vue might get confused.
====

