= Notes

Notes taken from:

Vue - The Complete Guide (incl. Router & Composition API) - Udemy

== Section 1: Getting Started

=== What is "Vue.js"

_Note:_ Apparently we are at Vue 3. Vue 2 was released some time ago and then
things changed.

_Vue.js (Vue) is a JavaScript framework that makes building interactive and reactive
web frontends (= browser-side web applications) easier.

"JavaScript" => A programming language that is supported by all browsers. It allows
to manipulate the already-running page and hence provide richer user experiences.

"framework" => This is a third-party library that exposes utility functionalities
AND a "set of rules" (a clear guidence) on how to build your JavaScript application.
It gives you a clear idea and structure of how to write your application code, so it's
utility functions plus the rules.

"reactive" => The idea is that we want to give the user a modern look and feel.
Most of the time we are imitating mobile app UI/UX.

"web frontends" => With javascript we control what the user sees. Vue helps us
build javascript driven interfaces. It's all about the browser side code.

**Why use Vue?**

- Let's talk about mobile applications. They are really responsive, they are snappy,
smooth animations. It all feels like one "unit". Mobile apps and desktop apps
feel very reactive. We don't have to wait for html getting downloaded and rendering.

The only thing that might take time is data loading.

_In a traditional web page, we always waiting, it's a client-server model. Request
and response_. **But JavaScript can help us circumvent this**. And that is by
manipulating the DOM of the browser. The modern paradigm is always: We do a request
ONCE, and then everything else gets changed in the browser.

- Technically, just javascript can be used without frameworks.
	- But you have to write all code on your own (re-invent the wheel)
	- You might write suboptimal code or introduce errors & bugs
	- Working in a team might be harder because not everyone knows your structure
	and "code philosophy"
	- So frameworks try to bridge that gap, to focus more on business requirements,
	and features that help you solve the problem you are analyzing

=== Different Ways of Using Vue

We can use Vue in two main ways.

- To control parts of an HTML page, so that it's more interactive and responsive
	- Chat overlay, pieces of HTML (we don't have to use Vue for everything on a
	page if we don't need interactive elements)
	- We can build "Widgets" so that parts of a page can be controlled by Vue 

- We can also use Vue to control **everything**. This is the SPA approach. So
no markup is sent on the first request/render, but all the javascript necessary
for the bootstrapping and working of the app.

**We will start with the widget approach for simplicity's case**.

[IMPORTANT]
====
It's not about "the better approach". Move away from Dogma, each problem, will require
either one of the approaches to using Vue.
====

=== Exploring Vue Alternatives

Vue => Complete component-based UI framework, includes most core features for
modern web applications. A bit less popular than React & Angular.

Reach.js => Alternative to Vue. It's officially a library. Lean and focused
component-based UI library. Certain features (e.g. routing) are added via community
packages. (Vue has everyting built in, e.g., routing)

Angular => Complete component-based UI framework, packed with features. Uses TypeScript.
Can be overkill for smaller projects. (Big in Enterprise, and it's TypeScript-based)

In general all three are very popular and used alot. If you want to switch to a
different alternative, switching is easier once you know **one framework**. The
core concepts and paradigms are interchangable

=== Building A First App With Just JavaScript

There will be course resources that can be downloaded. The recommended editor
is `VS Code`. And of course, there are Vue extensions for it.

We will first start by writing vanilla code, to then appreciate actual Vue code.

Thje `gs-1` folder has 3 files:

- app.js
- index.html
- style.css

With just javascript we want to code a simple Todo app.

It doesn't react at all. So we need access to the markup's button, input, list

[source, html]
====
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>A First App</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <div id="app">
      <div>
        <label for="goal">Goal</label>
        <input type="text" id="goal" />
        <button>Add Goal</button>
      </div>
      <ul>
        <li>Test</li>
      </ul>
    </div>
    <script src="app.js"></script>
  </body>
</html>

====

[source, js]
====
const buttonEl = document.querySelector('button'); <.>
const inputEl = document.querySelector('input');
const listEl = document.querySelector('ul');

function addGoal() {
    const enteredValue = inputEl.value;
    const listItemEl = document.createElement('li');
    listItemEl.textContent = enteredValue;
    listEl.appendChild(listItemEl); <.>
    inputEl.value = ''; <.>
}

buttonEl.addEventListener('click', addGoal); <.>
====
<.> With vanilla javascript this is the pattern. You have to select all the
elements that are living in the markup file, you use selectors for that.
<.> And you can them programatically add new markup elements, or change properties
that after the execution "look reactive", without a page reload
<.> This is a QoL type of change, so that after you input the goal to add to the list,
then the input is cleared (so you add something new and don't have to delete yourself)
<.> And this is also another really common pattern, you will attach callbacks to
different functions that are triggered on all sorts of interactions with the UI
elements (this idea is still used in the frameworks, albeit, in more elegant and
declarative ways)

=== Re-building the App with Vue

You can import vue directly into an html by doing this:

````
<script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js"></script> 
````

(The course has a note that the import changes, because it used to be something
else)

_In order to switch to vue, first, comment the `app.js`_.

That way the code won't have any effect now on markup interactions.

The course makes a remark: The docs are there to help you, and are extremely useful.

https://vuejs.org/guide/quick-start.html

In there you can see many ways of installing/setting up Vue. However, for our purposes
and also just to know this, the easiest way to start interfacing with it, is by
importing it into your markup through a CDN.

You should import it like this:

````
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>A First App</title>
  <link rel="stylesheet" href="styles.css" />
</head>

<body>
  <div id="app">
    <div>
      <label for="goal">Goal</label>
      <input type="text" id="goal" />
      <button>Add Goal</button>
    </div>
    <ul>
      <li>Test</li>
    </ul>
  </div>
  <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js"></script>
  <script src="app.js"></script>
</body>

</html>
````

_Before you `.js` script.

Now, we can access vue's functions.

Let's get this something out the way:

[IMPORTANT]
====
The vanilla way is an **imperative** approach. We literally declare every single
thing manually. But by using something such as `Vue` we switch to a **declarative
approach**, we declare the inputs/base components, and then let Vue figure out what
to do with it, by leveraging its own functions and pre-conceptions.
====

After we have imported Vue, we can then add "directives" that then tie into javascript
code:

[source, html]
====
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>A First App</title>
  <link rel="stylesheet" href="styles.css" />
</head>

<body>
  <div id="app">
    <div>
      <label for="goal">Goal</label>
      <input type="text" id="goal" v-model="enteredValue" /> <.>
      <button v-on:click="addGoal">Add Goal</button> <.>
    </div>
    <ul>
      <li v-for="goal in goals">{{ goal }}</li> <.>
    </ul>
  </div>
  <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js"></script>
  <script src="app.js"></script>
</body>

</html>
====
<.> If you want to hook into an input and bind its value so that then the model
(backend code) is constantly receiving changes, you'd use the `v-model` directive.
<.> When hooking into UI element's events, you'd use `v-on:click="function"`
<.> And lastly if you want to iteratively render something `v-for="..."`

As you can see we are using directives that will tell Vue what we want, but he
will do the heavy lifting in the background.

[source, js]
====
Vue.createApp({ <.>
    data() { <.>
        return {
            goals: [],
            enteredValue: ''
        };
    },
    methods: {
        addGoal() { <.>
            this.goals.push(this.enteredValue); <.>
            this.enteredValue = '';
        }
    }
}).mount('#app'); <.>
====
<.> We will feed a whole object to `Vue.createApp` in there all the data of
the screen will respond to a specific property of the object, and then another
property will hold methods that then will more than likely all act as callbacks
<.> This is "by convention" always `data()`, inside you would return all the
values you would need to be tied to UI element's values
<.> This is but one method that will react to some UI element event
<.> As you can see this is referring to `goals` as in the ones that are under
`data()`, Vue does a bit of magic here, but the convention is that if you set
`this.xxx` it will trace back to the bound data that is right now the "Model" of
the screen.
<.> Lastly, we need to tell vue where is the markup that it needs to watch and
then manipulate, luckily the HTML has a selector `id="app"`, by calling `mount("#app")`
which is a CSS selector syntax, vue will find the markup, and just after setting this
we would have the same behavior that we created with vanilla javascript.

=== Vue vs "Vanilla JavaScript" (just JavaScript)

There's a lot of magic happening. But the key thing: **With Vue we define the end
result, and with the features offered by it, data and logic and UI end up connected**.

Vue allows to build any kind of app, by following this "declarative-result". Which
allows us to declare the steps, not the "how we get there".

The bigger the applications, with just JavaScript it will grow just more and more
in terms of maintenance, whilst with something like Vue, things can still remain
lean, but evolvable and maintainable. (And hopefully less-error-prone)

=== Setting Up The Course Development Environment

- VS Code
  - Dark Theme
- Shortcut
  - Format document => Ctrl + K, Ctrl + F **really important**
  - If this isn't working, install the Prettier format extension
    - And then on settings make sure prettier-vscode is selected
      - This is the baseline to have more readable code

=== Course Outline & What's In the Course

Basics => No prior Vue knowledge. Syntax, templates, directives, data, computed
properties, watchers (Foundation)
Intermediate => Components, component communication, Behind the Scenes, Forms,
Http, Routing, Animations
Advanced => Vuex, Authentication, Deployment & Optimizations, Composition API,
Re-using Code

- Dozens of Small Demos / Mini Projects
- Multiple bigger Course Projects
- Assignments, Challenges

=== How To Get The Most Out Of This Course

- Watch the Videos: At your pace
- Code along: Try things on your own (code along, code ahead)
- Repeat Concepts - Repeat videos or sections if unclear
  - All concepts should come together through a project
- Google, Stackoverflow: Search the web, on threads with the solutions. However if
you are stuck => Q&A Section. You will learn more if you help fellow students.
(Forum for discussion)
- Facing an Error? - Compare course code to your own
- Code snapshots => Can be used for debugging, troubleshooting.

== Section 2: Basics & Core Concepts - DOM Interaction with Vue

=== Module Introduction

The Essentials:

- How does Vue interact with HTML? - Templates
- How do you output dynamic content?
- How do you react to User Input?

=== Creating and Connecting Vue App Instances

Don't forget for the import:

````
<script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script> 
````

We are going to use a basic starter "project". Downloaded from the course. It
has basic css, and html and js files.

We already mentioned this, we need to mark a part of the page, that vue is going
to attach to. (You need to control that with vue app).

[source, html]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vue Basics</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="styles.css" />
    <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script> 
    <script src="app.js" defer></script>
  </head>
  <body id="app">
    <header>
      <h1>Vue Course Goals</h1>
    </header>
    <section id="user-goal"> <.>
      <h2>My Course Goal</h2>
      <p></p>
    </section>
  </body>
</html>
----
<.> We want to attach to this specific section of the markup, so we need to be
sure to make usage of `id`, this is the best candidate for marking a section to
attach Vue to.

And then we can start writing Vue code:

[source, js]
----
const app = Vue.createApp({ <.>
    data() { <.>
        return {
            courseGoal: 'Finish the course and learn Vue!' <.>
        };
    }
});

app.mount('#user-goal'); <.>
----
<.> Notice how we can create an app object, with `Vue.createApp()`, and this
can be saved under a reference variable.
<.> The pre-defined `data` property, should be a function that **always returns an
object**
<.> And inside of there we can define all sorts of properties and what type of properties
they are based on our use case/need/goal. That way they can be bound to UI elements
and things.
<.> The `app` object needs to be mounted somewhere, and you do that by calling `mount()`
and inside feeding in the form of a _css selector_ the metadata that will help
find the element we want to mount Vue to.

=== Interpolation and Data Binding

[IMPORTANT]
====
The import of Vue tip from the course is **mega important**. If you import vue
"wrongly" none of the reactivity nor anything will work as expected. So be sure
to import vue correctly.
====

And, so lastly, the final piece of the puzzle to then start displaying whatever
vue has as state, you can make usage of special syntax that only when Vue is attached
will behave in a certain way:

````
<section id="user-goal">
  <h2>My Course Goal</h2>
  <p>{{ courseGoal }}</p>
</section>
````
When you use double curly braces and inside put a name (that should refer to a
property that is under `data()`), then Vue takes care of injecting the value there
and rendering in HTML. Without vue attached to the page **you will see literally
as a string `{{ courseGoal }}`, but thanks to Vue, the module itself, you can
see magic happening. Things are scored through javascript, and rendered on the view.

**Interpolation** => Is the concept that helps declare values inside the vue app
object, and that then gets rendered in some UI component.

**Note:** Unless you are editing the HTML that is bound to the Vue app, you won't
get the "swapping" of the property value, **bear that in mind, it's key**.

Interpolation and Vue attaching is the takeaway from all of this, this is the base
concept that will allow you to bring together whatever it is that Vue offers for
reactivity and responsive UIs.

=== Binding Attributes with the "v-bind" Directive

You don't always want to use interpolation for binding data.

Let's say you want links, (you'd use an anchor `<a href...`). The link could be
hardcoded. However, we could also store the value in the vue state. And this will
allow us to make things dynamic.

````
const app = Vue.createApp({
    data() {
        return {
            courseGoal: 'Finish the course and learn Vue!',
            vueLink: 'https://vuejs.org/'
        };
    }
});

app.mount('#user-goal');
````

[source, html]
----
<section id="user-goal">
  <h2>My Course Goal</h2>
  <p>{{ courseGoal }}</p>
  <p>Learn more <a href="{{ vueLink }}">about Vue</a></p> <.>
</section>
----
<.> If you want to bind state values to properties of markup. You can't use the
double curly braces, it will be rendered as the literal string.

And so, we will have to add a specific directive. An instruction that will be
picked up by Vue, so, in this instance to set the value of an attribute dynamically,
you can write:

````
<p>Learn more <a v-bind:href="vueLink">about Vue</a></p> <.>
````
<.> In essence you have to prefix with `v-bind` and then write after a colon,
the name of the attribute you want to bind to, the value then inside will reference
directly the vue's _data property name_.

This is another key concept to know when it comes to Vue, inside of html markup
you'd use double curly braces, and when trying to bind to attributes of html
elements, you would use `v-bind`

=== Understanding "methods" in Vue Apps

For outputting and managing data, Vue offsets the responsibility to the HTML code.

Now, let's add a new requirement:

- Roll a dice, and then render based on the result a "goal".

For this, we have to code some logic. And now leverage `methods`

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            courseGoal: 'Finish the course and learn Vue!',
            vueLink: 'https://vuejs.org/'
        };
    },
    methods: { <.>
        outputGoal() { <.>
            const randomNumber = Math.random();
            if (randomNumber < 0.5) {
                return 'Learn Vue!';
            }

            return 'Master Vue!';
        }
    }
});

app.mount('#user-goal');
----
<.> Another reserved name is `methods`. This receives an object that inside will
hold different functions.
<.> In this instance we are adding a function that will calculate a goal based on
a random number

We can then actually call this method from the `HTML`

````
<section id="user-goal">
  <h2>My Course Goal</h2>
  <p>{{ outputGoal() }}</p>
  <p>Learn more <a v-bind:href="vueLink">about Vue</a></p>
</section>
````
When you use string interpolation, inside you can technically run any JS code,
the function is registered under the vue object, so this gets resolved and
executed correctly, however you _could_ also just write code _in-line_.

And if you keep on reloading the page, you will se how the goal text changes,
due to the logic that calculates a random number on each iteration. This is the
base concept to understand so that later down the line you can build tons of
dynamic pages based on logic, binding and string interpolation.

=== Working with Data inside of a Vue App

It all depends on what you're building, and the goal. However, let's talk about
how to register Vue data, and how to leverage it.

By leveraging Vue `data()`, you can see how magic can happen:

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            courseGoalA: 'Finish the course and learn Vue!', <.>
            courseGoalB: 'Master Vue and build amazing apps!',
            vueLink: 'https://vuejs.org/'
        };
    },
    methods: {
        outputGoal() {
            const randomNumber = Math.random();
            if (randomNumber < 0.5) {
                return this.courseGoalA; <.>
            }

            return this.courseGoalB;
        }
    }
});

app.mount('#user-goal');
----
<.> You can register some extra properties, in this instance for saving goals.
<.> And you can then leverage `this` to reference those state properties by name.
This might look super strange, since `this` is a really tricky reserved name in
javascript

Vue, will always take all the properties under `data()` and it will register them
(alongside the methods in `methods`) as part of a global state. **This** is what
enables us having the ability to call them with `this` and also for the markup
to reference both methods and properties directly, regardless of interpolation or
data binding constraints.

=== Outputting Raw HTML Content with v-html

There's another directive that is really useful. And that comes when you have
scenarios in which you want to render structured HTML code. If you use html
elements in a string and you output with interpolation, then for security measures
it will not process the HTML. However, you can intentionally turn on that
processing: `v-bind`

````
<p v-html="outputGoal()"></p>
````
So you add it as an attribute, and then call any of the methods or properties that
the vue object is holding together.

The use cases for this html rendering switch are not _that many_, remember that it's
for security, it protects you against cross-site scripting. But if you ever need
to pass dynamically rendered HTML, `v-html` is your friend.

=== A First Summary

The moment we attach vue to some specific section, all the children also can get
manipulated. And when you attach vue to a section, you get access to special features
that javascript reads and then acts on. Lots of behavior under the scenes is computed,
but you only care about **declaring** what you want the behavior to be.

You _pass an object to your vue app_, and this object configures the vue app.

- data
- methods

These are all really important components of a vue object. The references across
methods and properties can be referred as `this`. The approach that Vue takes is
**_A declarative approach_**. Vue does all the magic behind the scenes, it updates
real DOM, it changes things around, _on our behalf_. As developers we define the
**final picture**, we architect based on behavior, we declare goals and those get
executed.

=== Assignment 1: Time to Practice: Data Binding

Need to create a Vue instance, use all the learned things so far.

Tasks:

- Output name
- Output age

Use vue.js. Save as properties, and output them from there.

- Output age + 5
- Output random number, and this needs to be outputted two times, one with a method
and another one without a method
- Output an image, go to Google, search for some random free to use image URL and
output the image (not throwing the URL, store that URL in the vue instance and
fetch it from there and output with vue syntax)
- Setting an `input` value with the _value attribute_

[source, html]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vue Basics</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="styles.css" />
    <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script> <.>
    <script src="app.js" defer></script>
  </head>
  <body>
    <section id="assignment">
      <!-- 1) Output your name -->
      <h2>{{ name }}</h2>
      <!-- 2) Output your age -->
      <p>{{ age }}</p>
      <!-- 3) Output your age + 5 -->
      <p>{{ age + 5 }}</p> <.>
      <!-- 4) Output a random number (0 to 1) -->
      <p>Favorite Number: {{ getRandomNumber() }}</p>
      <p>Favorite Number: {{ Math.random() }}</p>
      <div>
        <!-- 5) Display some image you found via Google -->
        <img v-bind:src="imageUrl" /> <.>
      </div>
      <!-- 6) Prepopulate the input field with your name via the "value" attribute -->
      <input v-bind:value="inputText" type="text" />
    </section>
  </body>
</html>
----
<.> Don't forget that the import of the course is "wrong". So this has to be changed.
<.> This evaluates javascript, it can just be a property reference or in-line
code execution, hence this works just fine.
<.> Remember that if you want to dynamically control attributes of HTML elements,
you have to use `v-bind:<attribute>`. That is key, after you declare the attribute
like that, you can safely execute js code or call methods or reference a property.

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            name: 'Diego',
            age: 26,
            imageUrl: 'https://future-architect.github.io/images/2025/20251022a/image.png',
            inputText: 'YO'
        }
    },
    methods: {
        getRandomNumber() {
            return Math.random();
        }
    }
});

app.mount('#assignment'); <.>
----
<.> Decided to do it like this for order purposes, and also because I noticed that
this element was encasing all the html elements for the assignment.

[IMPORTANT]
====
You can declare multiple "vue apps". Don't think it's just **one** mount that
works. But be sure to decide a good css selector. An id (`#id`) is probably the
best candidate, they have to be unique, otherwise Vue might get confused.
====

=== Understanding Event Binding

In modern web applications outputting data is half what you do. However, you
need to build reactive web applications. You need to react based on events.

We will use another testing project with pre-coded UI and some JS. But right now,
it doesn't react based on anything. We want to code behavior so that buttons trigger
some sort of event and the screen changes.

Our requirement is really easy: When we press the `Add` button we will add to
a counter, and when we press `Remove` we will decrease.

Remember, we need to leverage a declarative approach. No imperative. **Declare
the end result and let Vue do the magic**

For that we can use the `v-on` directive

````
<button v-on:click="counter">Add</button>
````

After `-on` we can select any of the native HTML attributes `focus` for example.

You can use a method that manipulates inline or calls a method:

````
<button v-on:click="onAdd">Add</button>
<button v-on:click="onRemove">Remove</button>

const app = Vue.createApp({
  data() {
    return {
      counter: 0,
    };
  },
  methods: {
    onAdd() {
      this.counter++;
    },
    onRemove() {
      this.counter--;
    }
  }
});

app.mount('#events');

````

Inline (not really good practice, but):

````
<button v-on:click="counter++">Add</button>
<button v-on:click="counter = counter - 1">Remove</button>
````

Look how little you need to write and still you get interactivity, reactivity and
so on. That's the **core asset of frameworks such as Vue**.

The framework does a lot of heavy lifting:

- Reacts to events
- Updates state and screen behind the scenes (knows where to replace)
	- Everything is JS behind the scenes. Makes life as a developer, much-much
	easier.

=== Events & Methods

As mentioned a bad practice:

````
<button v-on:click="counter++">Add</button>
<button v-on:click="counter = counter - 1">Remove</button>
````

You should put as little as javascript in the html side of a view. Even though
code is small or little, a good thing is to offload as much as possible to the
controller-model side of the view.

**Always remember to declare everything that vue leverages alongside its directives
inside the object that's in `Vue.createApp({})`.

Don't create functions outside, vue won't be able to see them, nor leverage them
correctly. Remember that the framework does a lot of fancy things behind the scenes,
remember that it's declarative and that is the philosophy behind all of its features.

The _better way of doing_ => Coding the logic in Javascript. And then pointing to
it from HTML. Even though you get the same result, as a habit, starting with methods
abstracting away all logic, is cleaner code.

[IMPORTANT]
====
When you write `v-on:click="add"` or `v-on:click="add()"`. Both syntaxes are correctly
resolved by Vue. But the "more correct way" would be without actually executing the
method = `add`. That's closer to vanilla JS.
====

Remember, we can bind methods to HTML events, and it's a core feature for building
rich modern web apps.

=== Working with Event Arguments

Let's add and deduct not just _1_ in the method. That can be done by accepting a
parameter.

````
methods: {
	onAdd(number) {
      this.counter += number;
    },
    onRemove(number) {
      this.counter -+ number;
	}
}

<button v-on:click="onAdd(5)">Add</button>
<button v-on:click="onRemove(5)">Remove</button>
````

Look how we extend the method to take one argument, and we can then declare in
the markup the argument. This is an important pattern. And that is because in reality,
you will have this scenario when building some use case. So sending event arguments,
turns really trivial actually.

=== Using the Native Event Object

Let's enhance the mini-dummy a bit more. We will add an input field and then as
something gets typed, the contents will be outputted in a another html element
below:

````
<button v-on:click="onAdd(5)">Add</button>
<button v-on:click="onRemove(5)">Remove</button>
<p>Result: {{ counter }}</p>
<input v-on:input="onInput" type="text">
<p>Your name: {{ name }}</p>
````
Notice how we are attaching to the native element's `input` event a method. In
the javascript side we would then code something like this:

````
const app = Vue.createApp({
  data() {
    return {
      counter: 0,
      name: '',
    };
  },
  methods: {
    onAdd(number) {
      this.counter += number;
    },
    onRemove(number) {
      this.counter -= number;
    },
    onInput(event) {
      this.name = event.target.value;
    }
  }
});

app.mount('#events');
````

So, by default, html events will always get an event automatically fed to them,
even on our `v-on:click` instance, we would get an event back, however because
we wrtoe `onAdd(5)` and `onRemove(5)`. We overwrote that stock behavior and fed
a custom argument. But on our `onInput` case, we are not overriding, we are letting
it keep the original behavior, the browser will provide the default event object.
This will have full of information about the event, HTML element in which the
event ocurred, and we can read the current value stored in the element from there.

The `target` will almost always refer to the HTML element that triggered the event,
and in the case of an input, the `value` property will yield whatever is stored
inside.

[NOTE]
====
This is all vanilla javascript and html behavior. You can even search for mdn
docs in google by typing something like "MDN input" for further information on
the API and how to leverage it.
====

After this, and we reload, we can start typing in the input, and we will see
'real-time" how the name changes in the places where updating is needed.

If you open the Dev Tools of the browser, and you type, you will see how the
parts that change, the text flashes. This is a corroboration that Vue is indeed
changing really specific HTML components. It's not changing the whole page, by
being smart Vue saves on performance.

[NOTE]
====
You could have an scenario in which you need to pass the native event, plus some
extra arguments. For this you can leverage a reserved keyword `$event`. Vue recognizes
this and will inject the native element for you on the method calling
====

````
<input v-on:input="onInput($event, 'Diego')" type="text">

onInput(event, name) {
	this.name = event.target.value + ' - ' + name;
}
````
Be sure to remember this, it might come in handy when you least expect it.

=== Exploring Event Modifiers

Another useful feature built into Vue.

Inheriting errors of the past, or well, different ways of thinking, if you have
a form like this:

````
<form>
	<input type="text">
	<button>Sign Up</button>
</form>
````
By default, when pressing the button, then the page will refresh, it will try to
send an HTTP request to the server serving the page. And in our case of an SPA,
we will lose **all our state**.

Typically, you want to prevent this browser default, and you should handle this
manually with javascript. **In the Vue app**. Programmatically read, treat and
send requests to a backend.

You can listen to the submit event: `v-on:submit="submitForm"` And do something
like this:

````
<form v-on:submit="submitForm">
	<input type="text">
	<button>Sign Up</button>
</form>

submitForm(event) {
	event.preventDefault();
	alert('Submitted!');
}
````
We attach ourselves to the form's `submit` event, and we use the native event object
to stop the reload of the page with `preventDefault()` that way we don't lose all
our state. However Vue has a nicer way:

**Event modifiers:** Help you change event behaviors, depends on the event type
and there are a couple of modifiers such as: `v-on:submit.prevent`. There's also
another for preventing propagation. Modifiers can help change "when an event occurs"
also.

With less code, you keep the same behavior. You can even modify a click event
to just react to right clicks `.click`. _Is this useful?_ Who knows, there may
be a case in which it is. So don't dismiss it just yet.

**There's also key modifiers**. What if we wanted to update an element only when
a user presses "Enter"?

````
<input v-on:input="onInput($event, 'Diego')" v-on:keyup.enter="confirmInput" type="text">
<p>Your name: {{ confirmedName }}</p>
````

And the code behind:

````
const app = Vue.createApp({
  data() {
    return {
      counter: 0,
      name: '',
      confirmedName: '',
    };
  },
  methods: {
    onAdd(number) {
      this.counter += number;
    },
    onRemove(number) {
      this.counter -= number;
    },
    onInput(event, name) {
      this.name = event.target.value + ' - ' + name;
    },
    confirmInput(event) {
      this.confirmedName = this.name;
    }, 
    submitForm(event) {
      alert('Submitted!');
    }
  }
});

app.mount('#events');
````
Notice how we have `v-on:keyup.enter` to react to another event. And only when
pressing enter on the input element (should be focused), then we actually update
an internal `confirmedName` property that then is set to be rendered in the below
html `<p>` tag. This is a cool idea that could be useful under specific workflows.

=== Locking Content with v-once

Nieche scenarios. But still let's have a look at it.

_What if we want for a value to never change after a first update?_

````
<p v-once>Starting Counter: {{ counter }}</p>
<p>Result: {{ counter }}</p>
````
With `v-once`, Vue prevents the binding to the rendered value. It will only be
rendered once, you lock an initial value. And any further update to the same
property will not be reflected on these "frozen" elements.o

=== Assignment 2: Time to Practice: Event Binding

[source, html]
----
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Vue Basics</title>
  <link href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="styles.css" />
  <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script>
  <script src="app.js" defer></script>
</head>

<body>
  <header>
    <h1>Events</h1>
  </header>
  <section id="assignment">
    <h2>Event Practice</h2>
    <!-- 1) Show an alert (any text of your choice) when the button is pressed -->
    <button type="button" v-on:click="showAlert">Show Alert</button> <.>
    <hr />
    <!-- 2) Register the user input on "keydown" and output it in the paragraph (hint: event.target.value helps) -->
    <input v-on:keydown="onKeydown" type="text" />
    <p>{{ keyedText }}</p>
    <hr />
    <!-- 3) Repeat 2) but only output the entered value if the ENTER key was pressed -->
    <input v-on:keyup.enter="snapshot" type="text" /> <.>
    <p>{{ snapshotText }}</p>
  </section>
</body>

</html>
----
<.> Using the syntax `click="showAlert"` is closer to the official syntax and to
conventions of HTML and JS working together. It also makes you write less code (by
offsetting to cognitive load).
<.> The solution of the course actually also put the `v-on:keydown="onKeydown"`
here, so two event listeners. I mean, from a "performance" standpoint, the enter
is more than enough, otherwise you are just using computing power for the reading
of every keystroke.

[source, js]
----
const app = Vue.createApp({ <.>
    data() {
        return {
            keyedText: '',
            snapshotText: '',
        }
    },
    methods: {
        showAlert() {
            alert('pressed');
        },
        onKeydown(event) { <.>
            this.keyedText = event.target.value;
        },
        snapshot(event) {
            this.snapshotText = event.target.value;
        }
    }
});

app.mount('#assignment'); <.>
----
<.> Never forget we need to create a vue app. This will allow us to then inject
as much reactivity as we want.
<.> And we have to attach the app to some part of the HTML
<.> Keydown is executed when the key is released, so the behavior that the input
lags behind one character is **expected**. Also, `event` is a browser default
object that you get when an HTML element triggers an event

=== Data Binding + Event Binding = Two-Way Binding

Our goal is to have **another button**. That helps us reset the input in the
input element. (**Not just the state value**). We could select the input element
manually, and so on. But that's hacky, it's just hacky. Vue has features that allow
for us to both manipulate some element's value through a side effect.

````
<input v-bind:value="name" type="text" v-on:input="setName($event, 'Schwarzmüller')">
<p>Your Name: {{ name }}</p>
<button v-on:click="resetInput">Reset Input</button>
````
`v-bind:value`, allows to enable _two way binding_. By not just listening to the
input, you can send the stored value to the element, it's a really common use case.

So common, we can simplify adding two events with a simple directive:

````
<input type="text" v-model="name">
````
This holds the same behavior, but with less code. **Two-way binding**, is that we
are listening to the input event, and at the same time we are writing back the value
to the HTML element, **through its property**. It's super useful, since updating
values is so clean and useful.

=== Methods used for Data Binding: How It Works

So far we know:

- DOM Interaction, Templates & Data Binding
- Event Handling = Two-way binding

_"Advanced Reactivity"_

What if we want the behavior of computing a state value? Like adding a prefix to
a name? - Mr <xxx>

````
<p>Your Name: {{ outputFullName() }}</p>

outputFullName() {
  if (this.name === '') {
    return '';
  }

  return this.name + ', Sir!';
}
````
This is great, we add now a computation behind a method that outputs a string in
an element. _However it's not_. Because Vue, whenever a change in state is detected,
**will always run any method behind any non-event bound attribute**. If you have
tons of methods all spread across your view, you will be re-running all of them
on each state change. That's not ideal, **the reason Vue does this**, is that he
has to run them to know if the state that changed was affected so he can then
update the view accordingly.

_There's a better way of displaying computed properties_

=== Introducing Computed Properties

_First, we could put the code in-line instead of a method_ That way vue can see
what's getting used and perhaps not run the javascript execution.

**Not that readable though**

And so, we can use a third option of the vue createApp method:

[source, js]
----
const app = Vue.createApp({
  data() {
    return {
      counter: 0,
      name: ''
    };
  },
  computed: {
    fullname() { <.>
      if (this.name === '') {
        return '';
      }

      return this.name + ', Sir!';
    }
  },
  methods: {
    setName(event) {
      this.name = event.target.value;
    },
    add(num) {
      this.counter = this.counter + num;
    },
    reduce(num) {
      this.counter = this.counter - num;
      // this.counter--;
    },
    resetInput() {
      this.name = '';
    },
    outputFullName() {
      if (this.name === '') {
        return '';
      }

      return this.name + ', Sir!';
    },
  }
});

app.mount('#events');
----
<.> Just like `methods` this needs to receive an object, and inside there will
be functions. However, the naming convention is **really important**. Because in
the HTML we would call this like a property, no execution `method()`.

For performance, it's better using computed properties, that way you won't run
the calculation every single time. Computed properties will keep track of the
dependencies, so Vue will know if he has to actually run the logic or not.

````
<p>Your Name: {{ fullname }}</p>
````
You use computed properties for outputting things just like this. Straightforward.

=== Working with Watchers

A key feature for outputting dynamic values is indeed computed properties. However
there is another reactivity feature: **Watchers**.

This is basically a function that runs, every-time a dependency changes. You could
actually replace computer properties for watchers (but that might not be the
best idea)

- Computed and data properties should not clash.

So a watcher, is "attached" to a name by matching the name:

[source, js]
----
data() {
  return {
    counter: 0,
    name: '', <.>
    fullname: '',
  };
},
watch: {
  name(value) { <.>
    this.fullname = value + ' ' + ', BOSS!'; <.>
  }
},
----
<.> So we are going to configure a watcher for `name`.
<.> The watcher automatically can receive the latest value of the property that's
being watched, and you can also receive a second parameter that will old an old
value
<.> And in here you can then run some specific logic, as you can see by doing this
we are emulating the same behavior as we had with the computed property

But this is not good if say we have "two dependencies", say for fullname we compute
with two propeties: `firstName` and `lastName`, we would have to write two
watchers and do a lot of similar looking code.

A computed property will easily grab as many properties and detect changes in them
to then update as needed.

Watchers, are good when focusing on **one value** and we need to perhaps control
something in it, say a counter that after going to 50, it has to be reset to 0.
Or something akin to that. In this scenario using computed properties you'd
have lots of issues.

**Another example:** HTTP requests, timers.

=== Methods vs Computed Properties vs Watchers

Methods:

- Use with event binding OR data binding
- Data binding: Method is executed for every "re-render" cycle of the component
- Use for events or data that really needs to be re-evaluated all the time

Computed Properties:

- Use with data binding
- Computed properties are only re-evaluated if one of their "used values" changed
- Use for data that depends on other data

Watch:

- Not used directly in template
- Allows you to run any code in reaction to some changed data (e.g., send Http
request etc.)
- Use for any non-data update you want to make

_Note:_ You are probably going to use the least: Watchers. Because the other
types are highly used in all sorts of use cases.

=== v-bind and v-on Shorthands

`v-on` was used a lot, and `v-bind` also.

Instead of `v-on:click`, you can use the shorthand `@click=''`. This can still
be combined with modifiers, it's just that `@` is used. It's less code to write,
it's up to you to use it, but **be consistent**. Also `v-bind` can turn into `:value="..."`

=== Assignment 3: Time to Practice: Reactivity

Straight forward

[source, html]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vue Basics</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="styles.css" />
    <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script>
    <script src="app.js" defer></script>
  </head>
  <body>
    <header>
      <h1>Reactivity in Action</h1>
    </header>
    <section id="assignment">
      <button @click="onAddFive">Add 5</button> <.>
      <button @click="onAddOne">Add 1</button>
      <!-- 1) Connect the buttons and calculate a value (a number) -->
      <!-- Show "Not there yet" until you reach a result of exactly 37 -->
      <!-- Show "Too much!" if the result is greater than 37 -->
      <p>Result: {{ result }}</p> <.>
      <!-- 2) Watch for changes in "result" and reset the value to 0 after 5 seconds -->
    </section>
  </body>
</html>
----
<.> Using the short handle `@click`
<.> This is actually a computed property, yet referenced as if it was a normal property.

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            counter: 0,
            timeout: null
        };
    },
    watch: {
        counter(value) {
            const that = this; <.>

            if (that.timeout == null && that.counter !== 0) { <.>
                that.timeout = setTimeout(() => { <.>
                    alert('Counter reset!');
                    that.counter = 0;
                    that.timeout = null;
                }, 5000);
            }
        }
    },
    computed: {
        result() {
            if (this.counter < 37) {
                return 'Not there yet';
            }

            if (this.counter > 37) {
                return 'Too much!';
            }

            return this.counter;
        }
    },
    methods: {
        onAddFive() {
            this.counter += 5;
        },
        onAddOne() {
            this.counter += 1;
        }
    }
});

app.mount('#assignment');
----
<.> Due to the fact that when doing a `setTimeout` the handler has its own context,
we have to capture the outside method's `this` under `that`
<.> This is a bad attempt at having the timeout only run once, and not multiple
timeouts. It still shows 2 alerts always.
<.> And yeah, we are saving a timeout reference to mark that we allocated a timeout
already, and inside we are both resetting the counter and also clearing out the
timeout again for subsequent runs.

=== Dynamic Styling with Inline Styles

So apparently, we can change styles based on user interactions, making it "dynamic
stling".

[source, html]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vue Basics</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="styles.css" />
    <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script>
    <script src="app.js" defer></script>
  </head>
  <body>
    <header>
      <h1>Vue Dynamic Styling</h1>
    </header>
    <section id="styling">
      <div class="demo" :style="{ borderColor: boxASelected ? 'red' : '#ccc' }" @click="boxSelected('A')"></div> <.> <.>
      <div class="demo" @click="boxSelected('B')"></div>
      <div class="demo" @click="boxSelected('C')"></div>
    </section>
  </body>
</html>
----
<.> To tap into styles, we can use the shorthand `:style`, and inside we have to
feed an object, and the recommended approach to access all the css features that
might be inside, is camelCase syntax. In this instance since our objective is to
change a box's border we will use `borderColor` and this will refer back to the
property in the vue app `boxASelected` and based on its value, we will paint the
border red, otherwise it will be gray.
<.> Notice also how we are using `@click` the shorthand to react to click events,
and we are running the method of the vue app with an argument that helps us change
the flag status for the respective box.

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            boxASelected: false, <.>
            boxBSelected: false,
            boxCSelected: false,
        };
    },
    methods: {
        boxSelected(box) {
            if (box === 'A') {
                this.boxASelected = true; <.>
                return;
            }

            if (box === 'B') {
                this.boxBSelected = true;
                return;
            }

            if (box === 'C') {
                this.boxCSelected = true;
            }
        }
    }
});

app.mount('#styling');
----
<.> We have created three state properties for each box in the view, it will be
a boolean because the two expected states are binary in nature (selected or not
selected)
<.> Whenever we receive a respective parameter for the respective box, we set
its flag to true

And just like this, we can change styling on a component in a dynamic fashion.

=== Adding CSS Classes Dynamically

[IMPORTANT]
====
Inline styles overrule any other style. Which sometimes might be the case, however
in modern web development, they are not considered good practice. So we resort
to css classes.
====

Our goal, is always to write less code, but that it's still understandable/readable.
And with that in mind we can do something like this:

[source, html]
----
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Vue Basics</title>
  <link href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="styles.css" />
  # <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script>
  <script src="app.js" defer></script>
</head>

<body>
  <header>
    <h1>Vue Dynamic Styling</h1>
  </header>
  <section id="styling">
    <div
      class="demo" <.>
      :class="{ active: boxASelected }" <.>
      @click="boxSelected('A')"></div>
    <div class="demo" :class="{ active: boxBSelected }" @click="boxSelected('B')"></div>
    <div class="demo" :class="{ active: boxCSelected }" @click="boxSelected('C')"></div>
  </section>
</body>

</html>
----
<.> We can totally just declare the vanilla `class` property so that it will act
as a hardcode actually.
<.> And then we can inject the vue bound `:class` property, in here we can also
leverage another feature which is this syntax that receives an object, and inside
of it as keys/property names we can declare a class name, and the value of that
key has to be a boolean (well, it will be computed as truthy, but boolean for simplicity).
If that value is true, then vue will attach the respective class and merge it with
the hardcoded class of the html element.

Remember, that if we don't declare the css class, no style will be applied:

````
.active {
  border-color: red;
  background-color: salmon;
}
````

And lastly, if you want to make selectable and unselectable a box, instead of
just setting it to `true`, you can leverage the cancellation of the boolean directly:

````
boxSelected(box) {
  if (box === 'A') {
      this.boxASelected = !this.boxASelected;
      return;
  }

  if (box === 'B') {
      this.boxBSelected = !this.boxBSelected;
      return;
  }

  if (box === 'C') {
      this.boxCSelected = !this.boxCSelected;
  }
}
````

=== Classes & Computed Properties

The code as much as nice it is, it's still suboptimal. :(. We want to move as
much logic away from the HTML as possible. Hence, computed properties can help
us with that:

````
<div
  class="demo"
  :class="boxAClasses"
  @click="boxSelected('A')"></div>

computed: {
  boxAClasses() {
      return { active: this.boxASelected };
  }
},
````
This can further simplify things. But beware that this should be reserved for
complex computations, sometimes it's a bit overkill to put a whole computed
property if the function is a literal one-liner.

=== Dynamic Classes: Array Syntax

There's one more syntax supported by vue. You **can** have multiple class attributes,
however, you can pass an array as well, where you pass the different classes or
objects if you want:

````
:class="['demo', { active: boxBSelected }]"
````

This is another syntax to be aware off. There are multiple options, and it depends
on your personal preference, and what you are building.

_Super powerful and important_

- With dynamic styling you can build amazing user interfaces.

=== Assignment 4: Time to Practice: Dynamic Styling

What I learned:

For inline styling:

````
<p :style="{ backgroundColor: background }">Style me inline!</p>
````
You have to pass an object, and the **VALUES** will be evaluated by Vue. So
if you define a property, that property can then be referenced by name and any
mutations applied to it will be evaluated and then computed for styling.

The solution of the instructor also is interesting, instead of capturing with callbacks
on input (`@input`) you can just `v-model=` and directly reference the **PROPERTY**
and it will be two-way bound easily.

And another smart thing is to make usage of the true-false, addition of class,
because there are two classes, you can bind them showing by having **two booleans**.

=== Module Summary

- DOM & Templates => Vue features that have reflecting changes on the page
  - Vue makes usage of the **declarative approach**
  - Connect Vue to HTML via "mount"
  - Vue renders the real DOM based on the connected template
- Data & Event Bindings
  - You can bind data via interpolation `{{ }}` or the v-bind (`:`) directive.
  - You listen for events via v-on `@`
- Reactivity
  - Vue updates the real DOM for you when bound data changes
  - Computed properties and watchers allow you to react to data changes
- Styling
  - You want to make apps look pretty, RIGHT?
    - Dynamic CSS class and inlite style bindings are supported by Vue
  - Vue offers multiple **special syntaxes** (object-based, array-based) for
  efficient bindings

This is of course, but the tip of the ice-berg. _But this is something we can
start with_

== Section 3: Rendering Conditional Content & Lists

=== Module Introduction

- Conditional Content & Lists
  - Rendering More... Sometimes
  - Rendering Content With Conditions
  - Outputting Lists of Data
  - A first look behind the scenes

=== Understanding the Problem

Basically a typical requirement of modern web applications is to display content
conditionally, so that parts of the page change and display or behave differently.

Another requirement is to display lists, or multiple elements that only change in
details, but are overall part of a same type of pattern/entry.

How can we achieve these type of outcomes? Vue should have some features that make
it easy to deal with conditional rendering and list rendering.

=== Rendering Content Conditionally

- We have to hide the "no goals" paragraph if we have goals (so an item in a list
state property)
- Otherwise show the elements

We can tackle first the conditional part of things:

[source, html]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vue Basics</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="styles.css" />
    <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script>
    <script src="app.js" defer></script>
  </head>
  <body>
    <header>
      <h1>Vue Course Goals</h1>
    </header>
    <section id="user-goals">
      <h2>My course goals</h2>
      <input v-model="goal" type="text" /> <.>
      <button @click="onAddGoal">Add Goal</button> <.>
      <p v-if="!goals.length">No goals have been added yet - please start adding some!</p> <.>
      <ul v-if="goals.length"> <.>
        <li>Goal</li>
      </ul>
    </section>
  </body></html>
----
<.> We have an input that will capture the goal we want to add to the list of goals
(don't forget that this is really straightforward with `v-model`)
<.> And then when pressing an "Add Goal" button we add that very same goal to
the list
<.> And with `v-if` we can then feed some javascript syntax that should evaluate
to truthy, and based on that the content will be shown (or not)
<.> The list will be the opposite of the `No goals...` when it comes to its rendering
condition

[source, js]
----
const app = Vue.createApp({
  data() {
    return {
      goals: [], <.>
      goal: null <.>
    };
  },
  methods: {
    onAddGoal() {
      this.goals.push(this.goal); <.>
    }
  }
});

app.mount('#user-goals');

----
<.> We have a list property (state property)
<.> And then a property for the goal that we will bind the input to, that way we
can reference it and its value
<.> After pressing the button we can then put code that adds the `goal` state property
into the `goals` state property element list

=== v-if, v-else and v-else-if

In `v-if` you will always evaluate things as **TRUTHY**. You can make complex
boolean operations (in-line), or you can execute methods that return a truthy
or falsy value.

**However**, there are other directives that help connecting with if-else like
logic. As we already did, we can put two `v-if` with inverted conditions. You can,
however, you have `else`, instead of repeating `if`.

**`v-else` has to be before a `v-if` element, always**

And if you need more granular checks, there's also `v-else-if`.

[IMPORTANT]
====
It's not just "hiding", as if the element is still there in the DOM. Vue actually
**removes the node from the DOM**. Conditional rendering is super important. You
will use it a lot
====

=== Using v-show instead of v-if

This directive actually goes against what v-if has built into it. This does **hide**.
The DOM element is still there, with a `display: none` css property.

Which approach is better? Showing and hiding elements can be performant. _However,
fallback into `v-show` if its visibility changes a lot, only there, `v-if` should
be the default at the beginning_

=== Rendering Lists of Data

It would be nice to render our actual goals instead of the dummy **Goal** we have
currently. Vue covers us for that as well.

Lists are everywhere in web apps, so Vue gives us a feature that helps us outputting
repeatable content. `v-for` directive.

````
<ul v-else-if="goals.length > 0">
  <li v-for="goal in goals">{{ goal }}</li>
</ul>
````
Syntax, again, will mirror javascript. However in vue it's **_recommended_** to
be `goal in goals`, `of` is supported, but not the standard recommendation. The
syntax plays into opening up the possibilities to deal with each element that is
being iterated over. In our case, since it's a list of simple strings, we will simply
evaluate its value (in our case inside the `li` tag), and that will be rendered,
and just like this, we have managed to know render repeatable lists as html elements.

[NOTE]
====
Just like a regular javascript type of for-loop, outside of the main element that has
the `v-for` directive, the iteration variable is not accesible, and won't work
at all.
====

Also, it's great that Vue has performance in mind, so he surgically adds and
removes elements into the DOM. Whenever you add a new element, only that new
element gets rendered, when you remove, only that element gets removed.

=== Diving Deeper into v-for

With `v-for` you can pull out also the index of the iteration, not just the
element.

````
<li v-for="(goal, index) in goals">{{ goal }} - {{ index }}</li>
````

You can also loop through more than just arrays. You can loop through objects.

_Although arrays will probably be the more useful data structure_

````
<li v-for="(value, key) in { name: 'Max', age: 31 }">{{ value }}</li>
````
You can even get the index, (if you add a third tuple element to the iteration
element)

You can even looping through an array of numbers:

````
<ul>
  <li v-for="num in 10">{{ num }}</li>
</ul>
````

=== Removing List Items

How can we remove items from the list?

Well, we can attach a listener to each list element so that it triggers a callback
that can then invoke some method on the array to get rid of said element:

````
<li v-for="(goal, index) in goals" @click="removeItem(index)">{{ goal }} - {{ index }}</li>

methods: {
  onAddGoal() {
    this.goals.push(this.goal);
  },
  removeItem(index) {
    console.log(index);
    this.goals.splice(index, 1);
  },
}
````
In this case, index comes in really handy because we can pass that directly to the
method and then make usage of `splice` which needs an index, and then a number
of deletions (in our case we only want to delete 1 element starting at that index)

[NOTE]
====
Be careful, the index is not "snapshotted" so when deleting an element, the whole
list rendering gets evaluated again, so all the element's index gets recalculated
and in short they are moved one index back.
====

_Barely any code at all, and we have a dynamic list behavior_. Writing the whole
thing in javascript, would be 10 times more difficult.

=== Lists & Keys

So, if you are not aware of the `:key` non-standard attribute to a list. You might
get into weird behaviors. Like deleting an element, and losing an element's content
or state.

````
<li v-for="(goal, index) in goals" :key="goal" @click="removeItem(index)">
  <p>{{ goal }} - {{ index }}</p>
  <input type="text" @click.stop>
</li>
````
Without `:key`, you could create multiple goal items. Write something in the input,
and if you delete the previous element, then the content would move only for the
dynamically rendered one. The input text would be thrown out the window.

_Why?_ Because Vue, tries to optimize things as much as possible, it doesn't compare
the whole element's values, yet it tries to shift around content from further elements
into previous DOM elements (because the less costly operation is to remove as least
DOM elements as possible and shift around the rendered content).

In order for us to provide Vue with more metadata, that allows for text such as
input text to be taken as "different" and influencing Vue's algorithm to not
just skip over elements such as this, is by adding a `:key`. Towards each list
element. In this case we can bind it directly to the `goal` text itself, but in
other use cases, it might be a database primary key or so on. The main takeaway
is that to avoid these weird bugs, you should provide keys for your list elements.

=== Assignment 5: Time to Practice: Conditional Content & Lists

A bit hard because I forgot syntax, but managed to pull it off

[source, html]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vue Basics</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="styles.css" />
    <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script>
    <script src="app.js" defer></script>
  </head>
  <body>
    <header>
      <h1>Vue Lists and Conditional Content</h1>
    </header>
    <section id="assignment">
      <h2>Assignment</h2>
      <!-- 1) Add code to manage a list of tasks in a Vue app -->
      <!-- When clicking "Add Task" a new task with the entered text should be added -->
      <input v-model="newTask" type="text"> <.>
      <button @click="onAddTask">Add Task</button>
      <ul :class="listClasses"> <.>
        <!-- 2) Output the list of tasks here -->
         <li v-for="task in tasks">{{ task }}</li>
      </ul>
      <!-- 3) When the below button is pressed, the list should be shown or hidden -->
      <!-- BONUS: Also update the button caption -->
      <button @click="onVisibility">{{ visibilityLabel }}</button>
    </section>
  </body>
</html>
----
<.> Don't forget that to two-way bind you have to use `v-model`. That's the directive
<.> For dynamic styling or classes don't forget to prefix with `:`

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            newTask: '',
            tasks: [],
            visible: true,
        }
    },
    computed: {
        visibilityLabel() {
            if (this.visible) { <.>
                return 'Hide List';
            }

            return 'Show List';
        },
        listClasses() {
            return { visible: this.visible, 'not-visible': !this.visible }; <.>
        }
    },
    methods: {
        onAddTask() {
            this.tasks.push(this.newTask);
        },
        onVisibility() {
            this.visible = !this.visible;
        }
    }
});

app.mount('#assignment');
----
<.> Always use `this` for state properties. Otherwise the app will break, since
you will be referrencing a non-existent variable.
<.> This syntax is a bit funn at first, but it's powerful under the premise that
if the value is evaluated to true the respective class name will be added to the
class property

[source, css]
----
// Stuff
.visible {
  display: block;
}

.not-visible {
  display: none;
}
----
Went the route with two classes that simply hide the button, could've used conditional
rendering though...

````
<ul v-if="visible">
  <!-- 2) Output the list of tasks here -->
  <li v-for="task in tasks">{{ task }}</li>
</ul>
 ````
Yeah, actually with `v-if` it's simpler, no need for a computed property, and no
need for styles in the `.css` file.

[NOTE]
====
Forgot to add `:key`. That is a good habit to develop! Always add that to the
elements that are being iterated with `v-for`
====

=== Module Summary

We have the core basics to build Vue applications now. Great Job!

- Conditional Content
  - v-if (and v-show) allow to render content only if a certain content is shown
  - v-else, v-else-if have to be used under a v-if, but help extending more
- Lists
  - v-for can be used to render multiple elements dynamically
  - v-for can be used with arrays, objects and ranges
- v-for Variations
  - You can extract values and indexes, keys as well
  - If you need v-for and v-if, DON'T use them on the same element. Use a wrapper
  with v-if instead
- Keys
  - Vue re-uses DOM elements to optimize performance. This can lead to bugs if
  elements contain state
  - Bind the **key** attribute to a unique value to help Vue identify elements
  that belong to list content

== Section 4: Course Project: The Monster Slayer Game

=== Module Introduction

We will build an actual project. To put to use/practice all the knowledge we had
reviewed (core basics).

=== Project Setup & First Methods

We have to download the scaffold of the course. We will create everything that
is Vue related from scratch. But styles and HTML will be already provided to
save up on time.

There are multiple routes to take. But let's understand the requirements:

- This is a monster slayer game, in which you fight a monster, you can choose
to attack the monster, do a special attack, heal yourself or surrender.
  - The monster will also take actions in the background to attack you and reduce
  your health

So we have to program all this behavior

- Let's not use a hard-coded value for damage, that way the game is not too predictable

`data()` is a core concept in Vue apps. Because any app that you code, you need
state. `data()` are the regular variables you might use in JS.

What are the different variables that we need to manage? (as state) Health values
for starters.

- playerHealth
- monsterHealth

This is good. But we need ways to change the health now, for example attacks.
That screams, **methods**, they will be the actions that the Vue application
executes.

The methods will calculate a random attack number to reduce the health of the
player or the monster.

Remember that inside the methods you should reference state values as `this.`,
because Vue exposes them through a global state object.

````
attackMonster() {
  const damage = Math.floor(Math.random() * (12 - 5)) + 5;
  this.monsterHealth -= damage;
},
attackPlayer() {
  const damage = Math.floor(Math.random() * (20 - 5)) + 5;
  this.monsterHealth -= damage;
}
````
We are applying a known formula to generate a random number between a range we
want (12 max, 5 minimum), (20 max, 5 minimum)

And a new concept is introduced:

[source, js]
----
function getRandomValue(min, max) { <.>
    return Math.floor(Math.random() * (max - min)) + min;
}

const app = Vue.createApp({
    data() {
        return {
            monsterHealth: 100,
            playerHealth: 100
        }
    },
    methods: {
        attackMonster() {
            const damage = getRandomValue(5, 12); <.>
            this.monsterHealth -= damage;

            this.attackPlayer(); <.>
        },
        attackPlayer() {
            const damage = getRandomValue(5, 20);
            this.playerHealth -= damage;
        }
    }
});

app.mount('#game');
----
<.> So, inside of your javascript module, you can of course register functions
as you see fit. These will not be related to the binding of HTML, but can be leveraged
by Vue itself.
<.> As you can see, we can call the functions declared on the same module and reuse
a generalized function instead of repeating code
<.> And this is the new concept. The global vue object will contain everything that
is declared under the different properties, so inside of vue methods, you can call
other declared methods. And this effectively makes it so that after the player
attacks the monster, the monster then attacks the player.

=== Updating the Health Bars

Let's now engage with the view. So that actions on the UI call the logic we have
programmed.

This is easy to bind the click of attack:

````
<button @click="attackMonster">ATTACK</button>
````

But we need to give feedback to the player now, we have to also update the healthbars.

So we can bind the health bar styles to our state values:

````
<section id="monster" class="container">
  <h2>Monster Health</h2>
  <div class="healthbar">
    <div class="healthbar__value" :style="{ width: `${monsterHealth}%` }"></div>
  </div>
</section>
<section id="player" class="container">
  <h2>Your Health</h2>
  <div class="healthbar">
    <div class="healthbar__value" :style="{ width: `${playerHealth}%` }"></div>
  </div>
</section>
````
As you can see, in trying to make it more readable, we use string interpolation
and leverage the object notation for `:style`. But as a good practice, remember
that we want to offset as much logic from the view as possible.

[NOTE]
====
Also, this is one of the use cases in which makes sense to use inline styles.
_Why?_ Because this will override any class styles that currently exist for the
bar elements. Because the style will be bound to state, then the health bars
become dynamic.
====

But now, in hopes of making code more readable, we can leverage computed properties
for the whole style object:

````
computed: {
    monsterBarStyles() {
        return { width: `${this.monsterHealth}%` };
    },
    playerBarStyles() {
        return { width: `${this.playerHealth}%` };
    },
},

<section id="monster" class="container">
  <h2>Monster Health</h2>
  <div class="healthbar">
    <div class="healthbar__value" :style="monsterBarStyles"></div>
  </div>
</section>
<section id="player" class="container">
  <h2>Your Health</h2>
  <div class="healthbar">
    <div class="healthbar__value" :style="playerBarStyles"></div>
  </div>
</section>
````

=== Adding a "Special Attack"

Now, a next action can be coded.

The rule is.

- Special attack will pack more damage to the monster, and it will be available
only every 3 rounds.

````
<button @click="specialAttackMonster" :disabled="!canSpecialAttack">SPECIAL ATTACK</button>

computed: {
    monsterBarStyles() {
        return { width: `${this.monsterHealth}%` };
    },
    playerBarStyles() {
        return { width: `${this.playerHealth}%` };
    },
    canSpecialAttack() {
        return this.round % 3 === 0;
    }
},
methods: {
    attackMonster() {
        const damage = getRandomValue(5, 12);
        this.monsterHealth -= damage;

        this.attackPlayer();
        this.round++;
    },
    attackPlayer() {
        const damage = getRandomValue(5, 20);
        this.playerHealth -= damage;
    },
    specialAttackMonster() {
        const damage = getRandomValue(10, 25);
        this.monsterHealth -= damage;

        this.attackPlayer();
        this.round++;
    }
}
````
The most important takeaways is the usage of `:disabled` to access the specific
html property, we can then bind this to a computed property (for offsetting of
logic) and we can apply the simple calculation of a `% 3 === 0` so that if this is
`true` it's not disabled, and if it's `false` it will be disabled. Besides that
we have added a new method that will trigger on the special attack button click,
and the attacks will increment a round state value that was also added to `data()`

And with this, our new game rule has been successfully implemented.

=== Adding a "Heal" Functionality

Let's add a heal method on the methods.

````
healPlayer() {
    const healValue = getRandomValue(8, 25);
    if (this.playerHealth + healValue > 100) {
        this.playerHealth = 100;
    }
    else {
        this.playerHealth += healValue;
    }

    this.attackPlayer();
    this.round++;
}

<section id="controls">
  <button @click="attackMonster">ATTACK</button>
  <button @click="specialAttackMonster" :disabled="!canSpecialAttack">SPECIAL ATTACK</button>
  <button @click="healPlayer">HEAL</button>
  <button>SURRENDER</button>
</section>
````
In short, we bind a click on `HEAL` so that now we can add to the player health,
progress a round and also let the monster attack the player.

=== Adding a "Game Over" Screen

We need to now code the WON and LOST conditions.

We need to be checking the monster and player health. We could do the check in
multiple methods, all over the place (repeated code).

**Watcher** can help us now. So that we watch the player health and monster health.

[source, js]
----
data() {
    return {
        monsterHealth: 100,
        playerHealth: 100,
        round: 1,
        gameOver: false, <.>
        gameOverText: '' <.>
    }
},
watch: {
    playerHealth(value) {
        if (value <= 0 && this.monsterHealth <= 0) {
            this.gameOverText = 'Draw!'; <.>
            this.gameOver = true;
        } else if (value <= 0) {
            this.gameOverText = 'Monster wins!';
            this.gameOver = true;
        }
    },
    monsterHealth(value) {
        if (value <= 0 && this.playerHealth <= 0) {
            this.gameOverText = 'Draw!';
            this.gameOver = true; <.>
        } else if (value <= 0) {
            this.gameOverText = 'Player wins!';
            this.gameOver = true;
        }
    }
},
----
<.> We will have a flag that can allow us to mark the game as over (this will come
in handy to also conditionally show a game over message)
<.> The course takes another route and adds tons of `v-if` but I decided to have
a multi-usage message for the game over because we have 3 possible scenarios,
this simplifies the HTML syntax
<.> So when we hit a specific scenario we set the label/message that corresponds
<.> And we mark the game as over

[source, html]
----
<section v-if="gameOver" class="container"> <.>
  <h2>Game Over!</h2>
  <p>{{ gameOverText }}</p> <.>
</section>
<section id="controls">
  <button @click="attackMonster">ATTACK</button>
  <button @click="specialAttackMonster" :disabled="!canSpecialAttack">SPECIAL ATTACK</button>
  <button @click="healPlayer">HEAL</button>
  <button>SURRENDER</button>
</section>
<section id="log" class="container">
  <h2>Battle Log</h2>
  <ul></ul>
</section>
----
<.> As you can see, the game over message is behind a `v-if` so only if the game
is truly over, then we show the message to the player
<.> And then on one `<p>` element the different scenario-driven message will be
displayed

=== Finishing the Core Functionality

So, right now when a game ends, the health bars never reach 0. And that's because
the health drops to negative and css does not cover width for negatives. So we
can actually get in between this, and return a 0% width:

````
computed: {
    monsterBarStyles() {
        if (this.monsterHealth < 0) {
            return { width: '0%' };
        }

        return { width: `${this.monsterHealth}%` };
    },
    playerBarStyles() {
        if (this.playerHealth < 0) {
            return { width: '0%' };
        }

        return { width: `${this.playerHealth}%` };
    },
    canSpecialAttack() {
        return this.round % 3 === 0;
    }
},
````
And with this we finally have health bars that reach 0.

Lastly we can add a simple button to start the game again.

````
<section v-if="gameOver" class="container">
  <h2>Game Over!</h2>
  <p>{{ gameOverText }}</p>
  <button @click="restartGame">Start New Game</button>
</section>

restartGame() {
    this.gameOver = false;
    this.gameOverText = '';
    this.playerHealth = 100;
    this.monsterHealth = 100;
    this.round = 1;
}
````
Straightforward, a new button on the game over section. It has a `@click` listener
to a method that sets all the state values to the original values. And with that
we have a replayable health.

One missing feature is the Battle Log, we should see a retelling of a match as well!

However, let's just implement the surrender button.

````
<section v-if="!gameOver" id="controls">
  <button @click="attackMonster">ATTACK</button>
  <button @click="specialAttackMonster" :disabled="!canSpecialAttack">SPECIAL ATTACK</button>
  <button @click="healPlayer">HEAL</button>
  <button @click="surrender">SURRENDER</button>
</section>

surrender() {
    this.gameOver = true;
    this.gameOverText = 'Monster wins!';
}
````
This is but a new `@click` on the surrender button, its specific logic. And an
extra QoL. When the game is over the controls are still present, so the health-bars
can still show and the player can interact with them. By adding `v-if="!gameOver"`
we can hide the controls, that way the player can't play after the game is over.

=== Adding a Battle Log

There are many ways of implementing this. The log is basically a place in which
we add messages and we keep track of who did an action, the value of the action
and so on.

````
addLogMessage(who, what, value, round) {
    this.log.unshift({
        round: round + 1,
        actionBy: who,
        actionType: what,
        actionValue: value
    });
}

<ul>
  <!-- <li v-for="message in log">{{ `Round: ${message.round} ${message.actionBy} ${message.actionType} ${message.actionValue}` }}</li> -->
  <li v-for="message in log">
    <span
      :class="{ 'log--player': message.actionBy === 'player', 'log--monster': message.actionBy !== 'player' }">{{
      message.actionBy === 'player' ? 'Player' : 'Monster' }}</span>
    <span v-if="message.actionType === 'heal'"> heals himself for <span class="log--heal">{{ message.actionValue
        }}</span></span>
    <span v-else>
      attacks and deals <span class="log--damage">{{ message.actionValue }}</span>
    </span>
  </li>
</ul>
````
Basically, on each action, we would reuse a new method that will start adding
messages in an array to log who did what, the value of that action (heal or damage)
and even the round. Then we can iterate over the list of messages and access the
objects that we have in a property (that for this instance we named `log`)

_Note:_ The `unshift` method in javascript is cool because it adds to a list but
from the beginning, not from the end like `push`.

The pre-made practice project had styles already in place so that the log looks
a bit nicer with colors, but in short, on each action taken to kill a monster,
we would see the player or the monster with different colored texts, and their
action and value for heal or attack.

This showcases all the concepts seen in the section really nicely.

== Section 5: Vue: Behind the Scenes

=== Module Introduction

We now have the basics of Vue. But another fundamental piece of knowledge is
getting to know how Vue behaves _behind the scenes_.

Having the extra behind the scenes knowledge will help you as a developer, because
understanding how the tool works. You will leverage it even better.

- How Vue Works
- Understanding "Virtual DOM" & DOM Updating

=== An Introduction to Vue's Reactivity

We have to download a simple Vue app that is already pre-setup.

A simple Vue side and a view, they are already wired up. Plus styles.

- We have an input
- We can type something, press the button next to the input
- The message will be displayed below

Everything is achieved with the basic concepts we already learned about in the previous
sections.

- The moment we click the button
  - The part of the view is updated by Vue behind the scenes
    - This is called **reactivity**

The idea is that Vue tracks the data object, and all the properties will be a
part of the global object. Managed by Vue, methods and everything else is attached.

The data object in Vue, is turned in a reactive object. This is done by **proxies**.
This is a Javascript property, so that whenever a state property gets assigned a
new value to a property, Vue receives a notification. Once Vue picks up on this
change, Vue goes to the screen to check where that dynamic content is displayed
and then swaps out the UI element behind the scenes.

=== Vue Reactivity: A Deep Dive

[source, javascript]
----
let message = 'Hello';

let longMessage = message + ' World!';

console.log(longMessage);

message = 'Hello!!!!';

console.log(longMessage);
----
In Vanilla javascript once a specific variable takes a value, any related property
that in theory should also trigger an update on all related properties (reactivity),
that value doesn't change, it doesn't "auto-update". With that premise, and seeing
how Vue ends up with us assuming such a concept, can only mean that Vue is doing
the heavy lifting enabling reactivity as a concept.

This is done through **proxies**.

This is a known object in modern javascript that takes an object and a handler

[source, javascript]
----
const data = {
  message: 'Hello!',
  longMessage: 'Hello! World!'
};

const handler = {
  set(target, key, value) {
    if (key === 'message') { <.>
      target.longMessage = value + ' World!' <.>
    }

    target.message = value;
  }
}

const proxy = new Proxy(data, handler);

proxy.message = 'Hello!!!!';

console.log(proxy.longMessage); <.>
----
<.> It is within the handler that is also an object but that holds "traps", which
in this case it holds a `set` trap function, that we can listen to changes in
an object's (target) property, and based on that change also update another property
of the same object.
<.> As you can see here, this ends up being reactive to changes on one property,
and updates other related properties
<.> Lastly, we will see how the value of the `longMessage` gets updated correctly.
As if the property was directly consolidated.

Vue takes care of doing all of this under the hood. It has way more complex
code, but the essence is that it works like this. Setting up proxies and updating
related content/state properties is what allows Vue to be the way it is.

=== One App vs Multiple Apps

In all the lectures we have only had **One app**. But you can absolutely have
more than one app.

````
<section id="app">
  <h2>How Vue Works</h2>
  <input type="text" @input="saveInput">
  <button @click="setText">Set Text</button>
  <p>{{ message }}</p>
</section>
<section id="app2">{{ favoriteFood }}</section>

app.mount('#app');

const app2 = Vue.createApp({
  data() {
    return {
      favoriteFood: 'Pizza'
    }
  }
});

app2.mount('#app2')
````
Each of them is their own world though. You can't access properties of another
app from another app. So bear that in mind. Each state, each method belongs to
its own specific Vue app.

=== Understanding Templates

The correct term to refer the "html" that is connected to a Vue app. You should
use **Template**.

Sometimes things are referred as "managed HTML" but that's not the right term.
The moment that you mount your Vue app against a piece of content, that HTML
content indeed is your Vue Template.

- The first section is the template of the first Vue app
- The second section is the template of the second Vue app

Connecting through a css selector to an HTML element is the most "common" way to
setup a Vue template. But there's also a `template` property!

````
<section id="app2">
  <!-- <p>{{ favoriteFood }}</p> -->
</section>

const app2 = Vue.createApp({
  template: `
    <p>{{ favoriteFood }}</p>
  `,
  data() {
    return {
      favoriteFood: 'Pizza'
    }
  }
});
````
As you can see, you can feed the HTML through a property. You still need to mount
that app somewhere, but with this specific syntax you can write the whole content
of the mount point.

Now, this approach is not really recommended, you lose syntax highlighting, formatting
and many other nice features when you keep syntax separated. But it's a concept
to be aware of, on top of `Template`.

=== Working with Refs

So far, we have seen how we can use methods to update state properties, as well
as how to straight up two-way bind them. However, there's also another tool we
can use to retrieve DOM element values or things we might need if needed and
that is `References`

[NOTE]
====
`console.dir()` is a cool log method to see a much more detailed description of
an object (works well when analyzing DOM objects)
====

Basically, you can use a non-standard HTML property to then manifest a reference
to said DOM element:

````
<input type="text" ref="userText">

setText() {
  // this.message = this.currentUserInput;
  this.message = this.$refs.userText.value;
},
````
After you give a name to the element, which should be the value for `ref` you
can access it through `$refs`. _All Vue, built-in properties will always be
suffixed with dollar signs btw._. Inside `$refs` you get access to any ref elements
you have tagged. And just like any other DOM element, they will have all their
properties available to them.

So in this instance, instead of watching every keystroke and so on, we can just
react based on the `setText` button trigger and assign to our state property the
referenced input value. (Same behavior, different approach)

=== How Vue Updates the DOM

Reactivity => Is the mechanism to detect updates, apply those updates.

There is an extra mechanism at play though, for **performance reasons**. And
that is used with a Virtual DOM.

So, we have a template side (let's call it the backend side) to whatever is happening
on the page, we are adding non-native html tags, properties, and syntax that doesn't
render properly if parsed through a normal HTML browser. However Vue catches all
of that syntax and transforms it into a browser readable form and renders it
accordingly. That's the virtual DOM, the version of the website that is full of
framework specific lingo so that he then renders the DOM respectively.

Now, as you can see this opens up the premise that Vue is constantly re-rendering
the DOM based on whatever event takes place and all that meta-data information.
However, Vue is smart, it doesn't re-generate the entire DOM, even for elements that
actually had nothing to do with an event and don't affect and shouldn't be computed
at all.

**Only the parts that changed should be actually CHANGED**

_How can Vue ensure that the entire screen is that not the entire screen is re-rendered?_

- You could compare all the old values in the DOM with the new values in the DOM
  - Good idea, but... not that good. Reading the entire real DOM all the time
  is pretty performance intensive. Not as bad a re-rendering all the time, but not
  that better either.

**Virtual DOM** Is a JS-based DOM which exists only in memory. It has a bunch of
properties, and objects. That's its "form".

Changes are computed to the virtual DOM first, and the comparisons made in a
virtual DOM (in-memory) pinpoint the places to change and those places are then
applied to the real DOM. (Memory comparison is way more performant).

However, don't think of it too deeply, it has a bunch of performance optimizations,
and it's not that "simple". But it's good to have a general idea.

=== Vue App Lifecycle - Theory

Sometimes you need to run code during steps of components rendering. **Vue has
lifecycle hooks**

- createApp({...}) => it all starts here
  - As things are getting created, lifecycle phases start running in sequence
    - beforeCreate()
    - created()
      - Vue only knows properties, and configuration. The template is computed and
      then we move onto:
    - beforeMount() - Right before Vue is going to bring something onto the screen
    - mounted() - We see something on the screen
      - Vue handed over all HTML elements to the browser
      - A mounted Vue Instance is then a place in which we lie in wait for events/actions
        - Data changes and then:
    - beforeUpdate()
    - updated() => And we remain here indefinitely repeating a cycle between
    updated() and beforeUpdate()
    - beforeUnmount()
    - unmounted()

And that's as far theory goes, it really depends on your use case, but all these
hooks are here in place so that you can leverage them. If you know your stuff,
and identify the correct use case, USE IT.

=== Vue App Lifecycle - Practice

All the hooks can be called by name at the same level as the base `data, methods`
properties:

````
const app = Vue.createApp({
  data() {
    return {
      currentUserInput: '',
      message: 'Vue is great!',
    };
  },
  methods: {
    saveInput(event) {
      this.currentUserInput = event.target.value;
    },
    setText() {
      // this.message = this.currentUserInput;
      this.message = this.$refs.userText.value;
    },
  },
  beforeCreate() {
    console.log('beforeCreate()');
  }
});
````

The course shows us also how we can debug in the browser the `.js` file. So we
can set breakpoints on our lifecycle hook methods and analyze the current status
of the application.

`beforeCreate()` => At this point no vue controlled app is rendered.
`beforeMount()` => Still nothing visible on the screen
`mounted()` => When debugging this hook we will see things rendered

You can group hooks into:

- **The Creation Lifecycle** => This only happens one time, when the Vue app is
brought to life.
- **The Updates Lifecycle**
  - `beforeUpdate()`, `updated()` => These hooks are engaged only after some reactivity
  type event is triggered.
- **The Unmount Lifecycle**
  - `beforeUnmount()`, `unmounted()`

In order to use or leverage unmount lifecycles, you would have to kill the app on
purpose. There is the `app.unmount()` method, which is great to test this, but,
it's not that realistic. There is however a really useful use case in which unmounting
makes sense to learn and analyze from (but for now, we can just trigger manually
an app unmount)

[IMPORTANT]
====
In reality, you'd probably use a few of the hooks consistently. However, it's good
to know about all these hooks at least in a general sense.
====

== Section 6: Introducing Components

=== Module Introduction

In the previous section we talked about the possibility of having multiple Vue
apps, but the key there is that these apps **can't be connected**. But based
on the ideas set out by "multiple apps" we are going to analyze `Components`,
specifically **Vue Components**. The kicker is that they indeed share state.

=== Understanding the Problem

We basically have a pre-built project in which we have a list of friends, it holds
two people currently and displays their information. It's basically a list iterated
in nature.

We are going to generate friends based on a list of friends:

[source, html]
----
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Vue Basics</title>
  <link href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="styles.css" />
  <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script>
  <script src="app.js" defer></script>
</head>

<body>
  <header>
    <h1>FriendList</h1>
  </header>
  <section id="app">
    <ul>
      <li v-for="friend in friends" :key="friend.id">
        <h2>{{ friend.name }}</h2>
        <button @click="toggleDetails">{{ detailsAreVisible ? 'Hide' : 'Show' }} Details</button>
        <ul v-if="detailsAreVisible"> <.>
          <li><strong>Phone:</strong> {{ friend.phone }}</li>
          <li><strong>Email:</strong> {{ friend.email }}</li>
        </ul>
      </li>
    </ul>
  </section>
</body>

</html>
----
<.> In here all the rendered elements will hide or show this section that is based
on a state property.

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            detailsAreVisible: false,
            friends: [
                { id: 'manuel', name: 'Manuel Lorenz', phone: '01234 5678 991', email: 'manuel@localhost.com' },
                { id: 'julie', name: 'Julie Jones', phone: '09876 543 221', email: 'julie@localhost.com' },
            ]
        }
    },
    methods: {
        toggleDetails() {
            this.detailsAreVisible = !this.detailsAreVisible; <.>
        }
    }
});

app.mount('#app');
----
<.> After clicking on the details show buttons, we invert the boolean value of
`detailsAreVisible`.

However this currently setup has a big flaw, all the elements on the list show
their details or not. You can't just allow one specific or a specific subset to
hide or show. Even if you tried it would be cumbersome, and really verbose.

**Components can help us achieve this granularity in state and render**

=== Introducing Components

Components are great if there are certain pieces of HTML that you use a lot and
that should hold some sort of behavior (that is repeatable).

Component is an official feature of Vue.js. That you can leverage by calling a
special vue method: `component`

**Important:** A component is basically a custom HTML element. Always have component
names with a dash (kebab case). And make them **multi-word** because all built-in
html elements are single word.

A component can be seen just like **another vue app**, but that can actually live
within other vue apps. _An app that will be connected to our main app_

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            friends: [
                { id: 'manuel', name: 'Manuel Lorenz', phone: '01234 5678 991', email: 'manuel@localhost.com' },
                { id: 'julie', name: 'Julie Jones', phone: '09876 543 221', email: 'julie@localhost.com' },
            ]
        }
    },
});

app.component('friend-contact', {
    template: `
    <li>
        <h2>{{ friend.name }}</h2>
        <button @click="toggleDetails">{{ detailsAreVisible ? 'Hide' : 'Show' }} Details</button>
        <ul v-if="detailsAreVisible">
            <li><strong>Phone:</strong> {{ friend.phone }}</li>
            <li><strong>Email:</strong> {{ friend.email }}</li>
        </ul>
    </li>
    `,
    data() {
        return { detailsAreVisible: false, friend: { id: 'manuel', name: 'Manuel Lorenz', phone: '01234 5678 991', email: 'manuel@localhost.com' } };
    },
    methods: {
        toggleDetails() {
            this.detailsAreVisible = !this.detailsAreVisible;
        }
    }
});

app.mount('#app');
----
A component has a name, and then an object with the same `data()`, `methods` and
so on properties. But what's key is that each component will hold its own state.

**IMPORTANT:** The component _needs_ a template. Without `mount` because that's
not how you connect to html with components. Hence we are leveraging `template`,
in-line. But remember _later we will actually switch to a much more convenient
method_.

And lastly after we have registered our component, we can render it as if it were
a normal HTML element:

````
<section id="app">
  <ul>
    <friend-contact v-for="friend in friends" friend="friend"></friend-contact>
  </ul>
</section>
````
It's with components that we can easily replicate a piece of HTML and encapsulate
both **data** and **logic** (on top of UI)

Having this type of concept at your disposal, is an extremely useful tool when
building cool UIs.

We can then render multiple elements in a repeatable way, and they all have independent
state, independent behaviors. On top of also the ability of passing around state.
