= Notes

Notes taken from:

Vue - The Complete Guide (incl. Router & Composition API) - Udemy

== Section 1: Getting Started

=== What is "Vue.js"

_Note:_ Apparently we are at Vue 3. Vue 2 was released some time ago and then
things changed.

_Vue.js (Vue) is a JavaScript framework that makes building interactive and reactive
web frontends (= browser-side web applications) easier.

"JavaScript" => A programming language that is supported by all browsers. It allows
to manipulate the already-running page and hence provide richer user experiences.

"framework" => This is a third-party library that exposes utility functionalities
AND a "set of rules" (a clear guidence) on how to build your JavaScript application.
It gives you a clear idea and structure of how to write your application code, so it's
utility functions plus the rules.

"reactive" => The idea is that we want to give the user a modern look and feel.
Most of the time we are imitating mobile app UI/UX.

"web frontends" => With javascript we control what the user sees. Vue helps us
build javascript driven interfaces. It's all about the browser side code.

**Why use Vue?**

- Let's talk about mobile applications. They are really responsive, they are snappy,
smooth animations. It all feels like one "unit". Mobile apps and desktop apps
feel very reactive. We don't have to wait for html getting downloaded and rendering.

The only thing that might take time is data loading.

_In a traditional web page, we always waiting, it's a client-server model. Request
and response_. **But JavaScript can help us circumvent this**. And that is by
manipulating the DOM of the browser. The modern paradigm is always: We do a request
ONCE, and then everything else gets changed in the browser.

- Technically, just javascript can be used without frameworks.
	- But you have to write all code on your own (re-invent the wheel)
	- You might write suboptimal code or introduce errors & bugs
	- Working in a team might be harder because not everyone knows your structure
	and "code philosophy"
	- So frameworks try to bridge that gap, to focus more on business requirements,
	and features that help you solve the problem you are analyzing

=== Different Ways of Using Vue

We can use Vue in two main ways.

- To control parts of an HTML page, so that it's more interactive and responsive
	- Chat overlay, pieces of HTML (we don't have to use Vue for everything on a
	page if we don't need interactive elements)
	- We can build "Widgets" so that parts of a page can be controlled by Vue 

- We can also use Vue to control **everything**. This is the SPA approach. So
no markup is sent on the first request/render, but all the javascript necessary
for the bootstrapping and working of the app.

**We will start with the widget approach for simplicity's case**.

[IMPORTANT]
====
It's not about "the better approach". Move away from Dogma, each problem, will require
either one of the approaches to using Vue.
====

=== Exploring Vue Alternatives

Vue => Complete component-based UI framework, includes most core features for
modern web applications. A bit less popular than React & Angular.

Reach.js => Alternative to Vue. It's officially a library. Lean and focused
component-based UI library. Certain features (e.g. routing) are added via community
packages. (Vue has everyting built in, e.g., routing)

Angular => Complete component-based UI framework, packed with features. Uses TypeScript.
Can be overkill for smaller projects. (Big in Enterprise, and it's TypeScript-based)

In general all three are very popular and used alot. If you want to switch to a
different alternative, switching is easier once you know **one framework**. The
core concepts and paradigms are interchangable

=== Building A First App With Just JavaScript

There will be course resources that can be downloaded. The recommended editor
is `VS Code`. And of course, there are Vue extensions for it.

We will first start by writing vanilla code, to then appreciate actual Vue code.

Thje `gs-1` folder has 3 files:

- app.js
- index.html
- style.css

With just javascript we want to code a simple Todo app.

It doesn't react at all. So we need access to the markup's button, input, list

[source, html]
====
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>A First App</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <div id="app">
      <div>
        <label for="goal">Goal</label>
        <input type="text" id="goal" />
        <button>Add Goal</button>
      </div>
      <ul>
        <li>Test</li>
      </ul>
    </div>
    <script src="app.js"></script>
  </body>
</html>

====

[source, js]
====
const buttonEl = document.querySelector('button'); <.>
const inputEl = document.querySelector('input');
const listEl = document.querySelector('ul');

function addGoal() {
    const enteredValue = inputEl.value;
    const listItemEl = document.createElement('li');
    listItemEl.textContent = enteredValue;
    listEl.appendChild(listItemEl); <.>
    inputEl.value = ''; <.>
}

buttonEl.addEventListener('click', addGoal); <.>
====
<.> With vanilla javascript this is the pattern. You have to select all the
elements that are living in the markup file, you use selectors for that.
<.> And you can them programatically add new markup elements, or change properties
that after the execution "look reactive", without a page reload
<.> This is a QoL type of change, so that after you input the goal to add to the list,
then the input is cleared (so you add something new and don't have to delete yourself)
<.> And this is also another really common pattern, you will attach callbacks to
different functions that are triggered on all sorts of interactions with the UI
elements (this idea is still used in the frameworks, albeit, in more elegant and
declarative ways)

=== Re-building the App with Vue

You can import vue directly into an html by doing this:

````
<script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js"></script> 
````

(The course has a note that the import changes, because it used to be something
else)

_In order to switch to vue, first, comment the `app.js`_.

That way the code won't have any effect now on markup interactions.

The course makes a remark: The docs are there to help you, and are extremely useful.

https://vuejs.org/guide/quick-start.html

In there you can see many ways of installing/setting up Vue. However, for our purposes
and also just to know this, the easiest way to start interfacing with it, is by
importing it into your markup through a CDN.

You should import it like this:

````
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>A First App</title>
  <link rel="stylesheet" href="styles.css" />
</head>

<body>
  <div id="app">
    <div>
      <label for="goal">Goal</label>
      <input type="text" id="goal" />
      <button>Add Goal</button>
    </div>
    <ul>
      <li>Test</li>
    </ul>
  </div>
  <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js"></script>
  <script src="app.js"></script>
</body>

</html>
````

_Before you `.js` script.

Now, we can access vue's functions.

Let's get this something out the way:

[IMPORTANT]
====
The vanilla way is an **imperative** approach. We literally declare every single
thing manually. But by using something such as `Vue` we switch to a **declarative
approach**, we declare the inputs/base components, and then let Vue figure out what
to do with it, by leveraging its own functions and pre-conceptions.
====

After we have imported Vue, we can then add "directives" that then tie into javascript
code:

[source, html]
====
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>A First App</title>
  <link rel="stylesheet" href="styles.css" />
</head>

<body>
  <div id="app">
    <div>
      <label for="goal">Goal</label>
      <input type="text" id="goal" v-model="enteredValue" /> <.>
      <button v-on:click="addGoal">Add Goal</button> <.>
    </div>
    <ul>
      <li v-for="goal in goals">{{ goal }}</li> <.>
    </ul>
  </div>
  <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js"></script>
  <script src="app.js"></script>
</body>

</html>
====
<.> If you want to hook into an input and bind its value so that then the model
(backend code) is constantly receiving changes, you'd use the `v-model` directive.
<.> When hooking into UI element's events, you'd use `v-on:click="function"`
<.> And lastly if you want to iteratively render something `v-for="..."`

As you can see we are using directives that will tell Vue what we want, but he
will do the heavy lifting in the background.

[source, js]
====
Vue.createApp({ <.>
    data() { <.>
        return {
            goals: [],
            enteredValue: ''
        };
    },
    methods: {
        addGoal() { <.>
            this.goals.push(this.enteredValue); <.>
            this.enteredValue = '';
        }
    }
}).mount('#app'); <.>
====
<.> We will feed a whole object to `Vue.createApp` in there all the data of
the screen will respond to a specific property of the object, and then another
property will hold methods that then will more than likely all act as callbacks
<.> This is "by convention" always `data()`, inside you would return all the
values you would need to be tied to UI element's values
<.> This is but one method that will react to some UI element event
<.> As you can see this is referring to `goals` as in the ones that are under
`data()`, Vue does a bit of magic here, but the convention is that if you set
`this.xxx` it will trace back to the bound data that is right now the "Model" of
the screen.
<.> Lastly, we need to tell vue where is the markup that it needs to watch and
then manipulate, luckily the HTML has a selector `id="app"`, by calling `mount("#app")`
which is a CSS selector syntax, vue will find the markup, and just after setting this
we would have the same behavior that we created with vanilla javascript.

=== Vue vs "Vanilla JavaScript" (just JavaScript)

There's a lot of magic happening. But the key thing: **With Vue we define the end
result, and with the features offered by it, data and logic and UI end up connected**.

Vue allows to build any kind of app, by following this "declarative-result". Which
allows us to declare the steps, not the "how we get there".

The bigger the applications, with just JavaScript it will grow just more and more
in terms of maintenance, whilst with something like Vue, things can still remain
lean, but evolvable and maintainable. (And hopefully less-error-prone)

=== Setting Up The Course Development Environment

- VS Code
  - Dark Theme
- Shortcut
  - Format document => Ctrl + K, Ctrl + F **really important**
  - If this isn't working, install the Prettier format extension
    - And then on settings make sure prettier-vscode is selected
      - This is the baseline to have more readable code

=== Course Outline & What's In the Course

Basics => No prior Vue knowledge. Syntax, templates, directives, data, computed
properties, watchers (Foundation)
Intermediate => Components, component communication, Behind the Scenes, Forms,
Http, Routing, Animations
Advanced => Vuex, Authentication, Deployment & Optimizations, Composition API,
Re-using Code

- Dozens of Small Demos / Mini Projects
- Multiple bigger Course Projects
- Assignments, Challenges

=== How To Get The Most Out Of This Course

- Watch the Videos: At your pace
- Code along: Try things on your own (code along, code ahead)
- Repeat Concepts - Repeat videos or sections if unclear
  - All concepts should come together through a project
- Google, Stackoverflow: Search the web, on threads with the solutions. However if
you are stuck => Q&A Section. You will learn more if you help fellow students.
(Forum for discussion)
- Facing an Error? - Compare course code to your own
- Code snapshots => Can be used for debugging, troubleshooting.

== Section 2: Basics & Core Concepts - DOM Interaction with Vue

=== Module Introduction

The Essentials:

- How does Vue interact with HTML? - Templates
- How do you output dynamic content?
- How do you react to User Input?

=== Creating and Connecting Vue App Instances

Don't forget for the import:

````
<script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script> 
````

We are going to use a basic starter "project". Downloaded from the course. It
has basic css, and html and js files.

We already mentioned this, we need to mark a part of the page, that vue is going
to attach to. (You need to control that with vue app).

[source, html]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vue Basics</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="styles.css" />
    <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script> 
    <script src="app.js" defer></script>
  </head>
  <body id="app">
    <header>
      <h1>Vue Course Goals</h1>
    </header>
    <section id="user-goal"> <.>
      <h2>My Course Goal</h2>
      <p></p>
    </section>
  </body>
</html>
----
<.> We want to attach to this specific section of the markup, so we need to be
sure to make usage of `id`, this is the best candidate for marking a section to
attach Vue to.

And then we can start writing Vue code:

[source, js]
----
const app = Vue.createApp({ <.>
    data() { <.>
        return {
            courseGoal: 'Finish the course and learn Vue!' <.>
        };
    }
});

app.mount('#user-goal'); <.>
----
<.> Notice how we can create an app object, with `Vue.createApp()`, and this
can be saved under a reference variable.
<.> The pre-defined `data` property, should be a function that **always returns an
object**
<.> And inside of there we can define all sorts of properties and what type of properties
they are based on our use case/need/goal. That way they can be bound to UI elements
and things.
<.> The `app` object needs to be mounted somewhere, and you do that by calling `mount()`
and inside feeding in the form of a _css selector_ the metadata that will help
find the element we want to mount Vue to.

=== Interpolation and Data Binding

[IMPORTANT]
====
The import of Vue tip from the course is **mega important**. If you import vue
"wrongly" none of the reactivity nor anything will work as expected. So be sure
to import vue correctly.
====

And, so lastly, the final piece of the puzzle to then start displaying whatever
vue has as state, you can make usage of special syntax that only when Vue is attached
will behave in a certain way:

````
<section id="user-goal">
  <h2>My Course Goal</h2>
  <p>{{ courseGoal }}</p>
</section>
````
When you use double curly braces and inside put a name (that should refer to a
property that is under `data()`), then Vue takes care of injecting the value there
and rendering in HTML. Without vue attached to the page **you will see literally
as a string `{{ courseGoal }}`, but thanks to Vue, the module itself, you can
see magic happening. Things are scored through javascript, and rendered on the view.

**Interpolation** => Is the concept that helps declare values inside the vue app
object, and that then gets rendered in some UI component.

**Note:** Unless you are editing the HTML that is bound to the Vue app, you won't
get the "swapping" of the property value, **bear that in mind, it's key**.

Interpolation and Vue attaching is the takeaway from all of this, this is the base
concept that will allow you to bring together whatever it is that Vue offers for
reactivity and responsive UIs.

=== Binding Attributes with the "v-bind" Directive

You don't always want to use interpolation for binding data.

Let's say you want links, (you'd use an anchor `<a href...`). The link could be
hardcoded. However, we could also store the value in the vue state. And this will
allow us to make things dynamic.

````
const app = Vue.createApp({
    data() {
        return {
            courseGoal: 'Finish the course and learn Vue!',
            vueLink: 'https://vuejs.org/'
        };
    }
});

app.mount('#user-goal');
````

[source, html]
----
<section id="user-goal">
  <h2>My Course Goal</h2>
  <p>{{ courseGoal }}</p>
  <p>Learn more <a href="{{ vueLink }}">about Vue</a></p> <.>
</section>
----
<.> If you want to bind state values to properties of markup. You can't use the
double curly braces, it will be rendered as the literal string.

And so, we will have to add a specific directive. An instruction that will be
picked up by Vue, so, in this instance to set the value of an attribute dynamically,
you can write:

````
<p>Learn more <a v-bind:href="vueLink">about Vue</a></p> <.>
````
<.> In essence you have to prefix with `v-bind` and then write after a colon,
the name of the attribute you want to bind to, the value then inside will reference
directly the vue's _data property name_.

This is another key concept to know when it comes to Vue, inside of html markup
you'd use double curly braces, and when trying to bind to attributes of html
elements, you would use `v-bind`

=== Understanding "methods" in Vue Apps

For outputting and managing data, Vue offsets the responsibility to the HTML code.

Now, let's add a new requirement:

- Roll a dice, and then render based on the result a "goal".

For this, we have to code some logic. And now leverage `methods`

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            courseGoal: 'Finish the course and learn Vue!',
            vueLink: 'https://vuejs.org/'
        };
    },
    methods: { <.>
        outputGoal() { <.>
            const randomNumber = Math.random();
            if (randomNumber < 0.5) {
                return 'Learn Vue!';
            }

            return 'Master Vue!';
        }
    }
});

app.mount('#user-goal');
----
<.> Another reserved name is `methods`. This receives an object that inside will
hold different functions.
<.> In this instance we are adding a function that will calculate a goal based on
a random number

We can then actually call this method from the `HTML`

````
<section id="user-goal">
  <h2>My Course Goal</h2>
  <p>{{ outputGoal() }}</p>
  <p>Learn more <a v-bind:href="vueLink">about Vue</a></p>
</section>
````
When you use string interpolation, inside you can technically run any JS code,
the function is registered under the vue object, so this gets resolved and
executed correctly, however you _could_ also just write code _in-line_.

And if you keep on reloading the page, you will se how the goal text changes,
due to the logic that calculates a random number on each iteration. This is the
base concept to understand so that later down the line you can build tons of
dynamic pages based on logic, binding and string interpolation.

=== Working with Data inside of a Vue App

It all depends on what you're building, and the goal. However, let's talk about
how to register Vue data, and how to leverage it.

By leveraging Vue `data()`, you can see how magic can happen:

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            courseGoalA: 'Finish the course and learn Vue!', <.>
            courseGoalB: 'Master Vue and build amazing apps!',
            vueLink: 'https://vuejs.org/'
        };
    },
    methods: {
        outputGoal() {
            const randomNumber = Math.random();
            if (randomNumber < 0.5) {
                return this.courseGoalA; <.>
            }

            return this.courseGoalB;
        }
    }
});

app.mount('#user-goal');
----
<.> You can register some extra properties, in this instance for saving goals.
<.> And you can then leverage `this` to reference those state properties by name.
This might look super strange, since `this` is a really tricky reserved name in
javascript

Vue, will always take all the properties under `data()` and it will register them
(alongside the methods in `methods`) as part of a global state. **This** is what
enables us having the ability to call them with `this` and also for the markup
to reference both methods and properties directly, regardless of interpolation or
data binding constraints.

=== Outputting Raw HTML Content with v-html

There's another directive that is really useful. And that comes when you have
scenarios in which you want to render structured HTML code. If you use html
elements in a string and you output with interpolation, then for security measures
it will not process the HTML. However, you can intentionally turn on that
processing: `v-bind`

````
<p v-html="outputGoal()"></p>
````
So you add it as an attribute, and then call any of the methods or properties that
the vue object is holding together.

The use cases for this html rendering switch are not _that many_, remember that it's
for security, it protects you against cross-site scripting. But if you ever need
to pass dynamically rendered HTML, `v-html` is your friend.

=== A First Summary

The moment we attach vue to some specific section, all the children also can get
manipulated. And when you attach vue to a section, you get access to special features
that javascript reads and then acts on. Lots of behavior under the scenes is computed,
but you only care about **declaring** what you want the behavior to be.

You _pass an object to your vue app_, and this object configures the vue app.

- data
- methods

These are all really important components of a vue object. The references across
methods and properties can be referred as `this`. The approach that Vue takes is
**_A declarative approach_**. Vue does all the magic behind the scenes, it updates
real DOM, it changes things around, _on our behalf_. As developers we define the
**final picture**, we architect based on behavior, we declare goals and those get
executed.

=== Assignment 1: Time to Practice: Data Binding

Need to create a Vue instance, use all the learned things so far.

Tasks:

- Output name
- Output age

Use vue.js. Save as properties, and output them from there.

- Output age + 5
- Output random number, and this needs to be outputted two times, one with a method
and another one without a method
- Output an image, go to Google, search for some random free to use image URL and
output the image (not throwing the URL, store that URL in the vue instance and
fetch it from there and output with vue syntax)
- Setting an `input` value with the _value attribute_

[source, html]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vue Basics</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="styles.css" />
    <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script> <.>
    <script src="app.js" defer></script>
  </head>
  <body>
    <section id="assignment">
      <!-- 1) Output your name -->
      <h2>{{ name }}</h2>
      <!-- 2) Output your age -->
      <p>{{ age }}</p>
      <!-- 3) Output your age + 5 -->
      <p>{{ age + 5 }}</p> <.>
      <!-- 4) Output a random number (0 to 1) -->
      <p>Favorite Number: {{ getRandomNumber() }}</p>
      <p>Favorite Number: {{ Math.random() }}</p>
      <div>
        <!-- 5) Display some image you found via Google -->
        <img v-bind:src="imageUrl" /> <.>
      </div>
      <!-- 6) Prepopulate the input field with your name via the "value" attribute -->
      <input v-bind:value="inputText" type="text" />
    </section>
  </body>
</html>
----
<.> Don't forget that the import of the course is "wrong". So this has to be changed.
<.> This evaluates javascript, it can just be a property reference or in-line
code execution, hence this works just fine.
<.> Remember that if you want to dynamically control attributes of HTML elements,
you have to use `v-bind:<attribute>`. That is key, after you declare the attribute
like that, you can safely execute js code or call methods or reference a property.

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            name: 'Diego',
            age: 26,
            imageUrl: 'https://future-architect.github.io/images/2025/20251022a/image.png',
            inputText: 'YO'
        }
    },
    methods: {
        getRandomNumber() {
            return Math.random();
        }
    }
});

app.mount('#assignment'); <.>
----
<.> Decided to do it like this for order purposes, and also because I noticed that
this element was encasing all the html elements for the assignment.

[IMPORTANT]
====
You can declare multiple "vue apps". Don't think it's just **one** mount that
works. But be sure to decide a good css selector. An id (`#id`) is probably the
best candidate, they have to be unique, otherwise Vue might get confused.
====

=== Understanding Event Binding

In modern web applications outputting data is half what you do. However, you
need to build reactive web applications. You need to react based on events.

We will use another testing project with pre-coded UI and some JS. But right now,
it doesn't react based on anything. We want to code behavior so that buttons trigger
some sort of event and the screen changes.

Our requirement is really easy: When we press the `Add` button we will add to
a counter, and when we press `Remove` we will decrease.

Remember, we need to leverage a declarative approach. No imperative. **Declare
the end result and let Vue do the magic**

For that we can use the `v-on` directive

````
<button v-on:click="counter">Add</button>
````

After `-on` we can select any of the native HTML attributes `focus` for example.

You can use a method that manipulates inline or calls a method:

````
<button v-on:click="onAdd">Add</button>
<button v-on:click="onRemove">Remove</button>

const app = Vue.createApp({
  data() {
    return {
      counter: 0,
    };
  },
  methods: {
    onAdd() {
      this.counter++;
    },
    onRemove() {
      this.counter--;
    }
  }
});

app.mount('#events');

````

Inline (not really good practice, but):

````
<button v-on:click="counter++">Add</button>
<button v-on:click="counter = counter - 1">Remove</button>
````

Look how little you need to write and still you get interactivity, reactivity and
so on. That's the **core asset of frameworks such as Vue**.

The framework does a lot of heavy lifting:

- Reacts to events
- Updates state and screen behind the scenes (knows where to replace)
	- Everything is JS behind the scenes. Makes life as a developer, much-much
	easier.

=== Events & Methods

As mentioned a bad practice:

````
<button v-on:click="counter++">Add</button>
<button v-on:click="counter = counter - 1">Remove</button>
````

You should put as little as javascript in the html side of a view. Even though
code is small or little, a good thing is to offload as much as possible to the
controller-model side of the view.

**Always remember to declare everything that vue leverages alongside its directives
inside the object that's in `Vue.createApp({})`.

Don't create functions outside, vue won't be able to see them, nor leverage them
correctly. Remember that the framework does a lot of fancy things behind the scenes,
remember that it's declarative and that is the philosophy behind all of its features.

The _better way of doing_ => Coding the logic in Javascript. And then pointing to
it from HTML. Even though you get the same result, as a habit, starting with methods
abstracting away all logic, is cleaner code.

[IMPORTANT]
====
When you write `v-on:click="add"` or `v-on:click="add()"`. Both syntaxes are correctly
resolved by Vue. But the "more correct way" would be without actually executing the
method = `add`. That's closer to vanilla JS.
====

Remember, we can bind methods to HTML events, and it's a core feature for building
rich modern web apps.

=== Working with Event Arguments

Let's add and deduct not just _1_ in the method. That can be done by accepting a
parameter.

````
methods: {
	onAdd(number) {
      this.counter += number;
    },
    onRemove(number) {
      this.counter -+ number;
	}
}

<button v-on:click="onAdd(5)">Add</button>
<button v-on:click="onRemove(5)">Remove</button>
````

Look how we extend the method to take one argument, and we can then declare in
the markup the argument. This is an important pattern. And that is because in reality,
you will have this scenario when building some use case. So sending event arguments,
turns really trivial actually.

=== Using the Native Event Object

Let's enhance the mini-dummy a bit more. We will add an input field and then as
something gets typed, the contents will be outputted in a another html element
below:

````
<button v-on:click="onAdd(5)">Add</button>
<button v-on:click="onRemove(5)">Remove</button>
<p>Result: {{ counter }}</p>
<input v-on:input="onInput" type="text">
<p>Your name: {{ name }}</p>
````
Notice how we are attaching to the native element's `input` event a method. In
the javascript side we would then code something like this:

````
const app = Vue.createApp({
  data() {
    return {
      counter: 0,
      name: '',
    };
  },
  methods: {
    onAdd(number) {
      this.counter += number;
    },
    onRemove(number) {
      this.counter -= number;
    },
    onInput(event) {
      this.name = event.target.value;
    }
  }
});

app.mount('#events');
````

So, by default, html events will always get an event automatically fed to them,
even on our `v-on:click` instance, we would get an event back, however because
we wrtoe `onAdd(5)` and `onRemove(5)`. We overwrote that stock behavior and fed
a custom argument. But on our `onInput` case, we are not overriding, we are letting
it keep the original behavior, the browser will provide the default event object.
This will have full of information about the event, HTML element in which the
event ocurred, and we can read the current value stored in the element from there.

The `target` will almost always refer to the HTML element that triggered the event,
and in the case of an input, the `value` property will yield whatever is stored
inside.

[NOTE]
====
This is all vanilla javascript and html behavior. You can even search for mdn
docs in google by typing something like "MDN input" for further information on
the API and how to leverage it.
====

After this, and we reload, we can start typing in the input, and we will see
'real-time" how the name changes in the places where updating is needed.

If you open the Dev Tools of the browser, and you type, you will see how the
parts that change, the text flashes. This is a corroboration that Vue is indeed
changing really specific HTML components. It's not changing the whole page, by
being smart Vue saves on performance.

[NOTE]
====
You could have an scenario in which you need to pass the native event, plus some
extra arguments. For this you can leverage a reserved keyword `$event`. Vue recognizes
this and will inject the native element for you on the method calling
====

````
<input v-on:input="onInput($event, 'Diego')" type="text">

onInput(event, name) {
	this.name = event.target.value + ' - ' + name;
}
````
Be sure to remember this, it might come in handy when you least expect it.

=== Exploring Event Modifiers

Another useful feature built into Vue.

Inheriting errors of the past, or well, different ways of thinking, if you have
a form like this:

````
<form>
	<input type="text">
	<button>Sign Up</button>
</form>
````
By default, when pressing the button, then the page will refresh, it will try to
send an HTTP request to the server serving the page. And in our case of an SPA,
we will lose **all our state**.

Typically, you want to prevent this browser default, and you should handle this
manually with javascript. **In the Vue app**. Programmatically read, treat and
send requests to a backend.

You can listen to the submit event: `v-on:submit="submitForm"` And do something
like this:

````
<form v-on:submit="submitForm">
	<input type="text">
	<button>Sign Up</button>
</form>

submitForm(event) {
	event.preventDefault();
	alert('Submitted!');
}
````
We attach ourselves to the form's `submit` event, and we use the native event object
to stop the reload of the page with `preventDefault()` that way we don't lose all
our state. However Vue has a nicer way:

**Event modifiers:** Help you change event behaviors, depends on the event type
and there are a couple of modifiers such as: `v-on:submit.prevent`. There's also
another for preventing propagation. Modifiers can help change "when an event occurs"
also.

With less code, you keep the same behavior. You can even modify a click event
to just react to right clicks `.click`. _Is this useful?_ Who knows, there may
be a case in which it is. So don't dismiss it just yet.

**There's also key modifiers**. What if we wanted to update an element only when
a user presses "Enter"?

````
<input v-on:input="onInput($event, 'Diego')" v-on:keyup.enter="confirmInput" type="text">
<p>Your name: {{ confirmedName }}</p>
````

And the code behind:

````
const app = Vue.createApp({
  data() {
    return {
      counter: 0,
      name: '',
      confirmedName: '',
    };
  },
  methods: {
    onAdd(number) {
      this.counter += number;
    },
    onRemove(number) {
      this.counter -= number;
    },
    onInput(event, name) {
      this.name = event.target.value + ' - ' + name;
    },
    confirmInput(event) {
      this.confirmedName = this.name;
    }, 
    submitForm(event) {
      alert('Submitted!');
    }
  }
});

app.mount('#events');
````
Notice how we have `v-on:keyup.enter` to react to another event. And only when
pressing enter on the input element (should be focused), then we actually update
an internal `confirmedName` property that then is set to be rendered in the below
html `<p>` tag. This is a cool idea that could be useful under specific workflows.

=== Locking Content with v-once

Nieche scenarios. But still let's have a look at it.

_What if we want for a value to never change after a first update?_

````
<p v-once>Starting Counter: {{ counter }}</p>
<p>Result: {{ counter }}</p>
````
With `v-once`, Vue prevents the binding to the rendered value. It will only be
rendered once, you lock an initial value. And any further update to the same
property will not be reflected on these "frozen" elements.o

=== Assignment 2: Time to Practice: Event Binding

[source, html]
----
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Vue Basics</title>
  <link href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="styles.css" />
  <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script>
  <script src="app.js" defer></script>
</head>

<body>
  <header>
    <h1>Events</h1>
  </header>
  <section id="assignment">
    <h2>Event Practice</h2>
    <!-- 1) Show an alert (any text of your choice) when the button is pressed -->
    <button type="button" v-on:click="showAlert">Show Alert</button> <.>
    <hr />
    <!-- 2) Register the user input on "keydown" and output it in the paragraph (hint: event.target.value helps) -->
    <input v-on:keydown="onKeydown" type="text" />
    <p>{{ keyedText }}</p>
    <hr />
    <!-- 3) Repeat 2) but only output the entered value if the ENTER key was pressed -->
    <input v-on:keyup.enter="snapshot" type="text" /> <.>
    <p>{{ snapshotText }}</p>
  </section>
</body>

</html>
----
<.> Using the syntax `click="showAlert"` is closer to the official syntax and to
conventions of HTML and JS working together. It also makes you write less code (by
offsetting to cognitive load).
<.> The solution of the course actually also put the `v-on:keydown="onKeydown"`
here, so two event listeners. I mean, from a "performance" standpoint, the enter
is more than enough, otherwise you are just using computing power for the reading
of every keystroke.

[source, js]
----
const app = Vue.createApp({ <.>
    data() {
        return {
            keyedText: '',
            snapshotText: '',
        }
    },
    methods: {
        showAlert() {
            alert('pressed');
        },
        onKeydown(event) { <.>
            this.keyedText = event.target.value;
        },
        snapshot(event) {
            this.snapshotText = event.target.value;
        }
    }
});

app.mount('#assignment'); <.>
----
<.> Never forget we need to create a vue app. This will allow us to then inject
as much reactivity as we want.
<.> And we have to attach the app to some part of the HTML
<.> Keydown is executed when the key is released, so the behavior that the input
lags behind one character is **expected**. Also, `event` is a browser default
object that you get when an HTML element triggers an event

=== Data Binding + Event Binding = Two-Way Binding

Our goal is to have **another button**. That helps us reset the input in the
input element. (**Not just the state value**). We could select the input element
manually, and so on. But that's hacky, it's just hacky. Vue has features that allow
for us to both manipulate some element's value through a side effect.

````
<input v-bind:value="name" type="text" v-on:input="setName($event, 'Schwarzmüller')">
<p>Your Name: {{ name }}</p>
<button v-on:click="resetInput">Reset Input</button>
````
`v-bind:value`, allows to enable _two way binding_. By not just listening to the
input, you can send the stored value to the element, it's a really common use case.

So common, we can simplify adding two events with a simple directive:

````
<input type="text" v-model="name">
````
This holds the same behavior, but with less code. **Two-way binding**, is that we
are listening to the input event, and at the same time we are writing back the value
to the HTML element, **through its property**. It's super useful, since updating
values is so clean and useful.

=== Methods used for Data Binding: How It Works

So far we know:

- DOM Interaction, Templates & Data Binding
- Event Handling = Two-way binding

_"Advanced Reactivity"_

What if we want the behavior of computing a state value? Like adding a prefix to
a name? - Mr <xxx>

````
<p>Your Name: {{ outputFullName() }}</p>

outputFullName() {
  if (this.name === '') {
    return '';
  }

  return this.name + ', Sir!';
}
````
This is great, we add now a computation behind a method that outputs a string in
an element. _However it's not_. Because Vue, whenever a change in state is detected,
**will always run any method behind any non-event bound attribute**. If you have
tons of methods all spread across your view, you will be re-running all of them
on each state change. That's not ideal, **the reason Vue does this**, is that he
has to run them to know if the state that changed was affected so he can then
update the view accordingly.

_There's a better way of displaying computed properties_

=== Introducing Computed Properties

_First, we could put the code in-line instead of a method_ That way vue can see
what's getting used and perhaps not run the javascript execution.

**Not that readable though**

And so, we can use a third option of the vue createApp method:

[source, js]
----
const app = Vue.createApp({
  data() {
    return {
      counter: 0,
      name: ''
    };
  },
  computed: {
    fullname() { <.>
      if (this.name === '') {
        return '';
      }

      return this.name + ', Sir!';
    }
  },
  methods: {
    setName(event) {
      this.name = event.target.value;
    },
    add(num) {
      this.counter = this.counter + num;
    },
    reduce(num) {
      this.counter = this.counter - num;
      // this.counter--;
    },
    resetInput() {
      this.name = '';
    },
    outputFullName() {
      if (this.name === '') {
        return '';
      }

      return this.name + ', Sir!';
    },
  }
});

app.mount('#events');
----
<.> Just like `methods` this needs to receive an object, and inside there will
be functions. However, the naming convention is **really important**. Because in
the HTML we would call this like a property, no execution `method()`.

For performance, it's better using computed properties, that way you won't run
the calculation every single time. Computed properties will keep track of the
dependencies, so Vue will know if he has to actually run the logic or not.

````
<p>Your Name: {{ fullname }}</p>
````
You use computed properties for outputting things just like this. Straightforward.

=== Working with Watchers

A key feature for outputting dynamic values is indeed computed properties. However
there is another reactivity feature: **Watchers**.

This is basically a function that runs, every-time a dependency changes. You could
actually replace computer properties for watchers (but that might not be the
best idea)

- Computed and data properties should not clash.

So a watcher, is "attached" to a name by matching the name:

[source, js]
----
data() {
  return {
    counter: 0,
    name: '', <.>
    fullname: '',
  };
},
watch: {
  name(value) { <.>
    this.fullname = value + ' ' + ', BOSS!'; <.>
  }
},
----
<.> So we are going to configure a watcher for `name`.
<.> The watcher automatically can receive the latest value of the property that's
being watched, and you can also receive a second parameter that will old an old
value
<.> And in here you can then run some specific logic, as you can see by doing this
we are emulating the same behavior as we had with the computed property

But this is not good if say we have "two dependencies", say for fullname we compute
with two propeties: `firstName` and `lastName`, we would have to write two
watchers and do a lot of similar looking code.

A computed property will easily grab as many properties and detect changes in them
to then update as needed.

Watchers, are good when focusing on **one value** and we need to perhaps control
something in it, say a counter that after going to 50, it has to be reset to 0.
Or something akin to that. In this scenario using computed properties you'd
have lots of issues.

**Another example:** HTTP requests, timers.

=== Methods vs Computed Properties vs Watchers

Methods:

- Use with event binding OR data binding
- Data binding: Method is executed for every "re-render" cycle of the component
- Use for events or data that really needs to be re-evaluated all the time

Computed Properties:

- Use with data binding
- Computed properties are only re-evaluated if one of their "used values" changed
- Use for data that depends on other data

Watch:

- Not used directly in template
- Allows you to run any code in reaction to some changed data (e.g., send Http
request etc.)
- Use for any non-data update you want to make

_Note:_ You are probably going to use the least: Watchers. Because the other
types are highly used in all sorts of use cases.

=== v-bind and v-on Shorthands

`v-on` was used a lot, and `v-bind` also.

Instead of `v-on:click`, you can use the shorthand `@click=''`. This can still
be combined with modifiers, it's just that `@` is used. It's less code to write,
it's up to you to use it, but **be consistent**. Also `v-bind` can turn into `:value="..."`

=== Assignment 3: Time to Practice: Reactivity

Straight forward

[source, html]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vue Basics</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="styles.css" />
    <script src="https://unpkg.com/vue@3.4.9/dist/vue.global.js" defer></script>
    <script src="app.js" defer></script>
  </head>
  <body>
    <header>
      <h1>Reactivity in Action</h1>
    </header>
    <section id="assignment">
      <button @click="onAddFive">Add 5</button> <.>
      <button @click="onAddOne">Add 1</button>
      <!-- 1) Connect the buttons and calculate a value (a number) -->
      <!-- Show "Not there yet" until you reach a result of exactly 37 -->
      <!-- Show "Too much!" if the result is greater than 37 -->
      <p>Result: {{ result }}</p> <.>
      <!-- 2) Watch for changes in "result" and reset the value to 0 after 5 seconds -->
    </section>
  </body>
</html>
----
<.> Using the short handle `@click`
<.> This is actually a computed property, yet referenced as if it was a normal property.

[source, js]
----
const app = Vue.createApp({
    data() {
        return {
            counter: 0,
            timeout: null
        };
    },
    watch: {
        counter(value) {
            const that = this; <.>

            if (that.timeout == null && that.counter !== 0) { <.>
                that.timeout = setTimeout(() => { <.>
                    alert('Counter reset!');
                    that.counter = 0;
                    that.timeout = null;
                }, 5000);
            }
        }
    },
    computed: {
        result() {
            if (this.counter < 37) {
                return 'Not there yet';
            }

            if (this.counter > 37) {
                return 'Too much!';
            }

            return this.counter;
        }
    },
    methods: {
        onAddFive() {
            this.counter += 5;
        },
        onAddOne() {
            this.counter += 1;
        }
    }
});

app.mount('#assignment');
----
<.> Due to the fact that when doing a `setTimeout` the handler has its own context,
we have to capture the outside method's `this` under `that`
<.> This is a bad attempt at having the timeout only run once, and not multiple
timeouts. It still shows 2 alerts always.
<.> And yeah, we are saving a timeout reference to mark that we allocated a timeout
already, and inside we are both resetting the counter and also clearing out the
timeout again for subsequent runs.

=== Dynamic Styling with Inline Styles


