= Introduction

I realized, I might not have the best basics whent it comes to Microsoft SQL.
And so, this is a literal refreshing, and powering up of those skills/knowledge.

The content of these notes will be based around this course:

https://www.udemy.com/course/complete-microsoft-sql-server-database-administration-course/[Udemy Course]

But of course, the idea is to also make my own ideas, investigate even further and
note all those extra bits and pieces that (imo) give a much rounder depth of
knowledge than just limiting yourself to course content.

== Complete Microsoft SQL server Database Administration Course

=== Introuction

Two instructors. They seem to be veterans with 20+ years of experience in IT
plus reputable degrees from good unis.

_Databases are my passio_ and the _Accidental DBA_ bits lead me to believe these
are green flags of the course.

=== Course Overview

Seems we will get a good mix of theory on top of practical stuff. That's good,
since my opinion is always to know your basics/theory well enough so that you
can then apply all of that practically. We are already pretty far away from
what many tutorials and materials used to be just a "copy what I do, and don't
ask questions".

Looking forward to learning interesting concepts on top of actually applying
them. _Besides just basics_. Since, well, I like learning, but also because when
push comes to shove and I need to also help a discussion with extra knowledge
that some might not have at the moment, that's when a difference can be made.
And we can ship things faster, and **get that user need fulfilled**.

=== Introduction to a Database

We know this. But in short.

- Data = Any piece of info that is unstructured but that can mean something
in a certain context (date, age, height, name)
- Databases are a solution to manage large volumes of data easily, with a way
better framework than a spreadsheet, and taking a fraction of size.
- There are powerful concepts in databases such as `joins`, `groups` and many
others. Things that in Excel are not a thing, or trying to replicate is also
way harder.

=== What is RDBMS?

Relational Database Management System.

So, a Relational Database is but **one** type of database. It uses a **structure**
that allows us to **identify and access data** in relation to another piece of data
in the database. Often, data in a relational database is organized into **tables**.

Here's an example of how the data would be organized:

.Employees Table
[cols="1,2,2,1", options="header"]
|===
| ID | First Name | Last Name | Department
| 1  | John       | Smith     | Engineering
| 2  | Maria      | Garcia    | Marketing  
| 3  | David      | Chen      | Sales
| 4  | Sarah      | Johnson   | HR
|===

.Addresses Table
[cols="1,3,2,2", options="header"]
|===
| Employee ID | Street Address       | City       | State
| 1           | 123 Main Street      | Boston     | MA
| 2           | 456 Oak Avenue       | Chicago    | IL
| 3           | 789 Pine Road        | Houston    | TX
| 4           | 321 Elm Boulevard    | Phoenix    | AZ
|===

Now, zooming out of this SQL world. Let's go back to spreadsheets for another example,
you can in theory organize data into _tables_ right? They might look the same,
but their properties are fundamentally different. Excel tables have no inherent
relation between them, and you certainly can't apply operations between tables
that can perhaps refine, extrapolate or summarize the data that both tables
hold. (Can't combine to pull **info** out of **data**).

**_Now going back as to how SQL Tables are different_**

Say, I have the data about employees, and those employees' addresses. What if I ask
the question _How can I get Diego's address_? Well you might have in both tables
a common field such as `ID` or `Employee ID` and by matching that specific piece
of data between the two tables, you can build your way into knowing _Diego's address_.

And so, the course will focus on how to wrap our head around the concept of SQL
tables, and how we can use them to store data, and refine it, and query it, and
overall make it work for us so that really complex pieces of info are structured
in such a way we can understand them (there's logic to them) but also are under
a framework that is extremely powerful when getting information out of data.

=== What is SQL?

Structured Query Language = It's a **programming language** used to communicate with
data **stored** in a **relational database management system**. SQL syntax is similar to
English language, which makes it relatively easy to READ/WRITE/UPDATE/TRANSLATE
data.

_S Q L_ or _Sequel_. Pronounce it either way.

Why is it called like that? It actually was created with the name Structured English
Query Language. And it was named **sequel**. But that was trademarked, and so,
to avoid lawsuits, it was changed to `SQL`.

[IMPORTANT]
====
SQL IS NOT A DATABASE. It is a command line language that many RDBMS use to access
data from tables.
====

Just like in Linux, there are 10K distros, and there are 10K DEs, under the hood,
they are still using `bash` they still share many tooling from what `GNU/Linux`
is.

Similarly, **SQL** has the same concept, this language has been designed specifically
to be used to pull, **query** data from a database. And we have tons of relational
databases out in the market (PostgreSQL, SQLite, MySQL, Microsoft SQL, etc).
_The correct way to define them with a general term is Relation Database Management
Systems_

An example of a statement is: `SELECT * FROM tablename;`. Check this statement out,
it almost reads as english, the idea is to be perceived that way. Later you will
see how there are other words that are _powerful_ operators like `WHERE`, `AND`,
`OR`, `GROUP BY` amongst others.

=== Top 5 RDBMS using SQL

- Oracle DB = Old, one of the biggest database vendor in IT.
- Microsoft SQL Server = Old, amongst the first ones actually, it's consired as
really stable, secure and reliable. It competes against Oracle and IBM DB2.
- MySQL = Swedes, community developed, open-source. SUN Microsystems bought it.
Then Oracle got SUN Microsystems. Even though this is open-source, there are
commercial licenses from Oracle. _Easy to use, inexpensive, reliable, large
community_.
- PostgreSQL = Community developed, open-source, (Successor of Ingres).
- MariaDB = Community developed, open-source, this actually is a fork of MySQL.
Because someone was concerned about the Oracle acquisition. Hence it branched off
and became its own thing. This actually was done by the original people that made
MySQL.

=== Introduction to Microsoft SQL Server

MSSQL = Microsoft Server SQL is a suite of database software published by Microsoft
and used extensively in enterprise world.

- Features:
	- A relational database engine which stores data in tables, columns and rows.
	- Integration Service (SSIS), which is a data movement tool for importing,
	exporting and transforming data.
	- Reporting Service (SSRS), which is used to create reports and serve reports
	to end users.
	- Analysis Sevice (SSAS), which is a multidimensional database used to query
	data from the main database engine.

In this course we will work with MSSQL 16, 19. And work on a Windows Server 2016, 2019.
"machine". Depending on which SQL Server version you decide to use, then you will have to
match the right OS.

Oh yeah we will use the full **Enterprise Version** for both RDBMS and OS. They
have a trial of 180 days (about 6 months). _We should finish the course by then_.

[NOTE]
====
85% of corporate companies around the world use MSSQL 16 or 19, or older, hence this
course will focus around them. (_That way you can have the biggest chances of saying
you know how to work with a version that a potential employer might have a need for_)
====

**SQL Server Management Studio** is an additional software we have to download to
be able to query data, run reports, manage tables and rows, perform backups and
analyze performance charts.

_Note:_ Even though they have a year in their name, they are not actually released
on those years.

The most recent versions are:

- SQL Server 2014
- SQL Server 2016 **
- SQL Server 2017
- SQL Server 2019 **

.Pros and Cons
[cols="2,2", options="header"]
|===
| Various supported versions   |   Expensive Enterprise edition
| Online product documentation |   Difficult licensing process that's always changing
| Microsoft premiere support   |
| On-premises and cloud database support |
| Plenty of tools and applications
| Support for use on Linux
|===

[IMPORTANT]
====
The main idea of the course is not to sell you on Microsoft SQL. But to make you
fluent in SQL. The language that is _more or less_ the universal spoken language by
all the major RDBMS out there. So if you know how to use it to query, filter, manipulate
data, you can easily jump between all the different databases.
====

=== Different editions of Microsoft SQL

- Enterprise Edition = This delivers **high-end data center** capabilities with
**blazing fast performance**, unlimited virtualization, end-to-end business intelligence.
So basically high service levels for mission critical workloads and end-user
access to data insights.
- Standard Edition = **basic data management** and business intelligence database
for departments and **small organizations** to run their applications and support
common development tools for on premise and cloud, it enables effective database
management with minimal IT resources.
- Web = **Low-total-cost-of-ownership** for **web hosting companies**. E-commerce
sites use this a lot.
- Developer = This is basically **Enterprise** but the idea is for testing purposes,
and also learning. You can't use this for production though, if Microsoft gets
word of some company using this for production. You can get easily get sued.
- Express = **entry, free level database** The idea is something small to start
with, Microsoft's idea with this tier is for people to start small, and if things
work out really well, they seamlessly upgrade this edition to the "better ones"
seamlessly.

The idea behind aiming for the **Enterprise Edition** choice of usage, is that
you will get exposed to the full capabilities of the suite that way. Since it has
all the features, and it focuses on the most complex problems, since this is the
_corporate world_ with different needs than small businesses (which are still valid
things to be respected, but the nature of the problems that each organization tries
to solve vary in scope and just overall amount of users).

=== Quiz 1: Introduction

- What is a database?
R: A database is an organized and systematic collection of data generally stored
and accessed electronically from a computer system

- What is the difference between spreadsheet and database?
R: A lot, but databases storage costs are less, and give a way better framework to
work with data so that you can really manipulate and do what you will with it.

- What is a difference between database and relational database?
R: DBMS store data as file whereas RDBMS stores data in a tabular form, AND In
database the data elements need to access individually and in RDBMS multiple data
elements can be accessed at the same time.

- In RDBMS an identical field in one table can be used to pull data from another table
R: True

- SQL stands for:
R: Structured Query Language

- Which year SEQUEL was first invented by IBM?
R: 1970

- Which of the following is NOT a relational database
R: MongoDB

- Oracle DB is an open source RDMBS
R: False

- What is the difference between SQL and MySQL?
R: SQL is a standard language for retrieving and manipulating structured databases.
On the contrary, MySQL is a relational database management system. AND SQL is used
to query and manage RDBMS.

- MariaDB is named after
R: Monty's younger daughter, Maria.

- Which of the following is NOT MS SQL version?
R: 2015

- Which of the following is Development edition of MS SQL?
R: Basically, ALL FEATUREs, but its intended purpose should be testing environments.

== Download, Install and Configure Windows

=== Welcome to Download, Install and Configure Windows

=== MS SQL Server Pre-Requisite

- Admin rights on a computer
- Hard Disk = 6 GB minimum (20 GB for the course)
- All editions of Microsoft SQL (except Express) require 1 GB of memory. Express
- 512MB, and 4 GB for Windows. We will have a Windows machine, with Microsoft
SQL installed.
- Only x64 processors are needed. 1.4 GHz, Recommended 2.0 GHz.
- OS = Windows Server 2016, or the newer 2019. Whichever is available.

=== Lab Setup

. With limited resources = You could just have your computer with OS and install
the Microsoft SQL RDBMS. If your computer is really slow, you can still use the
Express version, but many of the features of the course that will be covered won't
be accessible to you.
. The recommended approach is to **Virtualize**. We will use a virtual machine,
so that we will have a virtual machine installed with Windows Server. And we will
install Microsoft SQL Server Enterprise Edition there.

=== What is virtualization?

In the real world, in the world of infrastructures (servers), the bread and butter
is actually **virtualization**. But before, you usually just installed a OS, an app
on top of it and you were done.

This has a problem though:

- A physical server has some specs (e.g., 16 GB RAM, 4 CPU)
	- You install a OS (takes 4 GB of RAM)
		- You install services (like MSSQL)
			- And then this only takes half of all the capability of the server.
			It became a waste of resources. **Hence** virtualization came to try
			and optimize, to use that computing power and still get more value of
			it.

The infrastructure then changes:

- A physical server
	- You install a virtualization layer
		- You install tons of different OS and each one has applications running
		on it (how many will depend on the specs of the server and the requirements
		of the different virtual machines you will install)

What's the advantage? You can actually **use all the resources**. The beauty of
virtualization is also the fact that you can _three or four SOs at the same time_,
it's really important and beneficial for the world of computers (servers and infrastructures).

The main point is: **It uses all the resources of the server/machine**

=== Download and install VMWare Workstation Player

This is a virtualization layer that sits on top of your OS. (I will not, because
I'm on linux and QEMU kicks VMware's Butt)

We need the right resources:

- At least more than 4 GB of RAM (On Windows 10).
- HDD should at least have 50 GB.

[NOTE]
====
Did VMWare sell its soul or something? There's a whole website you have to go to
and register just to get an installer. Jesus.
====

=== Optional - Download and Install Oracle Virtualbox

Another virtualization software such as VMWare Player, made by **Oracle**.

=== Create a Virtual Machine

Remember:

- Computer
	- Virtualization Software (VMWare Player)
		- Virtual Machine (Container that has resources added to it). 20 - 50 GB
		of space, 4 GB RAM, 1 - 2 CPU

In VMWare Workstation you need to set the connection to Bridge, but on QEMU, things
are differently, NAT is actually what allows to connect the HOST to the VM and viceversa
on top of allowing the VM to get access to the internet.

How, we will install:
- `Windows Server 2019 Datacenter Evaluation (Desktop Experience)`
- Custom
- Allocate all the HDD
- Next
- Set a Password (Has to be somewhat complex otherwise it won't let you go past this
screen)

And yeah to unlock it is with `Ctrl + Alt + Supr`.

- Accept the default network with `Ok`
- You can disable the Server Managment to pop-up always on startup.
- On VMWare you will have to install the VMWare tools (for better experience)

- **Change the name of the machine to `LABMSSQL`**.
- Change the timezone to your timezone
- You will get a splash screen reminding you about for how long you have the
evaluation copy (and it's 180 days - 6 months). If you don't finish the course
in that amount of time and come back, you will have to install Windows Server
AGAIN.

=== Fix EFI Network Time out error for VM Player

Basically, some people get this error when trying to run the same workflow that
is shown in the Desktop.

- Head down to the physical path at which the VM is being saved.
- In that folder look for the Virtual Machine Configuration File
- Open the file and change the `firmware` key to `bios`
- The next boot should now work

=== Download and Install Windows Server (2019)

Remember:

- OS
	- Virtualization Layer (VMWare, VirtualBox, QEMU)

This is redundant (for experienced people I'd assume). It's basically the same
series of steps that we took for 2016 though. Only difference is looking up specifically
for this version instead of 16 in Google and the Microsoft Website.

=== Virtual Machine Management

How can we manage our Virtual Machine that's on the Virtualization Software?

This is obviously catered towards `VMWare Station`, but I guess the ideas that are
brought forward are things that I can totally extrapolate for any other virtualization
manager.

- You should be able to dynamically change the memory for a machine (RAM)
- You should be able to dynamically also change the disk space (expand HDD capacity)
- You should be able to add other extra interfaces (network adapter, disk reader, printer)

The idea is that VMs are way more dynamic, we can change so many things about them
on the fly, without going through the whole hassle of what an actual physical machine
would require. Hence this technology and the paradigm with which we work is so
powerful and useful.

**Note:** Most of the time you should keep your host and VM's time `synced`.

=== Quiz 2: Download, Install and Configure Windows

1. What is a hypervisor?
R: Software managing virtual machines

2. Which of the following is an example of a hypervisor?
R: Microsoft Hyper-V

3. What is a virtual machine (VM)?
R: A software emulation of a physical computer

4. Which feature allows you to capture the state of a virtual machine at a particular point in time?
R: Snapshotting

5. How does virtualization contribute to high availability in SQL Server environments?
R: By allowing quick movement of virtual machines between servers

6. What does a hypervisor manage in a virtualized environment?
R: Virtual machines

7. Which of the following is NOT a benefit of virtualization in Microsoft SQL Server environments?
R: Limited scalability

8. What does dynamic resource scaling in virtualization allow you to do?
R: Adjust allocated resources based on workload demands

== Download, Install and configure MS SQL Server

=== Welcome to Download, Install and Configure Microsoft SQL

By now we should have VM with Windows Server running. And our choice of RDBMS is
Microsoft SQL Server, so we will install it on top of this VM.

We will install

- Microsoft SQL Server
- Microsoft SQL Server Management Studio
- Configure MSSQL
- Use AdventureWorks Database

=== Which Version of SQL Server to Install?

There are many versions that have been released already:

- SQL Server 2022
- SQL Server 2019
- SQL Server 2017
- SQL Server 2016 - Mainstream support ended in July 13, 2021, but extended support
is until July 14, 2026.
- SQL Server 2014

**Mainstream Support:** There can be _paid support_ through a program and extra charges,
but this type of support basically is active, and current features can be improved and
extended, so you get more interesting things to work with. (On top of security updates)

**Extended Support:** We won't get new features or extensions to current ones, but
you will still see security updates so you have this extended time to still be safe.

So which version should you choose? It's not an easy answer.

[IMPORTANT]
====
It really depends on your business needs. Most of the time the oldest versions are
being used (because we tend to not migrate or stay up to date for very different
reasons). So it's not as black-and-white as to say _Always go for the latest version_.
Pick from the latest version one version lower, since that's where probably most
of the demand is. Besides it definitely has more time to become more stable than
the brand new version.
====

The course was made during versions 2016 and 2019. But later 2022 was dropped.

- 2019 is also widely being used now.

But just pick one version, and stick to it. That's the best advice.

=== Prerequisites for MSSQL 2016 Installation

These are good requirements for Lab and for Production environments. But of course,
for production we should have at least 6 GB of RAM (recommended), on top of (_of course_)
Microsoft's own format (NTFS, ReFS).

- Express Editions: 512 MB RAM, All other editions: 1 GB RAM
	- But recommended: 1 GB RAM, 4 GB RAM respectively
- Intel or AMD processors are okay
- And don't worry about network, that comes built-in and it's already working

**NOTE:** You need .NET Framework 4.6 for the Database Engine, Master Data Service,
or Replication.

_Considerations:_

- MSSQL 16 only works on **x64** machines
- MSSQL 16 can be installed on Windows Server 2012, 2016, 2019
- You cannot run SQL Server services on a domain controller under a local service
account
	- In English, this means that (I guess by default?), SQL Server won't run on
	the same server that has all credential and login info. (This is the Domain
	Controller, the most **sensitive and secure server**, it's literally the keys
	to the kingdom)
	- And a local service account, is the most generic type of account that can
	be registered (and used) under a Domain Controller. SQL Server cannot run
	with such an account, it needs an account specifically created and catered
	towards using the SQL Server service.
- Separate disks for Data Files, Log Files, and tempdb (This is Microsoft's
recommendations)

=== Prerequisites for MSSQL 2022 Installation

The newest MSSQL version.

So, in short. **_It requires the same things that all previous versions required_**.

_Good_.

[NOTE]
====
Okay, **ONE THING** that is different, and of course it turns like this. Is that
you can only run this in Windows 10 TH1 1507 or greater. And if this is running in
Windows Server it has to be **2016 or greater**
====

=== Download and install Chrome Browser

Okay, this isn't really one lesson on how to click some links and install. It actually
teaches you how to stop Internet Explorer of being annoying for a second.

_I'm not saying this is good, for Prod environments, definitely, being annoying is
way better than being completely laxed_.

But to stop pop-ups every 2 seconds saying that a site is not trusted:

. Open Internet Explorer
. Search for the **cog**
. Select `Internet options`
. Go to `Security`
. Select the `Trusted sites` icon
. And lower the lever of "Security level for this zone" to `Medium Low`

And when you still get the pop-ups, just check anything that says "Don't show again"
or "Continue", basically, ignore all the warnings (because we are power users and
we know what we are doing).

Even now though, you can still try and look for Chrome or Mozilla, try to download
and it won't work either. You have to go to the same screen we were before but:

. `Internet Options`
. Security
. Custom level
. Search for "Downloads"
. Mark "Enabled" instead of "Disabled"

After this, you can google whatever browser you want, and download it.

Because we are cool, we chose _Firefox_. But in a perfect world, we would go
for _Librewolf_.

It is with this new browser we should search and download "AdventureWorks Sample
Database" this is on the Microsoft Docs, it's probably a pretty widely used database
sample hence it is in Microsoft Docs even.

Download the OTLP => 2019 version. (bak file). Depending on what OS you decided to
install and what MSSQL Server you will install then you should match the specific
backup. (For the uninitiated, a `.bak` file is a typical extension for a database
backup in the MSSQL world)

=== Download MSSQL and SQL Server Management Studio

=== Install and Configure MSSQL 2016

=== Install and Configure MSSQL 2019
